import type { CurriculumSlice } from "@/types/content";

import { createFunctionGraphFigure } from "./quiz-figures";

export const g10Required1Unit1Slice: CurriculumSlice = {
  grade: {
    id: "g10",
    stageId: "senior",
    label: "高一",
    shortLabel: "高一",
    description: "从集合与函数出发，建立高中数学的抽象表达与图像理解。",
  },
  volume: {
    id: "required-1",
    stageId: "senior",
    gradeId: "g10",
    kind: "required",
    label: "必修一",
    shortLabel: "必一",
    description: "围绕集合、函数与基本数学建模展开的高中起始模块。",
  },
  chapter: {
    id: "unit-1",
    stageId: "senior",
    gradeId: "g10",
    volumeId: "required-1",
    slug: "han-shu-gai-nian-chu-bu",
    title: "第一章 函数概念初步",
    summary: "从对应关系、表示法和图像特征理解高中函数，完成初中到高中的表达升级。",
    order: 1,
    lessonIds: ["lesson-function-representation"],
    workedExampleIds: ["example-quadratic-vertex"],
    quizId: "quiz-g10-required-1-unit-1",
  },
  lessons: [
    {
      id: "lesson-function-representation",
      chapterId: "unit-1",
      slug: "han-shu-biao-shi-yu-tu-xiang",
      title: "函数的表示与图像观察",
      summary: "学会用解析式、表格和图像描述同一个函数，并从图像中读取关键特征。",
      learningObjectives: [
        "知道同一个函数可以用解析式、列表法和图像法来表示。",
        "能从函数图像中识别顶点、对称轴和增减变化。",
        "理解配方法在研究二次函数图像中的桥梁作用。",
      ],
      keyRules: [
        "函数图像是所有满足对应关系的点构成的集合。",
        "观察二次函数图像时，先看开口方向、对称轴和顶点。",
        "解析式、数值表和图像三种表示法应能互相印证。",
      ],
      bodyBlocks: [
        {
          type: "richText",
          id: "intro",
          title: "为什么高中更强调多种表示法",
          content: [
            "进入高中后，函数不再只停留在“代数式怎么算”，而是要同时观察解析式、数值变化和图像形状。",
            "当你能把同一个函数在三种表示法之间自由切换时，题目里的条件就更容易被看懂。",
          ],
        },
        {
          type: "formula",
          id: "representation",
          title: "同一个函数的三种表达入口",
          label: "函数表示",
          formulas: [
            "y=x^2-2x-3",
            "x=-1,0,1,2,3 \\Rightarrow y=0,-3,-4,-3,0",
            "\\text{图像是一条开口向上的抛物线}",
          ],
          note: "做高中函数题时，常常需要在解析式、表格和图像之间来回切换。",
        },
        {
          type: "derivation",
          id: "complete-square",
          title: "配方法如何帮助我们找到顶点",
          steps: [
            {
              id: "step-1",
              title: "先把一次项和二次项放在一起",
              expression: "y=x^2-2x-3",
              explanation: "这是原函数解析式，也是后续观察图像的起点。",
            },
            {
              id: "step-2",
              title: "把前两项配成完全平方",
              expression: "y=(x^2-2x+1)-1-3",
              explanation: "加一再减一，保持式子整体不变。",
            },
            {
              id: "step-3",
              title: "写成顶点式",
              expression: "y=(x-1)^2-4",
              explanation: "由此可以直接读出顶点在 (1,-4)，对称轴是 x=1。",
            },
          ],
          note: "配方法不是机械变形，它的目标是把“图像特征”从解析式里读出来。",
        },
        {
          type: "table",
          id: "value-table",
          title: "从数值变化验证图像对称性",
          columns: ["x", "-1", "0", "1", "2", "3"],
          rows: [
            {
              id: "row-y",
              cells: ["y=x^2-2x-3", "0", "-3", "-4", "-3", "0"],
              emphasis: true,
            },
          ],
          note: "当 x 在 1 左右等距离变化时，函数值呈现对称，这和抛物线的轴对称性质一致。",
        },
        {
          type: "figure",
          id: "quadratic-graph",
          title: "图像与解析式对应观察",
          label: "函数图像",
          figure: createFunctionGraphFigure("二次函数图像示意图", {
            graphType: "quadratic",
            equationLabel: "y=x^2-2x-3",
            domain: [-3, 5],
            coefficients: [1, -2, -3],
            highlightedPoints: [
              { x: -1, y: 0, label: "(-1,0)" },
              { x: 1, y: -4, label: "(1,-4)", emphasis: true },
              { x: 3, y: 0, label: "(3,0)" },
            ],
          }),
          note: "先看顶点，再看与 x 轴的交点，最后看整体开口方向，读图会更稳。",
        },
        {
          type: "tip",
          id: "reading-tip",
          title: "易错提醒",
          content: "顶点坐标和对称轴不要混淆：顶点是点，对称轴是直线；看图像时要分开表述。",
        },
      ],
      relatedExampleIds: ["example-quadratic-vertex"],
      order: 1,
      videoPlaceholder: {
        title: "板书微课：从解析式读图像",
        durationLabel: "5 分钟",
        description: "通过配方法把一般式转成顶点式，理解解析式和图像之间的对应关系。",
      },
    },
  ],
  workedExamples: [
    {
      id: "example-quadratic-vertex",
      chapterId: "unit-1",
      slug: "read-quadratic-graph",
      title: "由解析式判断二次函数图像特征",
      summary: "通过配方法快速判断顶点、对称轴和开口方向。",
      problem: "已知函数 y=x^2-2x-3，求它的顶点坐标、对称轴，并说明图像与 x 轴的交点。",
      steps: [
        {
          id: "step-1",
          title: "配方法改写解析式",
          content: "把 y=x^2-2x-3 改写成 y=(x-1)^2-4，由此能直接读出顶点和对称轴。",
        },
        {
          id: "step-2",
          title: "判断开口方向",
          content: "二次项系数 a=1>0，所以抛物线开口向上。",
        },
        {
          id: "step-3",
          title: "求与 x 轴的交点",
          content: "令 y=0，得 x^2-2x-3=0，解得 x=-1 或 x=3，所以交点是 (-1,0) 和 (3,0)。",
        },
      ],
      answer: "顶点为 (1,-4)，对称轴为 x=1，与 x 轴交于 (-1,0)、(3,0)。",
      commonMistakes: [
        "把顶点误写成 (1,4)，忽略了常数项是 -4。",
        "只看见两个零点，却没有先说明图像开口方向。",
      ],
      relatedLessonIds: ["lesson-function-representation"],
      order: 1,
    },
  ],
  quiz: {
    id: "quiz-g10-required-1-unit-1",
    chapterId: "unit-1",
    title: "函数图像识读小测",
    instructions:
      "先看图像，再完成多选、数值、表达式和分步作答，体会高中函数题“式图结合 + 过程表达”的基本节奏。",
    passingScore: 60,
    questions: [
      {
        id: "quiz-g10-q1",
        quizId: "quiz-g10-required-1-unit-1",
        type: "fill-blank",
        difficulty: "basic",
        stem: "观察图像，写出函数 y=x^2-2x-3 的顶点横坐标与对称轴。",
        figure: createFunctionGraphFigure("函数图像小测图", {
          graphType: "quadratic",
          equationLabel: "y=x^2-2x-3",
          domain: [-3, 5],
          coefficients: [1, -2, -3],
          highlightedPoints: [{ x: 1, y: -4, label: "(1,-4)", emphasis: true }],
        }),
        blanks: [
          {
            id: "vertex-x",
            prompt: "顶点横坐标",
            hint: "观察对称轴与顶点横坐标是否一致。",
            acceptableAnswers: ["1"],
            placeholder: "填写数字",
          },
          {
            id: "axis",
            prompt: "对称轴",
            hint: "用直线方程形式填写。",
            acceptableAnswers: ["x=1", "x = 1"],
            placeholder: "填写直线方程",
          },
        ],
        explanation: "由图像可见抛物线关于直线 x=1 对称，且顶点的横坐标就是 1。",
        relatedLessonIds: ["lesson-function-representation"],
        relatedExampleIds: ["example-quadratic-vertex"],
      },
      {
        id: "quiz-g10-q2",
        quizId: "quiz-g10-required-1-unit-1",
        type: "multiple-choice",
        difficulty: "advanced",
        stem: "根据函数 y=x^2-2x-3 的图像，下面哪些说法正确？",
        figure: createFunctionGraphFigure("函数图像多选题", {
          graphType: "quadratic",
          equationLabel: "y=x^2-2x-3",
          domain: [-3, 5],
          coefficients: [1, -2, -3],
          highlightedPoints: [
            { x: 1, y: -4, label: "(1,-4)", emphasis: true },
            { x: -1, y: 0, label: "(-1,0)" },
            { x: 3, y: 0, label: "(3,0)" },
          ],
        }),
        options: [
          { id: "a", label: "A", content: "顶点坐标是 (1,-4)" },
          { id: "b", label: "B", content: "抛物线开口向下" },
          { id: "c", label: "C", content: "图像与 x 轴交于 (-1,0) 和 (3,0)" },
          { id: "d", label: "D", content: "对称轴是 x=-1" },
        ],
        correctOptionIds: ["a", "c"],
        explanation: "从图像可见顶点是 (1,-4)，与 x 轴有两个交点，且对称轴应是 x=1，不是 x=-1。",
        relatedLessonIds: ["lesson-function-representation"],
        relatedExampleIds: ["example-quadratic-vertex"],
      },
      {
        id: "quiz-g10-q3",
        quizId: "quiz-g10-required-1-unit-1",
        type: "numeric",
        difficulty: "advanced",
        stem: "写出函数 y=x^2-2x-3 的最小值。",
        prompt: "最小值",
        acceptableAnswers: ["-4"],
        placeholder: "填写数值",
        explanation: "抛物线开口向上，顶点纵坐标是 -4，所以函数最小值为 -4。",
        relatedLessonIds: ["lesson-function-representation"],
        relatedExampleIds: ["example-quadratic-vertex"],
      },
      {
        id: "quiz-g10-q4",
        quizId: "quiz-g10-required-1-unit-1",
        type: "expression",
        difficulty: "challenge",
        stem: "化简表达式 2(x-1)+3(x+1)。",
        prompt: "化简结果",
        acceptableAnswers: ["5x+1", "5*x+1"],
        placeholder: "填写化简后的表达式",
        variable: "x",
        explanation: "去括号后得 2x-2+3x+3，合并同类项得到 5x+1。",
        relatedLessonIds: ["lesson-function-representation"],
      },
      {
        id: "quiz-g10-q5",
        quizId: "quiz-g10-required-1-unit-1",
        type: "step-by-step",
        difficulty: "challenge",
        stem: "由函数 y=x^2-2x-3 求图像与 x 轴交点的横坐标。",
        steps: [
          {
            id: "equation",
            title: "第 1 步",
            prompt: "先写出令 y=0 后得到的方程",
            hint: "把函数值设为 0。",
            acceptableAnswers: ["x^2-2x-3=0"],
            placeholder: "填写方程",
          },
          {
            id: "factorization",
            title: "第 2 步",
            prompt: "再写出因式分解后的结果",
            hint: "把二次三项式分解成两个一次因式。",
            acceptableAnswers: ["(x-3)(x+1)=0", "(x+1)(x-3)=0"],
            placeholder: "填写因式分解结果",
          },
          {
            id: "roots",
            title: "第 3 步",
            prompt: "最后写出两个交点的横坐标",
            hint: "分别令两个因式为 0。",
            acceptableAnswers: ["x=-1或x=3", "x=3或x=-1", "-1,3", "3,-1"],
            placeholder: "填写横坐标",
          },
        ],
        explanation: "与 x 轴交点满足 y=0，先解方程，再从两个根读出横坐标。",
        relatedLessonIds: ["lesson-function-representation"],
        relatedExampleIds: ["example-quadratic-vertex"],
      },
    ],
  },
};
