import type { CurriculumSlice } from "@/types/content";
import { createEquationBalanceFigure } from "./quiz-figures";

// Assumption: V1 mock content is authored as one nested slice per chapter so
// non-technical editors can update the curriculum in a single file.
export const g7ShangUnit3Slice: CurriculumSlice = {
  grade: {
    id: "g7",
    label: "七年级",
    shortLabel: "七上",
    description: "从数的认识出发，建立初中阶段数学学习的基础。",
  },
  volume: {
    id: "shang",
    gradeId: "g7",
    label: "上册",
    description: "以有理数、整式、几何初步为主线的入门学习。",
  },
  chapter: {
    id: "unit-3",
    gradeId: "g7",
    volumeId: "shang",
    slug: "yi-yuan-yi-ci-fang-cheng",
    title: "第三章 一元一次方程",
    summary:
      "理解方程与方程的解，会用移项、合并同类项等方法解简单的一元一次方程。",
    order: 3,
    lessonIds: ["lesson-equation-and-solution", "lesson-solving-linear-equation"],
    workedExampleIds: ["example-stationery-cost", "example-classroom-seats"],
    quizId: "quiz-unit-3",
    coverImage: {
      src: "/images/content/g7-shang-unit-3-cover.svg",
      alt: "第三章一元一次方程封面示意图",
    },
  },
  lessons: [
    {
      id: "lesson-equation-and-solution",
      chapterId: "unit-3",
      slug: "fang-cheng-yu-fang-cheng-de-jie",
      title: "方程与方程的解",
      summary: "从实际问题中抽象出方程，理解未知数、等式和方程的解。",
      learningObjectives: [
        "能判断一个式子是不是方程，知道方程必须含有未知数。",
        "会根据题意设未知数，并列出简单的一元一次方程。",
        "能通过代入检验一个数是不是方程的解。",
      ],
      keyRules: [
        "含有未知数的等式叫做方程。",
        "只含有一个未知数，并且未知数的次数是 1 的方程，叫做一元一次方程。",
        "使方程左右两边相等的未知数的值，叫做方程的解。",
      ],
      bodyBlocks: [
        {
          type: "richText",
          id: "concept-context",
          title: "从问题到方程",
          content: [
            "列方程时，先找出题目中的等量关系，再用字母表示未知量。",
            "例如“一个数加 5 等于 12”，设这个数为 x，就可以列出方程 x + 5 = 12。",
          ],
        },
        {
          type: "formula",
          id: "equation-examples",
          title: "典型表示",
          formulas: ["x + 5 = 12", "3x = 18", "2x - 7 = 9", "x + y = 10 不是一元一次方程"],
          note: "判断时要同时看“未知数个数”和“次数”。",
        },
        {
          type: "tip",
          id: "check-tip",
          title: "易错提醒",
          content: "检验方程的解时，要把数代入原方程左右两边分别计算，不能只看一边。",
        },
      ],
      relatedExampleIds: ["example-stationery-cost"],
      order: 1,
      videoPlaceholder: {
        title: "板书微课：什么是方程",
        durationLabel: "4 分钟",
        description: "从文字题到含未知数等式，梳理方程和方程解的概念。",
      },
    },
    {
      id: "lesson-solving-linear-equation",
      chapterId: "unit-3",
      slug: "jie-yi-yuan-yi-ci-fang-cheng",
      title: "解一元一次方程",
      summary: "掌握移项、合并同类项和系数化为 1 的基本解法。",
      learningObjectives: [
        "会用等式性质把方程逐步化简。",
        "能按“去括号、移项、合并同类项、系数化为 1”的顺序解题。",
        "能对解出的结果进行检验，提高计算正确率。",
      ],
      keyRules: [
        "方程两边同时加上或减去同一个数，等式仍然成立。",
        "方程两边同时乘同一个不为 0 的数或除以同一个不为 0 的数，等式仍然成立。",
        "移项要变号，合并同类项后再把未知数的系数化为 1。",
      ],
      bodyBlocks: [
        {
          type: "richText",
          id: "solve-idea",
          title: "解方程的目标",
          content: [
            "解一元一次方程的核心目标，是把方程变形成 x = a 这样的形式。",
            "每一步都要有依据，既要会算，也要注意符号变化是否正确。",
          ],
        },
        {
          type: "formula",
          id: "solve-pattern",
          title: "常见步骤",
          formulas: ["2x + 3 = 11", "2x = 8", "x = 4", "检验：2×4+3=11"],
          note: "解完后代回原方程检验，能帮助发现漏号、算错等问题。",
        },
        {
          type: "tip",
          id: "transpose-tip",
          title: "易错提醒",
          content: "移项时不要只移动位置不变符号；例如把 +3 移到右边后应变成 -3。",
        },
      ],
      relatedExampleIds: ["example-stationery-cost", "example-classroom-seats"],
      order: 2,
      videoPlaceholder: {
        title: "板书微课：一元一次方程的解法",
        durationLabel: "5 分钟",
        description: "结合板演示例讲清移项、合并同类项和检验过程。",
      },
    },
  ],
  workedExamples: [
    {
      id: "example-stationery-cost",
      chapterId: "unit-3",
      slug: "wen-ju-fei-yong",
      title: "例题 1：文具费用",
      summary: "根据总价与单价的关系列出一元一次方程并求解。",
      problem: "一本练习本 3 元，小明买了若干本后又买了一支 5 元的笔，一共花了 20 元。小明买了多少本练习本？",
      steps: [
        {
          id: "step-1",
          title: "设未知数",
          content: "设小明买了 x 本练习本，那么练习本一共花了 3x 元。",
        },
        {
          id: "step-2",
          title: "找等量关系列方程",
          content: "练习本费用 + 笔的费用 = 总费用，所以列方程 3x + 5 = 20。",
        },
        {
          id: "step-3",
          title: "解方程并检验",
          content: "移项得 3x = 15，再两边同时除以 3，得 x = 5。检验：3×5+5=20，正确。",
        },
      ],
      answer: "5 本",
      commonMistakes: [
        "把 3x + 5 = 20 错列成 3 + 5x = 20。",
        "求出 x = 5 后没有代入检验，容易忽略前面计算错误。",
      ],
      relatedLessonIds: ["lesson-equation-and-solution", "lesson-solving-linear-equation"],
      order: 1,
    },
    {
      id: "example-classroom-seats",
      chapterId: "unit-3",
      slug: "jiao-shi-zuo-wei",
      title: "例题 2：教室座位调整",
      summary: "通过移项和合并同类项解含未知数在两边的方程。",
      problem: "某班调整座位后，左边有 2x + 4 个座位，右边有 x + 16 个座位。已知左右两边座位数相同，求 x 的值。",
      steps: [
        {
          id: "step-1",
          title: "列出方程",
          content: "因为左右两边座位数相同，所以有 2x + 4 = x + 16。",
        },
        {
          id: "step-2",
          title: "移项化简",
          content: "把右边的 x 移到左边，把左边的 4 移到右边，得 2x - x = 16 - 4。",
        },
        {
          id: "step-3",
          title: "求解并写答",
          content: "化简得 x = 12。所以 x 的值是 12。",
        },
      ],
      answer: "12",
      commonMistakes: [
        "移项后忘记变号，写成 2x - x = 16 + 4。",
        "化简时把 2x - x 错算成 2。",
      ],
      relatedLessonIds: ["lesson-solving-linear-equation"],
      order: 2,
    },
  ],
  quiz: {
    id: "quiz-unit-3",
    chapterId: "unit-3",
    title: "第三章单元小测",
    instructions:
      "共 10 题，基础 2 题、进阶 4 题、压轴 4 题，整体难度明显上调，更强调多步推理、信息提取与综合应用。",
    passingScore: 80,
    questions: [
      {
        id: "q1",
        quizId: "quiz-unit-3",
        type: "single-choice",
        difficulty: "basic",
        stem: "下列式子中，哪个是一元一次方程？",
        options: [
          { id: "a", label: "A", content: "2x + 3" },
          { id: "b", label: "B", content: "x + y = 7" },
          { id: "c", label: "C", content: "3x - 2 = 10" },
          { id: "d", label: "D", content: "x² = 9" },
        ],
        correctOptionId: "c",
        explanation: "一元一次方程必须是含有一个未知数且未知数次数为 1 的等式，只有 3x - 2 = 10 符合条件。",
        relatedLessonIds: ["lesson-equation-and-solution"],
        relatedExampleIds: ["example-stationery-cost"],
      },
      {
        id: "q2",
        quizId: "quiz-unit-3",
        type: "single-choice",
        difficulty: "basic",
        stem: "方程 x + 6 = 15 的解是哪个？",
        options: [
          { id: "a", label: "A", content: "x = 9" },
          { id: "b", label: "B", content: "x = 21" },
          { id: "c", label: "C", content: "x = -9" },
          { id: "d", label: "D", content: "x = 6" },
        ],
        correctOptionId: "a",
        explanation: "方程两边同时减去 6，得 x = 15 - 6 = 9。",
        relatedLessonIds: ["lesson-solving-linear-equation"],
        relatedExampleIds: ["example-stationery-cost"],
      },
      {
        id: "q3",
        quizId: "quiz-unit-3",
        type: "fill-blank",
        difficulty: "advanced",
        stem: "观察天平图，方程表示为 2x + 3 = 11。先写出两边同时减 3 后的方程，再填写 x 的值。",
        figure: createEquationBalanceFigure(
          "方程 2x + 3 = 11 的天平图。",
          "2x + 3",
          "11",
        ),
        blanks: [
          {
            id: "next-step",
            prompt: "减 3 后得到的方程",
            hint: "把方程左右两边同时减去 3，按“2x=...”格式填写。",
            acceptableAnswers: ["2x=8"],
            placeholder: "请填写方程",
          },
          {
            id: "value",
            prompt: "依据相关关系，x 的值",
            hint: "先判断所用关系或方法，再根据 2x = 8 再把两边同时除以 2，填写 x 的数值。",
            acceptableAnswers: ["4"],
            placeholder: "请填写数值",
          },
        ],
        explanation: "依据题目中的条件和相关性质，方程两边同时减去 3，得到 2x = 8；再把方程两边同时除以 2，得到 x = 4。",
        relatedLessonIds: ["lesson-solving-linear-equation"],
        relatedExampleIds: ["example-stationery-cost"],
      },
      {
        id: "q4",
        quizId: "quiz-unit-3",
        type: "single-choice",
        difficulty: "advanced",
        stem: "解方程 2x - 5 = 11，结果正确的是哪个？",
        options: [
          { id: "a", label: "A", content: "x = 3" },
          { id: "b", label: "B", content: "x = 8" },
          { id: "c", label: "C", content: "x = 16" },
          { id: "d", label: "D", content: "x = -3" },
        ],
        correctOptionId: "b",
        explanation: "先移项得 2x = 16，再把两边同时除以 2，得 x = 8。",
        relatedLessonIds: ["lesson-solving-linear-equation"],
        relatedExampleIds: ["example-stationery-cost", "example-classroom-seats"],
      },
      {
        id: "q5",
        quizId: "quiz-unit-3",
        type: "single-choice",
        difficulty: "advanced",
        stem: "解方程 3x + 4 = 19，结果正确的是哪个？",
        options: [
          { id: "a", label: "A", content: "3" },
          { id: "b", label: "B", content: "5" },
          { id: "c", label: "C", content: "7" },
          { id: "d", label: "D", content: "15" },
        ],
        correctOptionId: "b",
        explanation: "先移项得 3x = 15，再把两边同时除以 3，得 x = 5。",
        relatedLessonIds: ["lesson-solving-linear-equation"],
        relatedExampleIds: ["example-stationery-cost"],
      },
      {
        id: "q6",
        quizId: "quiz-unit-3",
        type: "single-choice",
        difficulty: "advanced",
        stem: "若 4x - 3 = 2x + 9，则 x 的值是哪个？",
        options: [
          { id: "a", label: "A", content: "4" },
          { id: "b", label: "B", content: "5" },
          { id: "c", label: "C", content: "6" },
          { id: "d", label: "D", content: "7" },
        ],
        correctOptionId: "c",
        explanation: "移项得 4x - 2x = 9 + 3，所以 2x = 12，解得 x = 6。",
        relatedLessonIds: ["lesson-solving-linear-equation"],
        relatedExampleIds: ["example-classroom-seats"],
      },
      {
        id: "q7",
        quizId: "quiz-unit-3",
        type: "single-choice",
        difficulty: "challenge",
        stem: "若 3x + 2 = 2x + 7，则 x 的值是哪个？",
        options: [
          { id: "a", label: "A", content: "3" },
          { id: "b", label: "B", content: "5" },
          { id: "c", label: "C", content: "7" },
          { id: "d", label: "D", content: "9" },
        ],
        correctOptionId: "b",
        explanation: "移项得 3x - 2x = 7 - 2，所以 x = 5。",
        relatedLessonIds: ["lesson-solving-linear-equation"],
        relatedExampleIds: ["example-classroom-seats"],
      },
      {
        id: "q8",
        quizId: "quiz-unit-3",
        type: "single-choice",
        difficulty: "challenge",
        stem: "解方程 2(x - 1) = 3x + 5，结果正确的是哪个？",
        options: [
          { id: "a", label: "A", content: "x = -7" },
          { id: "b", label: "B", content: "x = 7" },
          { id: "c", label: "C", content: "x = -3" },
          { id: "d", label: "D", content: "x = 3" },
        ],
        correctOptionId: "a",
        explanation: "去括号得 2x - 2 = 3x + 5，移项得 -x = 7，所以 x = -7。",
        relatedLessonIds: ["lesson-solving-linear-equation"],
        relatedExampleIds: ["example-classroom-seats"],
      },
      {
        id: "q9",
        quizId: "quiz-unit-3",
        type: "fill-blank",
        difficulty: "challenge",
        stem: "观察图中的天平关系，先写出去括号后的方程，再填写最后求得的 x。",
        figure: createEquationBalanceFigure(
          "方程 5(x - 1) = 3(x + 5) 的天平图。",
          "5(x - 1)",
          "3(x + 5)",
        ),
        blanks: [
          {
            id: "expanded",
            prompt: "去括号后的方程",
            hint: "分别把左边和右边乘开，按“ax+b=cx+d”格式填写。",
            acceptableAnswers: ["5x-5=3x+15"],
            placeholder: "请填写方程",
          },
          {
            id: "value",
            prompt: "x 的值",
            hint: "把同类项移到同一边后求解，只填写最后的数值。",
            acceptableAnswers: ["10"],
            placeholder: "请填写整数",
          },
        ],
        explanation: "展开并移项得 5x - 5 = 3x + 15，再化简为 2x = 20，所以 x = 10。",
        relatedLessonIds: ["lesson-solving-linear-equation"],
        relatedExampleIds: ["example-classroom-seats"],
      },
      {
        id: "q10",
        quizId: "quiz-unit-3",
        type: "single-choice",
        difficulty: "challenge",
        stem: "某文具店铅笔每支 2 元，钢笔每支 8 元，小明共买了 7 支文具，一共花了 32 元。若设买了 x 支钢笔，则正确方程是哪个？",
        options: [
          { id: "a", label: "A", content: "8x + 2(7 - x) = 32" },
          { id: "b", label: "B", content: "8x + 2x = 32" },
          { id: "c", label: "C", content: "2x + 8(7 - x) = 32" },
          { id: "d", label: "D", content: "8 + 2(7 - x) = 32" },
        ],
        correctOptionId: "a",
        explanation: "钢笔有 x 支，铅笔有 7 - x 支，总价应为 8x + 2(7 - x) = 32。",
        relatedLessonIds: ["lesson-equation-and-solution", "lesson-solving-linear-equation"],
        relatedExampleIds: ["example-stationery-cost", "example-classroom-seats"],
      },
    ],
  },
};
