import type { CurriculumSlice } from "@/types/content";
import { createNumberLineFigure } from "./quiz-figures";

// Assumption: V1 mock content is authored as one nested slice per chapter so
// non-technical editors can update the curriculum in a single file.
export const g7ShangUnit1Slice: CurriculumSlice = {
  grade: {
    id: "g7",
    label: "七年级",
    shortLabel: "七上",
    description: "从数的认识出发，建立初中阶段数学学习的基础。",
  },
  volume: {
    id: "shang",
    gradeId: "g7",
    label: "上册",
    description: "以有理数、整式、几何初步为主线的入门学习。",
  },
  chapter: {
    id: "unit-1",
    gradeId: "g7",
    volumeId: "shang",
    slug: "you-li-shu",
    title: "第一章 有理数",
    summary:
      "认识正数、负数与有理数，会比较大小，并能完成简单的有理数加法运算。",
    order: 1,
    lessonIds: ["lesson-positive-negative", "lesson-rational-addition"],
    workedExampleIds: ["example-temperature-change", "example-mixed-addition"],
    quizId: "quiz-unit-1",
    coverImage: {
      src: "/images/content/g7-shang-unit-1-cover.svg",
      alt: "第一章有理数封面示意图",
    },
  },
  lessons: [
    {
      id: "lesson-positive-negative",
      chapterId: "unit-1",
      slug: "zheng-shu-yu-fu-shu",
      title: "正数与负数",
      summary: "从生活情境理解相反意义的量，学会用正数和负数表示。",
      learningObjectives: [
        "能说出正数、负数和 0 在实际情境中的含义。",
        "能根据题意选择合适的正负号表示数量。",
        "知道 0 既不是正数也不是负数。",
      ],
      keyRules: [
        "像 3、2.5 这样大于 0 的数是正数。",
        "像 -3、-2.5 这样小于 0 的数是负数。",
        "0 是正数和负数的分界点。",
      ],
      bodyBlocks: [
        {
          type: "richText",
          id: "context",
          title: "生活中的正负数",
          content: [
            "在温度、海拔、收支等场景中，经常会遇到意义相反的量。为了区分这些量，我们在原来的数前面添上“+”或“-”。",
            "例如，高于海平面 8848 米记作 +8848 米，低于海平面 155 米记作 -155 米。",
          ],
        },
        {
          type: "formula",
          id: "notation",
          title: "表示规则",
          formulas: ["收入 +200 元", "支出 -80 元", "零上 5℃ 记作 +5℃", "零下 3℃ 记作 -3℃"],
          note: "正号通常可以省略，但负号不能省略。",
        },
        {
          type: "tip",
          id: "zero-tip",
          title: "易错提醒",
          content: "0 不是正数，也不是负数；它表示分界位置或没有变化。",
        },
      ],
      relatedExampleIds: ["example-temperature-change"],
      order: 1,
      videoPlaceholder: {
        title: "板书微课：正负数的引入",
        durationLabel: "3 分钟",
        description: "用温度计和电梯楼层示意图帮助理解相反意义的量。",
      },
    },
    {
      id: "lesson-rational-addition",
      chapterId: "unit-1",
      slug: "you-li-shu-de-jia-fa",
      title: "有理数的加法",
      summary: "掌握同号、异号及一个数与 0 相加的运算方法。",
      learningObjectives: [
        "会根据符号情况选择合适的有理数加法法则。",
        "能把实际问题中的变化量转化为加法算式。",
        "知道加法交换律在有理数范围内仍然成立。",
      ],
      keyRules: [
        "同号两数相加，取相同的符号，并把绝对值相加。",
        "异号两数相加，取绝对值较大的加数的符号，并用较大绝对值减较小绝对值。",
        "一个数同 0 相加，仍得这个数。",
      ],
      bodyBlocks: [
        {
          type: "richText",
          id: "rule-explain",
          title: "为什么要看符号",
          content: [
            "有理数加法不仅要关注数的大小，还要判断两个加数表示的方向是否一致。",
            "若方向一致，就把变化合并；若方向相反，就比较两种变化谁更大。",
          ],
        },
        {
          type: "formula",
          id: "examples",
          title: "典型算式",
          formulas: ["(+4) + (+3) = +7", "(-6) + (-2) = -8", "(-5) + (+3) = -2", "(+7) + (-7) = 0"],
        },
        {
          type: "tip",
          id: "abs-tip",
          title: "易错提醒",
          content: "异号相加时，先比较绝对值，再确定结果符号，不要直接把符号抄在前面。",
        },
      ],
      relatedExampleIds: ["example-temperature-change", "example-mixed-addition"],
      order: 2,
      videoPlaceholder: {
        title: "板书微课：有理数加法法则",
        durationLabel: "4 分钟",
        description: "用数轴动画演示同号与异号相加的结果变化。",
      },
    },
  ],
  workedExamples: [
    {
      id: "example-temperature-change",
      chapterId: "unit-1",
      slug: "wen-du-bian-hua",
      title: "例题 1：温度变化",
      summary: "把生活中的升温和降温转化为有理数加法。",
      problem: "某地中午气温是 -2℃，傍晚又下降了 3℃。傍晚气温是多少？",
      steps: [
        {
          id: "step-1",
          title: "找出已知量",
          content: "中午气温是 -2℃，下降 3℃ 表示再加上 -3℃。",
        },
        {
          id: "step-2",
          title: "列式计算",
          content: "(-2) + (-3) = -(2 + 3) = -5。",
        },
        {
          id: "step-3",
          title: "写出答案",
          content: "所以傍晚气温是 -5℃。",
        },
      ],
      answer: "-5℃",
      commonMistakes: [
        "把“下降 3℃”错写成 +3。",
        "同号相加时漏写负号。",
      ],
      relatedLessonIds: ["lesson-positive-negative", "lesson-rational-addition"],
      order: 1,
    },
    {
      id: "example-mixed-addition",
      chapterId: "unit-1",
      slug: "hun-he-jia-fa",
      title: "例题 2：异号相加",
      summary: "通过比较绝对值完成异号两数相加。",
      problem: "计算：(-12) + 7。",
      steps: [
        {
          id: "step-1",
          title: "判断类型",
          content: "两个加数符号不同，属于异号两数相加。",
        },
        {
          id: "step-2",
          title: "比较绝对值",
          content: "|-12| = 12，|7| = 7，12 比 7 大，所以结果取 -12 的符号。",
        },
        {
          id: "step-3",
          title: "求结果",
          content: "12 - 7 = 5，所以 (-12) + 7 = -5。",
        },
      ],
      answer: "-5",
      commonMistakes: [
        "异号相加直接把 12 和 7 相加得到 19。",
        "只做减法 12 - 7 = 5，却忘记判断结果符号。",
      ],
      relatedLessonIds: ["lesson-rational-addition"],
      order: 2,
    },
  ],
  quiz: {
    id: "quiz-unit-1",
    chapterId: "unit-1",
    title: "第一章单元小测",
    instructions:
      "共 10 题，基础 2 题、进阶 4 题、压轴 4 题，整体难度明显上调，更强调多步推理、信息提取与综合应用。",
    passingScore: 80,
    questions: [
      {
        id: "q1",
        quizId: "quiz-unit-1",
        type: "single-choice",
        difficulty: "basic",
        stem: "下列各数中，表示“低于海平面 20 米”的是哪个？",
        options: [
          { id: "a", label: "A", content: "20" },
          { id: "b", label: "B", content: "-20" },
          { id: "c", label: "C", content: "+20" },
          { id: "d", label: "D", content: "0" },
        ],
        correctOptionId: "b",
        explanation: "低于海平面表示在基准面以下，应使用负数表示，所以记作 -20 米。",
        relatedLessonIds: ["lesson-positive-negative"],
        relatedExampleIds: ["example-temperature-change"],
      },
      {
        id: "q2",
        quizId: "quiz-unit-1",
        type: "single-choice",
        difficulty: "basic",
        stem: "计算：(-4) + (-6) 的结果是哪个？",
        options: [
          { id: "a", label: "A", content: "-10" },
          { id: "b", label: "B", content: "10" },
          { id: "c", label: "C", content: "-2" },
          { id: "d", label: "D", content: "2" },
        ],
        correctOptionId: "a",
        explanation: "同号负数相加，结果仍是负数，绝对值相加得到 4 + 6 = 10，所以结果是 -10。",
        relatedLessonIds: ["lesson-rational-addition"],
        relatedExampleIds: ["example-temperature-change"],
      },
      {
        id: "q3",
        quizId: "quiz-unit-1",
        type: "fill-blank",
        difficulty: "advanced",
        stem: "观察图中的数轴，完成两个填空：先写出点 P 表示的数，再写出点 P 到数 2 的距离。",
        figure: createNumberLineFigure(
          "数轴上标出点 P，对应位置需要填写具体数值。",
          "-8",
          "-3",
          "2",
          "P",
        ),
        blanks: [
          {
            id: "value",
            prompt: "点 P 表示的数",
            hint: "观察蓝点所在刻度，直接填写对应整数，不带单位。",
            acceptableAnswers: ["-3"],
            placeholder: "请填写整数",
          },
          {
            id: "distance",
            prompt: "依据相关关系，点 P 到数 2 的距离",
            hint: "先判断所用关系或方法，再先读出点 P 表示的数，再计算它与 2 之间相差几个单位，只填正数。",
            acceptableAnswers: ["5"],
            placeholder: "请填写正数",
          },
        ],
        explanation: "依据题目中的条件和相关性质，蓝点 P 对应 -3，数 2 在它的右侧，两者相差 2 - (-3) = 5，所以点 P 到数 2 的距离是 5。",
        relatedLessonIds: ["lesson-positive-negative"],
        relatedExampleIds: ["example-temperature-change"],
      },
      {
        id: "q4",
        quizId: "quiz-unit-1",
        type: "single-choice",
        difficulty: "advanced",
        stem: "计算：7 + (-9) 的结果是哪个？",
        options: [
          { id: "a", label: "A", content: "16" },
          { id: "b", label: "B", content: "-16" },
          { id: "c", label: "C", content: "-2" },
          { id: "d", label: "D", content: "2" },
        ],
        correctOptionId: "c",
        explanation: "这是异号相加，比较绝对值后 9 更大，所以结果取负号，再算 9 - 7 = 2，得 -2。",
        relatedLessonIds: ["lesson-rational-addition"],
        relatedExampleIds: ["example-mixed-addition"],
      },
      {
        id: "q5",
        quizId: "quiz-unit-1",
        type: "single-choice",
        difficulty: "advanced",
        stem: "计算：(-8) + 3 + (-2) 的结果是哪个？",
        options: [
          { id: "a", label: "A", content: "-13" },
          { id: "b", label: "B", content: "-7" },
          { id: "c", label: "C", content: "7" },
          { id: "d", label: "D", content: "-3" },
        ],
        correctOptionId: "b",
        explanation: "先算 (-8) + 3 = -5，再算 -5 + (-2) = -7。",
        relatedLessonIds: ["lesson-rational-addition"],
        relatedExampleIds: ["example-mixed-addition"],
      },
      {
        id: "q6",
        quizId: "quiz-unit-1",
        type: "single-choice",
        difficulty: "advanced",
        stem: "某天早晨气温是 -4℃，中午上升 7℃，则中午气温是多少？",
        options: [
          { id: "a", label: "A", content: "3℃" },
          { id: "b", label: "B", content: "-3℃" },
          { id: "c", label: "C", content: "11℃" },
          { id: "d", label: "D", content: "-11℃" },
        ],
        correctOptionId: "a",
        explanation: "上升 7℃ 表示加 7，所以 -4 + 7 = 3℃。",
        relatedLessonIds: ["lesson-positive-negative", "lesson-rational-addition"],
        relatedExampleIds: ["example-temperature-change"],
      },
      {
        id: "q7",
        quizId: "quiz-unit-1",
        type: "single-choice",
        difficulty: "challenge",
        stem: "如果某次数学测验成绩记作 +5 分，最合理的含义是哪个？",
        options: [
          { id: "a", label: "A", content: "比及格线低 5 分" },
          { id: "b", label: "B", content: "比参考标准高 5 分" },
          { id: "c", label: "C", content: "没有变化" },
          { id: "d", label: "D", content: "扣了 5 分" },
        ],
        correctOptionId: "b",
        explanation: "正数通常表示高于基准、增加或盈利，因此 +5 分表示比参考标准高 5 分。",
        relatedLessonIds: ["lesson-positive-negative"],
        relatedExampleIds: ["example-temperature-change"],
      },
      {
        id: "q8",
        quizId: "quiz-unit-1",
        type: "single-choice",
        difficulty: "challenge",
        stem: "计算：(-12) + 7 + (-5) 的结果是哪个？",
        options: [
          { id: "a", label: "A", content: "-10" },
          { id: "b", label: "B", content: "10" },
          { id: "c", label: "C", content: "-24" },
          { id: "d", label: "D", content: "0" },
        ],
        correctOptionId: "a",
        explanation: "先算 (-12) + 7 = -5，再算 -5 + (-5) = -10。",
        relatedLessonIds: ["lesson-rational-addition"],
        relatedExampleIds: ["example-mixed-addition"],
      },
      {
        id: "q9",
        quizId: "quiz-unit-1",
        type: "single-choice",
        difficulty: "challenge",
        stem: "潜水艇从海平面先下潜 18 米，再上升 9 米，接着又下潜 12 米，此时它相对海平面的高度是多少？",
        options: [
          { id: "a", label: "A", content: "-21 米" },
          { id: "b", label: "B", content: "21 米" },
          { id: "c", label: "C", content: "-39 米" },
          { id: "d", label: "D", content: "3 米" },
        ],
        correctOptionId: "a",
        explanation: "列式为 -18 + 9 + (-12) = -21，所以它在海平面下 21 米。",
        relatedLessonIds: ["lesson-positive-negative", "lesson-rational-addition"],
        relatedExampleIds: ["example-temperature-change", "example-mixed-addition"],
      },
      {
        id: "q10",
        quizId: "quiz-unit-1",
        type: "fill-blank",
        difficulty: "challenge",
        stem: "图中蓝点 A 表示凌晨气温为 -6℃。上午升高 4℃，傍晚又下降 7℃。请填写总变化量和傍晚气温。",
        figure: createNumberLineFigure(
          "数轴上蓝点 A 表示凌晨气温所在位置。",
          "-10",
          "-6",
          "-2",
          "A",
        ),
        blanks: [
          {
            id: "change",
            prompt: "与凌晨相比的总变化量",
            hint: "先把“上升”记为加、“下降”记为减，结果可写数字或带 ℃。",
            acceptableAnswers: ["-3℃", "-3", "下降3℃", "下降3"],
            placeholder: "请填写变化量",
          },
          {
            id: "evening",
            prompt: "傍晚气温",
            hint: "把总变化量叠加到凌晨的 -6℃ 上，填写最终气温。",
            acceptableAnswers: ["-9℃", "-9"],
            placeholder: "请填写气温",
          },
        ],
        explanation: "总变化量只看变化本身：+4 + (-7) = -3；把变化量叠加到凌晨气温 -6℃ 上，得到傍晚气温是 -9℃。",
        relatedLessonIds: ["lesson-positive-negative", "lesson-rational-addition"],
        relatedExampleIds: ["example-temperature-change", "example-mixed-addition"],
      },
    ],
  },
};
