import type { CurriculumSlice } from "@/types/content";
import { createExpressionFigure } from "./quiz-figures";

// Assumption: V1 mock content is authored as one nested slice per chapter so
// non-technical editors can update the curriculum in a single file.
export const g7ShangUnit2Slice: CurriculumSlice = {
  grade: {
    id: "g7",
    label: "七年级",
    shortLabel: "七上",
    description: "从数的认识出发，建立初中阶段数学学习的基础。",
  },
  volume: {
    id: "shang",
    gradeId: "g7",
    label: "上册",
    description: "以有理数、整式、几何初步为主线的入门学习。",
  },
  chapter: {
    id: "unit-2",
    gradeId: "g7",
    volumeId: "shang",
    slug: "zheng-shi-de-jia-jian",
    title: "第二章 整式的加减",
    summary:
      "理解单项式、多项式与同类项，会进行合并同类项和去括号的整式加减运算。",
    order: 2,
    lessonIds: ["lesson-like-terms", "lesson-polynomial-add-subtract"],
    workedExampleIds: ["example-combine-like-terms", "example-remove-parentheses"],
    quizId: "quiz-unit-2",
    coverImage: {
      src: "/images/content/g7-shang-unit-2-cover.svg",
      alt: "第二章整式的加减封面示意图",
    },
  },
  lessons: [
    {
      id: "lesson-like-terms",
      chapterId: "unit-2",
      slug: "tong-lei-xiang-yu-he-bing",
      title: "同类项与合并同类项",
      summary: "认识同类项的特征，学会把多项式中能合并的项整理到一起。",
      learningObjectives: [
        "能判断两个或多个式子是否是同类项。",
        "知道合并同类项时只合并系数，字母及其指数不变。",
        "能用合并同类项把多项式化简。",
      ],
      keyRules: [
        "所含字母相同，并且相同字母的指数也分别相同的项，叫做同类项。",
        "合并同类项时，把各同类项的系数相加，字母和字母的指数保持不变。",
        "不是同类项的式子不能合并。",
      ],
      bodyBlocks: [
        {
          type: "richText",
          id: "recognize-like-terms",
          title: "先看“字母部分”是否完全一样",
          content: [
            "判断同类项时，关键不在系数，而在字母部分是否完全一致。例如 3a 和 -5a 是同类项，2x²y 和 -7x²y 也是同类项。",
            "像 4ab 与 4a、x² 与 x³，虽然有相同字母，但指数或字母种类不同，因此都不是同类项。",
          ],
        },
        {
          type: "formula",
          id: "combine-rule",
          title: "合并示例",
          formulas: ["3x + 5x = 8x", "7a²b - 2a²b = 5a²b", "4m + 2n 不能合并"],
          note: "合并时只处理系数，字母部分原样保留。",
        },
        {
          type: "tip",
          id: "like-terms-tip",
          title: "易错提醒",
          content: "把字母相同但指数不同的项误认为同类项，是这一课最常见的失分点。",
        },
      ],
      relatedExampleIds: ["example-combine-like-terms"],
      order: 1,
      videoPlaceholder: {
        title: "板书微课：怎样快速找同类项",
        durationLabel: "4 分钟",
        description: "通过圈画字母部分，示范同类项判断和合并步骤。",
      },
    },
    {
      id: "lesson-polynomial-add-subtract",
      chapterId: "unit-2",
      slug: "zheng-shi-jia-jian-yu-qu-kuo-hao",
      title: "整式的加减与去括号",
      summary: "掌握括号前符号的变化规律，能按顺序完成整式加减。",
      learningObjectives: [
        "会把减去一个多项式转化为加上这个多项式的相反数。",
        "能正确去括号，并注意括号前是减号时各项符号改变。",
        "能按“去括号、合并同类项”的顺序化简整式。",
      ],
      keyRules: [
        "括号前是“+”号，去括号后括号内各项符号不变。",
        "括号前是“-”号，去括号后括号内各项都要变号。",
        "整式加减的一般步骤是先去括号，再合并同类项。",
      ],
      bodyBlocks: [
        {
          type: "richText",
          id: "subtract-polynomial",
          title: "为什么减法常常先变成加法",
          content: [
            "整式减法容易出错，往往是因为没有把“减去一个整体”看清楚。列式后先注意括号前的符号，再决定去括号后的每一项如何变化。",
            "只要括号前是减号，括号里的每一项都要同时变号，不能只改第一项。",
          ],
        },
        {
          type: "formula",
          id: "remove-parentheses",
          title: "典型算式",
          formulas: [
            "a + (2a - 3) = a + 2a - 3",
            "x - (3x + 2) = x - 3x - 2",
            "(5m - n) - (2m + 3n) = 5m - n - 2m - 3n",
          ],
        },
        {
          type: "tip",
          id: "minus-parentheses-tip",
          title: "易错提醒",
          content: "括号前有减号时，去括号后每一项都要变号；漏变一项，后面全错。",
        },
      ],
      relatedExampleIds: ["example-combine-like-terms", "example-remove-parentheses"],
      order: 2,
      videoPlaceholder: {
        title: "板书微课：整式加减的标准步骤",
        durationLabel: "5 分钟",
        description: "用两道典型题演示先去括号、后合并同类项的完整过程。",
      },
    },
  ],
  workedExamples: [
    {
      id: "example-combine-like-terms",
      chapterId: "unit-2",
      slug: "he-bing-tong-lei-xiang",
      title: "例题 1：合并同类项",
      summary: "先找同类项，再只对系数进行运算。",
      problem: "化简：4x + 7 - 2x + 3。",
      steps: [
        {
          id: "step-1",
          title: "找出同类项",
          content: "4x 和 -2x 是同类项，7 和 3 也是同类项。",
        },
        {
          id: "step-2",
          title: "分别合并",
          content: "4x - 2x = 2x，7 + 3 = 10。",
        },
        {
          id: "step-3",
          title: "写出结果",
          content: "所以原式化简为 2x + 10。",
        },
      ],
      answer: "2x + 10",
      commonMistakes: [
        "把 4x 和 7 直接相加，忽略它们不是同类项。",
        "合并 4x 与 -2x 时把字母丢掉，只写成 2。",
      ],
      relatedLessonIds: ["lesson-like-terms", "lesson-polynomial-add-subtract"],
      order: 1,
    },
    {
      id: "example-remove-parentheses",
      chapterId: "unit-2",
      slug: "qu-kuo-hao-hua-jian",
      title: "例题 2：去括号化简",
      summary: "把减去多项式转化为去括号后再合并同类项。",
      problem: "化简：3a - (2a - 5) + 4。",
      steps: [
        {
          id: "step-1",
          title: "先去括号",
          content: "括号前是减号，所以括号内各项都变号：3a - 2a + 5 + 4。",
        },
        {
          id: "step-2",
          title: "合并同类项",
          content: "3a - 2a = a，5 + 4 = 9。",
        },
        {
          id: "step-3",
          title: "写出结果",
          content: "所以原式化简为 a + 9。",
        },
      ],
      answer: "a + 9",
      commonMistakes: [
        "去括号时只把 2a 变号，忘记把 -5 也变成 +5。",
        "没有先去括号，就直接把括号内外的项混在一起相加减。",
      ],
      relatedLessonIds: ["lesson-polynomial-add-subtract"],
      order: 2,
    },
  ],
  quiz: {
    id: "quiz-unit-2",
    chapterId: "unit-2",
    title: "第二章单元小测",
    instructions:
      "共 10 题，基础 2 题、进阶 4 题、压轴 4 题，整体难度明显上调，更强调多步推理、信息提取与综合应用。",
    passingScore: 80,
    questions: [
      {
        id: "q1",
        quizId: "quiz-unit-2",
        type: "single-choice",
        difficulty: "basic",
        stem: "下列各组式子中，哪一组是同类项？",
        options: [
          { id: "a", label: "A", content: "3x 与 3y" },
          { id: "b", label: "B", content: "2a²b 与 -5a²b" },
          { id: "c", label: "C", content: "m² 与 m³" },
          { id: "d", label: "D", content: "4ab 与 4a" },
        ],
        correctOptionId: "b",
        explanation: "同类项要求字母相同且相同字母的指数也分别相同，只有 2a²b 与 -5a²b 符合条件。",
        relatedLessonIds: ["lesson-like-terms"],
        relatedExampleIds: ["example-combine-like-terms"],
      },
      {
        id: "q2",
        quizId: "quiz-unit-2",
        type: "single-choice",
        difficulty: "basic",
        stem: "化简 5x - 3x + 2 的结果是哪个？",
        options: [
          { id: "a", label: "A", content: "2x + 2" },
          { id: "b", label: "B", content: "8x + 2" },
          { id: "c", label: "C", content: "2" },
          { id: "d", label: "D", content: "2x" },
        ],
        correctOptionId: "a",
        explanation: "5x 与 -3x 是同类项，合并后得 2x，再把常数项 2 保留下来，所以结果是 2x + 2。",
        relatedLessonIds: ["lesson-like-terms"],
        relatedExampleIds: ["example-combine-like-terms"],
      },
      {
        id: "q3",
        quizId: "quiz-unit-2",
        type: "fill-blank",
        difficulty: "advanced",
        stem: "观察图中的整式结构图，填写这个多项式的项数和所有字母项系数的和。",
        figure: createExpressionFigure(
          "整式 2a - b + 3 的结构图，三个色块分别表示三个项。",
          "2a - b + 3",
          "2a",
          "-b",
          "3",
        ),
        blanks: [
          {
            id: "term-count",
            prompt: "项数",
            hint: "按色块逐项数，注意符号不同也算不同项。",
            acceptableAnswers: ["3", "三"],
            placeholder: "请填写项数",
          },
          {
            id: "constant",
            prompt: "依据相关关系，字母项系数和",
            hint: "先判断所用关系或方法，再字母项是 2a 和 -b，它们的系数分别是 2 和 -1，把这两个系数相加。",
            acceptableAnswers: ["1"],
            placeholder: "请填写结果",
          },
        ],
        explanation: "依据题目中的条件和相关性质，图中三个色块分别表示 2a、-b、3，所以这个多项式共有 3 项；字母项 2a 和 -b 的系数分别是 2 和 -1，系数和为 1。",
        relatedLessonIds: ["lesson-like-terms"],
        relatedExampleIds: ["example-combine-like-terms"],
      },
      {
        id: "q4",
        quizId: "quiz-unit-2",
        type: "single-choice",
        difficulty: "advanced",
        stem: "去括号后，x - (2x + 3) 正确的是哪个？",
        options: [
          { id: "a", label: "A", content: "x - 2x + 3" },
          { id: "b", label: "B", content: "x + 2x + 3" },
          { id: "c", label: "C", content: "x - 2x - 3" },
          { id: "d", label: "D", content: "x + 2x - 3" },
        ],
        correctOptionId: "c",
        explanation: "括号前是减号，括号内每一项都要变号，所以应化为 x - 2x - 3。",
        relatedLessonIds: ["lesson-polynomial-add-subtract"],
        relatedExampleIds: ["example-remove-parentheses"],
      },
      {
        id: "q5",
        quizId: "quiz-unit-2",
        type: "single-choice",
        difficulty: "advanced",
        stem: "化简 2m + (3 - m) 的结果是哪个？",
        options: [
          { id: "a", label: "A", content: "m + 3" },
          { id: "b", label: "B", content: "3m - 3" },
          { id: "c", label: "C", content: "m - 3" },
          { id: "d", label: "D", content: "2m + 3 - m²" },
        ],
        correctOptionId: "a",
        explanation: "括号前是加号，去括号后符号不变，原式为 2m + 3 - m，再合并同类项得 m + 3。",
        relatedLessonIds: ["lesson-like-terms", "lesson-polynomial-add-subtract"],
        relatedExampleIds: ["example-combine-like-terms", "example-remove-parentheses"],
      },
      {
        id: "q6",
        quizId: "quiz-unit-2",
        type: "single-choice",
        difficulty: "advanced",
        stem: "化简 3a - 2(a - 4) 的结果是哪个？",
        options: [
          { id: "a", label: "A", content: "a + 8" },
          { id: "b", label: "B", content: "a - 8" },
          { id: "c", label: "C", content: "5a - 4" },
          { id: "d", label: "D", content: "a + 4" },
        ],
        correctOptionId: "a",
        explanation: "先去括号得 3a - 2a + 8，再合并同类项得 a + 8。",
        relatedLessonIds: ["lesson-polynomial-add-subtract"],
        relatedExampleIds: ["example-remove-parentheses"],
      },
      {
        id: "q7",
        quizId: "quiz-unit-2",
        type: "single-choice",
        difficulty: "challenge",
        stem: "化简 4x - (2x - 5) + 3 的结果是哪个？",
        options: [
          { id: "a", label: "A", content: "2x + 8" },
          { id: "b", label: "B", content: "2x - 2" },
          { id: "c", label: "C", content: "6x - 2" },
          { id: "d", label: "D", content: "2x + 2" },
        ],
        correctOptionId: "a",
        explanation: "去括号得 4x - 2x + 5 + 3，再合并同类项得 2x + 8。",
        relatedLessonIds: ["lesson-polynomial-add-subtract"],
        relatedExampleIds: ["example-remove-parentheses"],
      },
      {
        id: "q8",
        quizId: "quiz-unit-2",
        type: "single-choice",
        difficulty: "challenge",
        stem: "若 A = 2a - 3b，B = a + 4b，则 A - B 等于哪个？",
        options: [
          { id: "a", label: "A", content: "a - 7b" },
          { id: "b", label: "B", content: "3a + b" },
          { id: "c", label: "C", content: "a + b" },
          { id: "d", label: "D", content: "a - b" },
        ],
        correctOptionId: "a",
        explanation: "A - B = (2a - 3b) - (a + 4b) = 2a - 3b - a - 4b = a - 7b。",
        relatedLessonIds: ["lesson-like-terms", "lesson-polynomial-add-subtract"],
        relatedExampleIds: ["example-combine-like-terms", "example-remove-parentheses"],
      },
      {
        id: "q9",
        quizId: "quiz-unit-2",
        type: "fill-blank",
        difficulty: "challenge",
        stem: "观察图中的整式，先化简，再填写结果中 x 的系数和常数项。",
        figure: createExpressionFigure(
          "整式 2(3x - 1) - (x + 4) 的结构图。",
          "2(3x - 1) - (x + 4)",
          "3x - 1",
          "-",
          "x + 4",
        ),
        blanks: [
          {
            id: "x-coefficient",
            prompt: "x 的系数",
            hint: "先去括号，再把所有含 x 的项合并，只填系数。",
            acceptableAnswers: ["5"],
            placeholder: "请填写系数",
          },
          {
            id: "constant",
            prompt: "常数项",
            hint: "把不含 x 的数相加减，只填化简后的常数项。",
            acceptableAnswers: ["-6"],
            placeholder: "请填写常数项",
          },
        ],
        explanation: "先去括号得 6x - 2 - x - 4，再合并同类项得 5x - 6，所以 x 的系数是 5，常数项是 -6。",
        relatedLessonIds: ["lesson-polynomial-add-subtract"],
        relatedExampleIds: ["example-remove-parentheses"],
      },
      {
        id: "q10",
        quizId: "quiz-unit-2",
        type: "single-choice",
        difficulty: "challenge",
        stem: "若多项式 5x + kx - 7 合并同类项后为 9x - 7，则 k 的值是哪个？",
        options: [
          { id: "a", label: "A", content: "2" },
          { id: "b", label: "B", content: "3" },
          { id: "c", label: "C", content: "4" },
          { id: "d", label: "D", content: "5" },
        ],
        correctOptionId: "c",
        explanation: "5x 与 kx 合并后得到 9x，所以 5 + k = 9，解得 k = 4。",
        relatedLessonIds: ["lesson-like-terms"],
        relatedExampleIds: ["example-combine-like-terms"],
      },
    ],
  },
};
