import type { CurriculumSlice } from "@/types/content";
import { createAngleFigure } from "./quiz-figures";

// Assumption: V1 mock content is authored as one nested slice per chapter so
// non-technical editors can update the curriculum in a single file.
export const g7ShangUnit4Slice: CurriculumSlice = {
  grade: {
    id: "g7",
    label: "七年级",
    shortLabel: "七上",
    description: "从数的认识出发，建立初中阶段数学学习的基础。",
  },
  volume: {
    id: "shang",
    gradeId: "g7",
    label: "上册",
    description: "以有理数、整式、几何初步为主线的入门学习。",
  },
  chapter: {
    id: "unit-4",
    gradeId: "g7",
    volumeId: "shang",
    slug: "ji-he-tu-xing-chu-bu",
    title: "第四章 几何图形初步",
    summary:
      "认识常见立体图形与平面图形，掌握直线、射线、线段和角的基本概念与简单计算。",
    order: 4,
    lessonIds: ["lesson-solid-and-plane-figures", "lesson-lines-and-angles"],
    workedExampleIds: ["example-cube-observation", "example-angle-calculation"],
    quizId: "quiz-unit-4",
    coverImage: {
      src: "/images/content/g7-shang-unit-4-cover.svg",
      alt: "第四章几何图形初步封面示意图",
    },
  },
  lessons: [
    {
      id: "lesson-solid-and-plane-figures",
      chapterId: "unit-4",
      slug: "li-ti-tu-xing-yu-ping-mian-tu-xing",
      title: "立体图形与平面图形",
      summary: "会区分常见几何图形，知道从不同方向观察立体图形看到的平面形状。",
      learningObjectives: [
        "能识别正方体、长方体、圆柱、圆锥、球等常见立体图形。",
        "能说出长方形、正方形、三角形、圆等常见平面图形的名称。",
        "能根据简单情境判断从正面、左面、上面看到的图形。",
      ],
      keyRules: [
        "占有空间、能看出长宽高的图形是立体图形。",
        "只在一个平面内的图形是平面图形。",
        "观察立体图形时，不同方向看到的平面图形可能不同。",
      ],
      bodyBlocks: [
        {
          type: "richText",
          id: "figure-recognition",
          title: "从生活物体认识图形",
          content: [
            "粉笔盒、魔方常抽象成长方体或正方体，易拉罐可看作圆柱，球类可看作球。",
            "把立体图形的某个面单独看出来，常能得到长方形、正方形、圆等平面图形。",
          ],
        },
        {
          type: "formula",
          id: "common-figures",
          title: "常见对应",
          formulas: [
            "魔方 -> 正方体",
            "教室门 -> 长方形",
            "红领巾一角 -> 三角形",
            "硬币表面 -> 圆",
          ],
          note: "做题时先判断物体是否“占有空间”，再确定属于立体还是平面图形。",
        },
        {
          type: "tip",
          id: "observe-tip",
          title: "易错提醒",
          content: "不要把“物体”和“物体表面的形状”混为一谈，如篮球是球，篮球上的某个截面可能是圆。",
        },
      ],
      relatedExampleIds: ["example-cube-observation"],
      order: 1,
      videoPlaceholder: {
        title: "板书微课：立体图形和平面图形",
        durationLabel: "4 分钟",
        description: "用生活实物和三视图草图帮助区分不同类型的图形。",
      },
    },
    {
      id: "lesson-lines-and-angles",
      chapterId: "unit-4",
      slug: "zhi-xian-she-xian-xian-duan-yu-jiao",
      title: "直线、射线、线段与角",
      summary: "理解直线、射线、线段的区别，掌握角的表示方法和简单角度计算。",
      learningObjectives: [
        "能根据端点个数区分直线、射线和线段。",
        "会用字母正确表示线段、射线和角。",
        "能根据图形或条件进行简单的角度求值。",
      ],
      keyRules: [
        "直线没有端点，可以向两端无限延伸。",
        "射线有一个端点，线段有两个端点。",
        "平角等于 180°，周角等于 360°。",
      ],
      bodyBlocks: [
        {
          type: "richText",
          id: "line-angle-explain",
          title: "抓住端点和方向",
          content: [
            "判断直线、射线、线段时，最关键的是看端点个数以及是否向某个方向无限延伸。",
            "角是由两条有公共端点的射线组成的，公共端点叫角的顶点。",
          ],
        },
        {
          type: "formula",
          id: "angle-facts",
          title: "常用结论",
          formulas: [
            "线段 AB 可记作 AB",
            "射线 OA 端点是 O",
            "1 个平角 = 180°",
            "若 ∠1 与 ∠2 组成平角，则 ∠1 + ∠2 = 180°",
          ],
          note: "角的计算常用“和为 180°”或“和为 360°”来建立等式。",
        },
        {
          type: "tip",
          id: "angle-tip",
          title: "易错提醒",
          content: "表示射线时要把端点写在前面；计算角度后别漏写单位“°”。",
        },
      ],
      relatedExampleIds: ["example-angle-calculation"],
      order: 2,
      videoPlaceholder: {
        title: "板书微课：线与角的基础知识",
        durationLabel: "5 分钟",
        description: "通过图示梳理三种线和常见角度关系，帮助提升识图速度。",
      },
    },
  ],
  workedExamples: [
    {
      id: "example-cube-observation",
      chapterId: "unit-4",
      slug: "zheng-fang-ti-guan-cha",
      title: "例题 1：观察正方体",
      summary: "从立体图形中抽取平面图形，训练识图能力。",
      problem: "一个正方体纸盒放在桌面上，从正面看到的图形是什么？从上面看到的图形又是什么？",
      steps: [
        {
          id: "step-1",
          title: "明确图形特点",
          content: "正方体的每个面都是大小相同的正方形。",
        },
        {
          id: "step-2",
          title: "按方向观察",
          content: "从正面看，看到的是前面的一个面；从上面看，看到的是上面的一个面。",
        },
        {
          id: "step-3",
          title: "写出结论",
          content: "前面的面和上面的面都是正方形，所以两个方向看到的图形都是正方形。",
        },
      ],
      answer: "从正面看是正方形，从上面看也是正方形。",
      commonMistakes: [
        "把正方体看成只能从一个方向得到正方形。",
        "混淆“看到的面”与整个立体图形本身。",
      ],
      relatedLessonIds: ["lesson-solid-and-plane-figures"],
      order: 1,
    },
    {
      id: "example-angle-calculation",
      chapterId: "unit-4",
      slug: "ping-jiao-qiu-jiao",
      title: "例题 2：利用平角求角度",
      summary: "借助平角等于 180° 快速求出未知角。",
      problem: "如图，A、O、B 在同一直线上，射线 OC 把平角 AOB 分成两个角，且 ∠AOC = 68°。求 ∠COB 的度数。",
      steps: [
        {
          id: "step-1",
          title: "找出数量关系",
          content: "因为 A、O、B 在同一直线上，所以 ∠AOB 是平角，等于 180°。",
        },
        {
          id: "step-2",
          title: "列式计算",
          content: "∠AOC + ∠COB = 180°，所以 ∠COB = 180° - 68° = 112°。",
        },
        {
          id: "step-3",
          title: "写出答案",
          content: "所以 ∠COB = 112°。",
        },
      ],
      answer: "112°",
      commonMistakes: [
        "忘记平角等于 180°，误用 90° 去计算。",
        "算出 112 后漏写角度单位。",
      ],
      relatedLessonIds: ["lesson-lines-and-angles"],
      order: 2,
    },
  ],
  quiz: {
    id: "quiz-unit-4",
    chapterId: "unit-4",
    title: "第四章单元小测",
    instructions:
      "共 10 题，基础 2 题、进阶 4 题、压轴 4 题，整体难度明显上调，更强调多步推理、信息提取与综合应用。",
    passingScore: 80,
    questions: [
      {
        id: "q1",
        quizId: "quiz-unit-4",
        type: "single-choice",
        difficulty: "basic",
        stem: "下列图形中，属于立体图形的是哪个？",
        options: [
          { id: "a", label: "A", content: "三角形" },
          { id: "b", label: "B", content: "长方形" },
          { id: "c", label: "C", content: "圆柱" },
          { id: "d", label: "D", content: "线段" },
        ],
        correctOptionId: "c",
        explanation: "圆柱占有空间，属于立体图形；其余选项都属于平面图形或基本图形。",
        relatedLessonIds: ["lesson-solid-and-plane-figures"],
        relatedExampleIds: ["example-cube-observation"],
      },
      {
        id: "q2",
        quizId: "quiz-unit-4",
        type: "single-choice",
        difficulty: "basic",
        stem: "下列说法正确的是哪个？",
        options: [
          { id: "a", label: "A", content: "直线有两个端点" },
          { id: "b", label: "B", content: "射线有一个端点" },
          { id: "c", label: "C", content: "线段可以向两端无限延伸" },
          { id: "d", label: "D", content: "射线和线段都没有端点" },
        ],
        correctOptionId: "b",
        explanation: "射线有一个端点并向一端无限延伸；直线没有端点，线段有两个端点。",
        relatedLessonIds: ["lesson-lines-and-angles"],
        relatedExampleIds: ["example-angle-calculation"],
      },
      {
        id: "q3",
        quizId: "quiz-unit-4",
        type: "fill-blank",
        difficulty: "advanced",
        stem: "点 A、B、C 在同一直线上，且 B 在线段 AC 上。若 AB = 3 cm，AC = 8 cm，请先填写 BC 的长度，再说明所用的线段关系。",
        blanks: [
          {
            id: "bc",
            prompt: "BC 的长度",
            hint: "先根据点在线段上的位置关系求未知部分。",
            acceptableAnswers: ["5", "5 cm"],
            placeholder: "请填写结果",
          },
          {
            id: "relation",
            prompt: "所用线段关系",
            hint: "B 在线段 AC 上时，整段等于两部分之和。",
            acceptableAnswers: ["AB+BC=AC", "AB + BC = AC"],
            placeholder: "请填写关系",
          },
        ],
        explanation: "依据点 B 在线段 AC 上这一条件，有 AB + BC = AC，所以 BC = 5(cm)。",
        relatedLessonIds: ["lesson-lines-and-angles"],
        relatedExampleIds: ["example-angle-calculation"],
      },
      {
        id: "q4",
        quizId: "quiz-unit-4",
        type: "single-choice",
        difficulty: "advanced",
        stem: "一个角是 37°，它的补角是多少？",
        options: [
          { id: "a", label: "A", content: "53°" },
          { id: "b", label: "B", content: "127°" },
          { id: "c", label: "C", content: "143°" },
          { id: "d", label: "D", content: "217°" },
        ],
        correctOptionId: "c",
        explanation: "补角和为 180°，所以 180° - 37° = 143°。",
        relatedLessonIds: ["lesson-lines-and-angles"],
        relatedExampleIds: ["example-angle-calculation"],
      },
      {
        id: "q5",
        quizId: "quiz-unit-4",
        type: "fill-blank",
        difficulty: "advanced",
        stem: "观察图形，先写出补角关系式，再填写 ∠COB 的度数。",
        figure: createAngleFigure(
          "角 AOB 中标出角 AOC 为 35° 的示意图。",
          "O",
          "35°",
        ),
        blanks: [
          {
            id: "equation",
            prompt: "角之间的关系式",
            hint: "利用图中直角 90°，把已知角和未知角的和写成等式。",
            acceptableAnswers: ["35+∠cob=90", "∠aoc+∠cob=90", "∠cob+35=90"],
            placeholder: "请填写关系式",
          },
          {
            id: "angle",
            prompt: "∠COB 的度数",
            hint: "根据上一步关系式求解，填写度数，可带或不带 °。",
            acceptableAnswers: ["55°", "55"],
            placeholder: "请填写角度",
          },
        ],
        explanation: "∠AOC + ∠COB = ∠AOB = 90°，所以 ∠COB = 90° - 35° = 55°。",
        relatedLessonIds: ["lesson-lines-and-angles"],
        relatedExampleIds: ["example-angle-calculation"],
      },
      {
        id: "q6",
        quizId: "quiz-unit-4",
        type: "single-choice",
        difficulty: "advanced",
        stem: "一个平角被分成两个角，其中一个角比另一个角大 36°，较小的角是多少？",
        options: [
          { id: "a", label: "A", content: "72°" },
          { id: "b", label: "B", content: "78°" },
          { id: "c", label: "C", content: "84°" },
          { id: "d", label: "D", content: "108°" },
        ],
        correctOptionId: "a",
        explanation: "设较小角为 x，则另一个角为 x + 36°。因为它们组成平角，所以 2x + 36 = 180，解得 x = 72。",
        relatedLessonIds: ["lesson-lines-and-angles"],
        relatedExampleIds: ["example-angle-calculation"],
      },
      {
        id: "q7",
        quizId: "quiz-unit-4",
        type: "single-choice",
        difficulty: "challenge",
        stem: "把一个正方体放在桌面上，从上面看到的图形最可能是哪个？",
        options: [
          { id: "a", label: "A", content: "正方形" },
          { id: "b", label: "B", content: "三角形" },
          { id: "c", label: "C", content: "梯形" },
          { id: "d", label: "D", content: "扇形" },
        ],
        correctOptionId: "a",
        explanation: "正方体每个面都是正方形，从上面看到的是上面的一个面，因此看到正方形。",
        relatedLessonIds: ["lesson-solid-and-plane-figures"],
        relatedExampleIds: ["example-cube-observation"],
      },
      {
        id: "q8",
        quizId: "quiz-unit-4",
        type: "single-choice",
        difficulty: "challenge",
        stem: "已知射线 OC 把平角 ∠AOB 分成两个角，且 ∠AOC : ∠COB = 2 : 7，则 ∠AOC 是多少？",
        options: [
          { id: "a", label: "A", content: "20°" },
          { id: "b", label: "B", content: "30°" },
          { id: "c", label: "C", content: "40°" },
          { id: "d", label: "D", content: "50°" },
        ],
        correctOptionId: "c",
        explanation: "平角是 180°，共分成 2 + 7 = 9 份，每份 20°，所以 ∠AOC = 2 × 20° = 40°。",
        relatedLessonIds: ["lesson-lines-and-angles"],
        relatedExampleIds: ["example-angle-calculation"],
      },
      {
        id: "q9",
        quizId: "quiz-unit-4",
        type: "single-choice",
        difficulty: "challenge",
        stem: "一个角的补角比它大 48°，这个角是多少？",
        options: [
          { id: "a", label: "A", content: "56°" },
          { id: "b", label: "B", content: "66°" },
          { id: "c", label: "C", content: "72°" },
          { id: "d", label: "D", content: "84°" },
        ],
        correctOptionId: "b",
        explanation: "设这个角为 x，则补角为 180° - x。由题意 180 - x = x + 48，解得 x = 66。",
        relatedLessonIds: ["lesson-lines-and-angles"],
        relatedExampleIds: ["example-angle-calculation"],
      },
      {
        id: "q10",
        quizId: "quiz-unit-4",
        type: "fill-blank",
        difficulty: "challenge",
        stem: "如图，先写出含 x 的方程，再填写 x 的值。",
        figure: createAngleFigure(
          "直线上的相邻角示意图，其中一个角标为 3x°。",
          "O",
          "3x°",
        ),
        blanks: [
          {
            id: "equation",
            prompt: "列出的方程",
            hint: "把两个相邻角 3x° 和 2x° 相加，等于整个 ∠AOC 的 150°。",
            acceptableAnswers: ["3x+2x=150", "2x+3x=150"],
            placeholder: "请填写方程",
          },
          {
            id: "value",
            prompt: "x 的值",
            hint: "把同类项合并后求解，只填写 x 的数值。",
            acceptableAnswers: ["30"],
            placeholder: "请填写整数",
          },
        ],
        explanation: "相邻角满足 ∠AOB + ∠BOC = ∠AOC，所以 3x + 2x = 150，解得 x = 30。",
        relatedLessonIds: ["lesson-lines-and-angles"],
        relatedExampleIds: ["example-angle-calculation"],
      },
    ],
  },
};
