import type { CurriculumSlice } from "@/types/content";
import { createEquationBalanceFigure } from "./quiz-figures";

export const g7XiaUnit4Slice: CurriculumSlice = {
  grade: {
    id: "g7",
    label: "七年级",
    shortLabel: "七下",
    description: "从图形关系、方程模型到统计意识，继续搭建初中数学的基础骨架。",
  },
  volume: {
    id: "xia",
    gradeId: "g7",
    label: "下册",
    description: "以几何关系、坐标与方程思想为主线的进阶学习。",
  },
  chapter: {
    id: "g7-xia-unit-4",
    gradeId: "g7",
    volumeId: "xia",
    slug: "er-yuan-yi-ci-fang-cheng-zu",
    title: "第四章 二元一次方程组",
    summary: "理解二元一次方程组的意义，会用代入法和加减法解方程组，并解决简单应用问题。",
    order: 4,
    lessonIds: ["lesson-g7x4-system-meaning", "lesson-g7x4-substitution-elimination"],
    workedExampleIds: ["example-g7x4-substitution", "example-g7x4-application"],
    quizId: "quiz-g7-xia-unit-4",
  },
  lessons: [
    {
      id: "lesson-g7x4-system-meaning",
      chapterId: "g7-xia-unit-4",
      slug: "er-yuan-yi-ci-fang-cheng-zu-de-yi-yi",
      title: "二元一次方程组的意义",
      summary: "理解二元一次方程组中“两个未知数、两个条件”的关系，知道公共解的含义。",
      learningObjectives: [
        "能识别二元一次方程和二元一次方程组。",
        "知道方程组的解是同时满足两个方程的一组数值。",
        "能通过代入检验一组数是不是方程组的解。",
      ],
      keyRules: [
        "含有两个未知数，并且未知数次数都是 1 的方程叫做二元一次方程。",
        "把两个二元一次方程合在一起就得到二元一次方程组。",
        "方程组的解要同时满足两个方程。",
      ],
      bodyBlocks: [
        {
          type: "richText",
          id: "g7x4-meaning-context",
          title: "为什么要“同时满足”",
          content: [
            "方程组的两个方程通常描述的是同一件事的两个条件，所以最终答案必须同时通过两个条件的检验。",
            "只满足其中一个方程，不算方程组的解。",
          ],
        },
        {
          type: "formula",
          id: "g7x4-meaning-formula",
          title: "典型形式",
          formulas: ["{ x + y = 7, 2x - y = 5 }", "x = 4, y = 3"],
          note: "把一组数代入两个方程都成立，才叫方程组的解。",
        },
        {
          type: "tip",
          id: "g7x4-meaning-tip",
          title: "易错提醒",
          content: "检验时不要只代入一个方程，也不要只验一个未知数。",
        },
      ],
      relatedExampleIds: ["example-g7x4-substitution"],
      order: 1,
      videoPlaceholder: {
        title: "板书微课：方程组的解到底是什么",
        durationLabel: "4 分钟",
        description: "从“两个条件同时成立”理解方程组。",
      },
    },
    {
      id: "lesson-g7x4-substitution-elimination",
      chapterId: "g7-xia-unit-4",
      slug: "dai-ru-fa-yu-jia-jian-fa",
      title: "代入法与加减法",
      summary: "掌握代入法和加减法的基本思路，会根据方程特点选择更合适的方法。",
      learningObjectives: [
        "会把一个未知数用另一个未知数表示并代入求解。",
        "会通过同乘、同加或同减消去一个未知数。",
        "会根据系数特点选择代入法或加减法。",
      ],
      keyRules: [
        "代入法：先变形，再代入，最后回代求另一个未知数。",
        "加减法：先对齐未知数系数，再相加或相减消元。",
        "求出结果后要回代检验。",
      ],
      bodyBlocks: [
        {
          type: "richText",
          id: "g7x4-method-context",
          title: "什么时候用哪种方法",
          content: [
            "如果某个方程很容易写成 x = ... 或 y = ...，代入法往往更顺手。",
            "如果两个方程中某个未知数的系数接近或相同，加减法通常更快。",
          ],
        },
        {
          type: "formula",
          id: "g7x4-method-formula",
          title: "解题流程",
          formulas: ["变形 → 消元 → 求一个未知数 → 回代 → 检验", "同加同减的目标是消去一个未知数"],
          note: "核心不是机械操作，而是“消去一个未知数”。",
        },
        {
          type: "tip",
          id: "g7x4-method-tip",
          title: "易错提醒",
          content: "相加减前如果系数不一致，要先配系数，不要直接加减。",
        },
      ],
      relatedExampleIds: ["example-g7x4-substitution", "example-g7x4-application"],
      order: 2,
      videoPlaceholder: {
        title: "板书微课：方程组怎么选方法",
        durationLabel: "6 分钟",
        description: "比较代入法与加减法的适用场景。",
      },
    },
  ],
  workedExamples: [
    {
      id: "example-g7x4-substitution",
      chapterId: "g7-xia-unit-4",
      slug: "dai-ru-fa-jie-fang-cheng-zu",
      title: "例题 1：用代入法解方程组",
      summary: "先把一个未知数表示出来，再代入另一个方程求解。",
      problem: "解方程组：x + y = 7，2x - y = 5。",
      steps: [
        { id: "step-1", title: "先变形", content: "由 x + y = 7，得 y = 7 - x。" },
        { id: "step-2", title: "代入另一个方程", content: "把 y = 7 - x 代入 2x - y = 5，得 2x - (7 - x) = 5。" },
        { id: "step-3", title: "求出 x", content: "化简得 3x = 12，所以 x = 4。" },
        { id: "step-4", title: "回代求 y", content: "把 x = 4 代回 y = 7 - x，得 y = 3。" },
      ],
      answer: "x = 4，y = 3",
      commonMistakes: ["代入时忘记加括号。", "求出 x 后忘记回代求 y。"],
      relatedLessonIds: ["lesson-g7x4-system-meaning", "lesson-g7x4-substitution-elimination"],
      order: 1,
    },
    {
      id: "example-g7x4-application",
      chapterId: "g7-xia-unit-4",
      slug: "fang-cheng-zu-ying-yong",
      title: "例题 2：方程组应用",
      summary: "把数量关系翻译成方程组，再解出未知数。",
      problem: "篮球和足球共买了 8 个，其中篮球个数比足球多 2 个。求篮球和足球各买了多少个。",
      steps: [
        { id: "step-1", title: "设未知数", content: "设篮球买了 x 个，足球买了 y 个。" },
        { id: "step-2", title: "列方程组", content: "由总数得 x + y = 8，由数量差得 x - y = 2。" },
        { id: "step-3", title: "用加减法求解", content: "两式相加得 2x = 10，所以 x = 5；代回得 y = 3。" },
        { id: "step-4", title: "写出结论", content: "篮球买了 5 个，足球买了 3 个。" },
      ],
      answer: "篮球 5 个，足球 3 个",
      commonMistakes: ["把“多 2 个”列错成 y - x = 2。", "列出方程后忘记说明未知数所表示的量。"],
      relatedLessonIds: ["lesson-g7x4-substitution-elimination"],
      order: 2,
    },
  ],
  quiz: {
    id: "quiz-g7-xia-unit-4",
    chapterId: "g7-xia-unit-4",
    title: "第四章单元小测",
    instructions:
      "共 10 题，基础 2 题、进阶 4 题、压轴 4 题，整体难度明显上调，更强调多步推理、信息提取与综合应用。",
    passingScore: 80,
    questions: [
      {
        id: "q1",
        quizId: "quiz-g7-xia-unit-4",
        type: "single-choice",
        difficulty: "basic",
        stem: "下列各组中，是方程组 x + y = 5，x - y = 1 的解的是哪个？",
        options: [
          { id: "a", label: "A", content: "x = 2，y = 3" },
          { id: "b", label: "B", content: "x = 3，y = 2" },
          { id: "c", label: "C", content: "x = 1，y = 4" },
          { id: "d", label: "D", content: "x = 4，y = 1" },
        ],
        correctOptionId: "b",
        explanation: "只有 x = 3，y = 2 同时满足两个方程。",
        relatedLessonIds: ["lesson-g7x4-system-meaning"],
      },
      {
        id: "q2",
        quizId: "quiz-g7-xia-unit-4",
        type: "single-choice",
        difficulty: "basic",
        stem: "方程组中两个未知数的次数都是 1，这类方程组叫做什么？",
        options: [
          { id: "a", label: "A", content: "二元一次方程组" },
          { id: "b", label: "B", content: "一元二次方程组" },
          { id: "c", label: "C", content: "二元二次方程组" },
          { id: "d", label: "D", content: "多元方程组" },
        ],
        correctOptionId: "a",
        explanation: "含有两个未知数且未知数次数都为 1 的方程组叫做二元一次方程组。",
        relatedLessonIds: ["lesson-g7x4-system-meaning"],
      },
      {
        id: "q3",
        quizId: "quiz-g7-xia-unit-4",
        type: "fill-blank",
        difficulty: "advanced",
        stem: "解方程组：x + y = 9，x - y = 1。请先写出两式相加后的结果，再填写 x 与 y 的值。",
        blanks: [
          {
            id: "sum",
            prompt: "两式相加后的方程",
            hint: "相加后 y 会被消去。",
            acceptableAnswers: ["2x=10", "2x = 10"],
            placeholder: "请填写方程",
          },
          {
            id: "solution",
            prompt: "依据相关关系，最终解",
            hint: "先判断所用关系或方法，再先求 x，再代回原方程求 y。",
            acceptableAnswers: ["x=5,y=4", "x = 5, y = 4", "x=5，y=4"],
            placeholder: "请填写结果",
          },
        ],
        explanation: "依据题目中的条件和相关性质，两式相加得 2x = 10，所以 x = 5；代入 x + y = 9，得 y = 4。",
        relatedLessonIds: ["lesson-g7x4-substitution-elimination"],
      },
      {
        id: "q4",
        quizId: "quiz-g7-xia-unit-4",
        type: "single-choice",
        difficulty: "advanced",
        stem: "解方程组 x = y + 2，2x + y = 11，较方便的方法是什么？",
        options: [
          { id: "a", label: "A", content: "代入法" },
          { id: "b", label: "B", content: "配方法" },
          { id: "c", label: "C", content: "开方法" },
          { id: "d", label: "D", content: "列表法" },
        ],
        correctOptionId: "a",
        explanation: "第一个方程已经写成 x = ... 的形式，直接代入最方便。",
        relatedLessonIds: ["lesson-g7x4-substitution-elimination"],
      },
      {
        id: "q5",
        quizId: "quiz-g7-xia-unit-4",
        type: "fill-blank",
        difficulty: "advanced",
        stem: "方程组 2x + y = 8，x - y = 1。请先用加减法消去 y，再写出 x 的值。",
        blanks: [
          {
            id: "elim",
            prompt: "消去 y 后的方程",
            hint: "把两个方程直接相加。",
            acceptableAnswers: ["3x=9", "3x = 9"],
            placeholder: "请填写方程",
          },
          {
            id: "x-value",
            prompt: "x 的值",
            hint: "解出 x 后即可。",
            acceptableAnswers: ["3"],
            placeholder: "请填写结果",
          },
        ],
        explanation: "两式相加得 3x = 9，所以 x = 3。",
        relatedLessonIds: ["lesson-g7x4-substitution-elimination"],
      },
      {
        id: "q6",
        quizId: "quiz-g7-xia-unit-4",
        type: "single-choice",
        difficulty: "advanced",
        stem: "若二元一次方程组的解是 x = 2，y = 1，则下面哪个方程一定与它相容？",
        options: [
          { id: "a", label: "A", content: "x + y = 5" },
          { id: "b", label: "B", content: "2x + y = 5" },
          { id: "c", label: "C", content: "x - y = 4" },
          { id: "d", label: "D", content: "3x + y = 10" },
        ],
        correctOptionId: "b",
        explanation: "代入 x = 2，y = 1，只有 2x + y = 5 成立。",
        relatedLessonIds: ["lesson-g7x4-system-meaning"],
      },
      {
        id: "q7",
        quizId: "quiz-g7-xia-unit-4",
        type: "fill-blank",
        difficulty: "challenge",
        stem: "某班买练习本和圆珠笔共 14 件，圆珠笔比练习本少 2 件。设练习本 x 件，圆珠笔 y 件。请先写出方程组，再写出解。",
        blanks: [
          {
            id: "system",
            prompt: "方程组",
            hint: "总数一个方程，数量关系一个方程。",
            acceptableAnswers: ["x+y=14,x-y=2", "x + y = 14, x - y = 2", "{x+y=14,x-y=2}"],
            placeholder: "请填写方程组",
          },
          {
            id: "answer",
            prompt: "解",
            hint: "先加减消元，再解释 x、y 表示的含义。",
            acceptableAnswers: ["x=8,y=6", "x = 8, y = 6", "x=8，y=6"],
            placeholder: "请填写结果",
          },
        ],
        explanation: "由总数得 x + y = 14，由“圆珠笔比练习本少 2 件”得 x - y = 2，解得 x = 8，y = 6。",
        relatedLessonIds: ["lesson-g7x4-substitution-elimination"],
      },
      {
        id: "q8",
        quizId: "quiz-g7-xia-unit-4",
        type: "single-choice",
        difficulty: "challenge",
        stem: "若方程组 x + y = 6，2x + 2y = 12 有无数组解，原因是什么？",
        options: [
          { id: "a", label: "A", content: "两个方程表示的条件完全相同" },
          { id: "b", label: "B", content: "两个方程互相矛盾" },
          { id: "c", label: "C", content: "方程组没有未知数" },
          { id: "d", label: "D", content: "只能靠画图判断" },
        ],
        correctOptionId: "a",
        explanation: "第二个方程是第一个方程的 2 倍，表示的是同一条直线，所以有无数组解。",
        relatedLessonIds: ["lesson-g7x4-system-meaning"],
      },
      {
        id: "q9",
        quizId: "quiz-g7-xia-unit-4",
        type: "fill-blank",
        difficulty: "challenge",
        stem: "如图，天平图表示方程组 x + y = 10，x - y = 2。请填写两式相加后的结果，并写出 y 的值。",
        figure: createEquationBalanceFigure("方程组 x+y=10 与 x-y=2 的示意图。", "x+y", "10"),
        blanks: [
          {
            id: "sum",
            prompt: "相加后的结果",
            hint: "相加后 y 被消去。",
            acceptableAnswers: ["2x=12", "2x = 12"],
            placeholder: "请填写结果",
          },
          {
            id: "y",
            prompt: "y 的值",
            hint: "先由 2x = 12 求 x，再代回 x + y = 10。",
            acceptableAnswers: ["4"],
            placeholder: "请填写结果",
          },
        ],
        explanation: "相加得 2x = 12，x = 6；代回 x + y = 10，得 y = 4。",
        relatedLessonIds: ["lesson-g7x4-substitution-elimination"],
      },
      {
        id: "q10",
        quizId: "quiz-g7-xia-unit-4",
        type: "fill-blank",
        difficulty: "challenge",
        stem: "甲、乙两人共有 38 元，若甲给乙 4 元后，两人的钱数相等。设甲原有 x 元，乙原有 y 元。请先列方程组，再写出甲原有多少钱。",
        blanks: [
          {
            id: "system",
            prompt: "方程组",
            hint: "总钱数一个方程，相等关系一个方程。",
            acceptableAnswers: ["x+y=38,x-4=y+4", "x + y = 38, x - 4 = y + 4", "{x+y=38,x-4=y+4}"],
            placeholder: "请填写方程组",
          },
          {
            id: "x",
            prompt: "甲原有的钱数",
            hint: "由 x - y = 8 与 x + y = 38 联立求解。",
            acceptableAnswers: ["23"],
            placeholder: "请填写结果",
          },
        ],
        explanation: "由 x + y = 38，x - 4 = y + 4 可得 x - y = 8。联立解得 x = 23，y = 15。",
        relatedLessonIds: ["lesson-g7x4-substitution-elimination"],
      },
    ],
  },
};
