import type { CurriculumSlice } from "@/types/content";
import { createParallelLinesFigure } from "./quiz-figures";

export const g7XiaUnit1Slice: CurriculumSlice = {
  grade: {
    id: "g7",
    label: "七年级",
    shortLabel: "七下",
    description: "从图形关系、方程模型到统计意识，继续搭建初中数学的基础骨架。",
  },
  volume: {
    id: "xia",
    gradeId: "g7",
    label: "下册",
    description: "以几何关系、坐标与方程思想为主线的进阶学习。",
  },
  chapter: {
    id: "g7-xia-unit-1",
    gradeId: "g7",
    volumeId: "xia",
    slug: "xiang-jiao-xian-yu-ping-xing-xian",
    title: "第一章 相交线与平行线",
    summary:
      "认识邻补角、对顶角以及平行线的性质与判定，会用角度关系解决简单几何问题。",
    order: 1,
    lessonIds: [
      "lesson-g7x-intersecting-lines",
      "lesson-g7x-parallel-line-properties",
    ],
    workedExampleIds: [
      "example-g7x-vertical-angle",
      "example-g7x-parallel-angle",
    ],
    quizId: "quiz-g7-xia-unit-1",
    coverImage: {
      src: "/images/content/g7-xia-unit-1-cover.svg",
      alt: "第一章相交线与平行线封面示意图",
    },
  },
  lessons: [
    {
      id: "lesson-g7x-intersecting-lines",
      chapterId: "g7-xia-unit-1",
      slug: "xiang-jiao-xian-yu-jiao-guan-xi",
      title: "相交线与角的关系",
      summary: "理解邻补角与对顶角的特点，能快速判断角之间的数量关系。",
      learningObjectives: [
        "能识别邻补角和对顶角。",
        "会利用平角是 180° 求未知角度。",
        "知道对顶角相等的结论并能直接应用。",
      ],
      keyRules: [
        "有公共顶点和一条公共边，另一边互为反向延长线的两个角是邻补角。",
        "邻补角的和等于 180°。",
        "对顶角相等。",
      ],
      bodyBlocks: [
        {
          type: "richText",
          id: "g7x-context-1",
          title: "先看图形位置",
          content: [
            "两条直线相交时，会形成四个角。判断角关系时，先看它们有没有公共边，再看另外两边是不是在同一条直线上。",
            "如果两个角面对面地“顶着”，它们就是对顶角；如果两个角拼起来刚好是一条直线，它们就是邻补角。",
          ],
        },
        {
          type: "formula",
          id: "g7x-formula-1",
          title: "常用关系",
          formulas: ["∠1 + ∠2 = 180°", "∠1 = ∠3", "已知一个角，其邻补角 = 180° - 这个角"],
          note: "先判断关系，再列式，不要一上来就盲目相减。",
        },
        {
          type: "tip",
          id: "g7x-tip-1",
          title: "易错提醒",
          content: "对顶角相等，但邻补角一般不相等，只是和为 180°。",
        },
      ],
      relatedExampleIds: ["example-g7x-vertical-angle"],
      order: 1,
      videoPlaceholder: {
        title: "板书微课：相交线里的角关系",
        durationLabel: "4 分钟",
        description: "用十字交叉图快速辨认对顶角和邻补角。",
      },
    },
    {
      id: "lesson-g7x-parallel-line-properties",
      chapterId: "g7-xia-unit-1",
      slug: "ping-xing-xian-de-xing-zhi-yu-pan-ding",
      title: "平行线的性质与判定",
      summary: "掌握同位角、内错角、同旁内角的关系，会由角判断两直线是否平行。",
      learningObjectives: [
        "能在截线图中找出同位角、内错角和同旁内角。",
        "会运用平行线的性质求角度。",
        "能根据角相等或互补判断两条直线平行。",
      ],
      keyRules: [
        "两直线平行，同位角相等。",
        "两直线平行，内错角相等。",
        "两直线平行，同旁内角互补。",
      ],
      bodyBlocks: [
        {
          type: "richText",
          id: "g7x-context-2",
          title: "为什么要先找截线",
          content: [
            "平行线问题里最关键的是找到一条同时穿过两条直线的截线。角的位置关系都是相对这条截线来判断的。",
            "只要位置找准了，平行线的性质和判定就会非常稳定，不容易混淆。",
          ],
        },
        {
          type: "formula",
          id: "g7x-formula-2",
          title: "判定与性质对照",
          formulas: [
            "同位角相等 ⇔ 两直线平行",
            "内错角相等 ⇔ 两直线平行",
            "同旁内角互补 ⇔ 两直线平行",
          ],
          note: "看题目是“已知平行求角”还是“已知角求平行”，别把方向用反了。",
        },
        {
          type: "tip",
          id: "g7x-tip-2",
          title: "易错提醒",
          content: "同旁内角是互补，不是相等；很多同学会和内错角混淆。",
        },
      ],
      relatedExampleIds: ["example-g7x-parallel-angle"],
      order: 2,
      videoPlaceholder: {
        title: "板书微课：平行线角关系速判",
        durationLabel: "5 分钟",
        description: "按“找截线—定位置—用性质”的顺序做题。",
      },
    },
  ],
  workedExamples: [
    {
      id: "example-g7x-vertical-angle",
      chapterId: "g7-xia-unit-1",
      slug: "dui-ding-jiao-qiu-jiao",
      title: "例题 1：对顶角求角",
      summary: "利用邻补角和对顶角相等求未知角。",
      problem: "两条直线相交，已知其中一个角为 58°，求它的邻补角和对顶角。",
      steps: [
        {
          id: "step-1",
          title: "先找邻补角",
          content: "邻补角与已知角组成平角，所以邻补角 = 180° - 58° = 122°。",
        },
        {
          id: "step-2",
          title: "再找对顶角",
          content: "对顶角与已知角相等，所以对顶角 = 58°。",
        },
        {
          id: "step-3",
          title: "整理结果",
          content: "邻补角是 122°，对顶角是 58°。",
        },
      ],
      answer: "邻补角 122°，对顶角 58°",
      commonMistakes: [
        "把对顶角错看成邻补角，直接算成 122°。",
        "算出角度后漏写单位。",
      ],
      relatedLessonIds: ["lesson-g7x-intersecting-lines"],
      order: 1,
    },
    {
      id: "example-g7x-parallel-angle",
      chapterId: "g7-xia-unit-1",
      slug: "ping-xing-xian-jiao-du-zhui-zong",
      title: "例题 2：平行线中的角度追踪",
      summary: "用同位角相等和邻补角关系求未知角。",
      problem: "直线 a ∥ b，截线 c 与 a 交于点 A，与 b 交于点 B。若在点 A 处的一个角为 68°，求点 B 处与它同位的角和与它同旁内的角。",
      steps: [
        {
          id: "step-1",
          title: "找同位角",
          content: "因为 a ∥ b，所以同位角相等，点 B 处对应的同位角也是 68°。",
        },
        {
          id: "step-2",
          title: "找同旁内角",
          content: "同旁内角互补，所以另一个角 = 180° - 68° = 112°。",
        },
        {
          id: "step-3",
          title: "写出答案",
          content: "同位角是 68°，同旁内角是 112°。",
        },
      ],
      answer: "68°，112°",
      commonMistakes: [
        "把同旁内角也误判成相等。",
        "没有先确定角的位置关系就直接减法。",
      ],
      relatedLessonIds: ["lesson-g7x-parallel-line-properties"],
      order: 2,
    },
  ],
  quiz: {
    id: "quiz-g7-xia-unit-1",
    chapterId: "g7-xia-unit-1",
    title: "第一章单元小测",
    instructions:
      "共 10 题，基础 2 题、进阶 4 题、压轴 4 题，整体难度明显上调，更强调多步推理、信息提取与综合应用。",
    passingScore: 80,
    questions: [
      {
        id: "q1",
        quizId: "quiz-g7-xia-unit-1",
        type: "single-choice",
        difficulty: "basic",
        stem: "两条直线相交形成的对顶角有怎样的数量关系？",
        options: [
          { id: "a", label: "A", content: "互补" },
          { id: "b", label: "B", content: "相等" },
          { id: "c", label: "C", content: "和为 90°" },
          { id: "d", label: "D", content: "没有固定关系" },
        ],
        correctOptionId: "b",
        explanation: "对顶角相等，这是相交线中的基本结论。",
        relatedLessonIds: ["lesson-g7x-intersecting-lines"],
        relatedExampleIds: ["example-g7x-vertical-angle"],
      },
      {
        id: "q2",
        quizId: "quiz-g7-xia-unit-1",
        type: "single-choice",
        difficulty: "basic",
        stem: "若一个角是 46°，与它相邻的补角是多少？",
        options: [
          { id: "a", label: "A", content: "44°" },
          { id: "b", label: "B", content: "134°" },
          { id: "c", label: "C", content: "146°" },
          { id: "d", label: "D", content: "154°" },
        ],
        correctOptionId: "b",
        explanation: "邻补角和为 180°，所以 180° - 46° = 134°。",
        relatedLessonIds: ["lesson-g7x-intersecting-lines"],
        relatedExampleIds: ["example-g7x-vertical-angle"],
      },
      {
        id: "q3",
        quizId: "quiz-g7-xia-unit-1",
        type: "fill-blank",
        difficulty: "advanced",
        stem: "若直线 a ∥ b，被截线 c 所截，其中一组同旁内角中一个角是 118°。请先填写另一个角的度数，再说明所用的角关系。",
        blanks: [
          {
            id: "angle",
            prompt: "另一个角的度数",
            hint: "先判断这是哪一类角，再用其数量关系求值。",
            acceptableAnswers: ["62°", "62"],
            placeholder: "请填写结果",
          },
          {
            id: "relation",
            prompt: "所用角关系",
            hint: "平行线被截时，这组角的和是 180°。",
            acceptableAnswers: ["同旁内角互补", "同旁内角和为180°"],
            placeholder: "请填写关系",
          },
        ],
        explanation: "依据平行线被截时同旁内角互补，可得另一个角为 180° - 118° = 62°。",
        relatedLessonIds: ["lesson-g7x-parallel-line-properties"],
        relatedExampleIds: ["example-g7x-parallel-angle"],
      },
      {
        id: "q4",
        quizId: "quiz-g7-xia-unit-1",
        type: "single-choice",
        difficulty: "advanced",
        stem: "若两条平行线被一条截线所截，则同位角之间的关系是哪个？",
        options: [
          { id: "a", label: "A", content: "相等" },
          { id: "b", label: "B", content: "互补" },
          { id: "c", label: "C", content: "互余" },
          { id: "d", label: "D", content: "大小不确定" },
        ],
        correctOptionId: "a",
        explanation: "两直线平行时，同位角相等。",
        relatedLessonIds: ["lesson-g7x-parallel-line-properties"],
        relatedExampleIds: ["example-g7x-parallel-angle"],
      },
      {
        id: "q5",
        quizId: "quiz-g7-xia-unit-1",
        type: "fill-blank",
        difficulty: "advanced",
        stem: "观察图中的平行线示意图，先填内错角，再填与它同旁的内角。",
        figure: createParallelLinesFigure(
          "两条平行线被截线所截，上方角标为 73°。",
          "73°",
          "?",
        ),
        blanks: [
          {
            id: "alternate",
            prompt: "对应的内错角",
            hint: "先找与已知角被同一条截线切出的内错位置，填写该角度数。",
            acceptableAnswers: ["73°", "73"],
            placeholder: "请填写角度",
          },
          {
            id: "same-side",
            prompt: "与它同旁的内角",
            hint: "同旁内角互补，用 180° 减去已知角后填写结果。",
            acceptableAnswers: ["107°", "107"],
            placeholder: "请填写角度",
          },
        ],
        explanation: "平行线被截时，内错角相等，所以另一个内错角是 73°；同旁内角互补，所以另一个角是 180° - 73° = 107°。",
        relatedLessonIds: ["lesson-g7x-parallel-line-properties"],
        relatedExampleIds: ["example-g7x-parallel-angle"],
      },
      {
        id: "q6",
        quizId: "quiz-g7-xia-unit-1",
        type: "single-choice",
        difficulty: "advanced",
        stem: "若直线 a ∥ b，且一个同位角是 128°，则与它相邻的另一个同位位置所对应的锐角是多少？",
        options: [
          { id: "a", label: "A", content: "38°" },
          { id: "b", label: "B", content: "42°" },
          { id: "c", label: "C", content: "52°" },
          { id: "d", label: "D", content: "62°" },
        ],
        correctOptionId: "c",
        explanation: "128° 的邻补角是 180° - 128° = 52°，对应位置的锐角也应是 52°。",
        relatedLessonIds: ["lesson-g7x-intersecting-lines", "lesson-g7x-parallel-line-properties"],
        relatedExampleIds: ["example-g7x-parallel-angle"],
      },
      {
        id: "q7",
        quizId: "quiz-g7-xia-unit-1",
        type: "single-choice",
        difficulty: "challenge",
        stem: "若 ∠1 与 ∠2 是对顶角，且 ∠1 = 3x + 5°，∠2 = 2x + 25°，则 x 等于多少？",
        options: [
          { id: "a", label: "A", content: "10" },
          { id: "b", label: "B", content: "15" },
          { id: "c", label: "C", content: "20" },
          { id: "d", label: "D", content: "25" },
        ],
        correctOptionId: "c",
        explanation: "对顶角相等，所以 3x + 5 = 2x + 25，解得 x = 20。",
        relatedLessonIds: ["lesson-g7x-intersecting-lines"],
        relatedExampleIds: ["example-g7x-vertical-angle"],
      },
      {
        id: "q8",
        quizId: "quiz-g7-xia-unit-1",
        type: "single-choice",
        difficulty: "challenge",
        stem: "若同旁内角一个为 2x + 10°，另一个为 x + 20°，且两直线平行，则 x 等于多少？",
        options: [
          { id: "a", label: "A", content: "30" },
          { id: "b", label: "B", content: "40" },
          { id: "c", label: "C", content: "50" },
          { id: "d", label: "D", content: "60" },
        ],
        correctOptionId: "c",
        explanation: "同旁内角互补，所以 2x + 10 + x + 20 = 180，解得 3x = 150，x = 50。",
        relatedLessonIds: ["lesson-g7x-parallel-line-properties"],
        relatedExampleIds: ["example-g7x-parallel-angle"],
      },
      {
        id: "q9",
        quizId: "quiz-g7-xia-unit-1",
        type: "fill-blank",
        difficulty: "challenge",
        stem: "如图，两条直线要保持平行。请先列出同位角相等的方程，再填写 x 的值。",
        figure: createParallelLinesFigure(
          "平行线判定图，上下两个同位角分别用 4x-10° 和 3x+20° 表示。",
          "4x-10°",
          "3x+20°",
        ),
        blanks: [
          {
            id: "equation",
            prompt: "列出的方程",
            hint: "两条直线平行时，同位角相等，把图中两个代数式写成等式。",
            acceptableAnswers: ["4x-10=3x+20", "3x+20=4x-10"],
            placeholder: "请填写方程",
          },
          {
            id: "value",
            prompt: "x 的值",
            hint: "先解出等式，再填写 x 的具体数值。",
            acceptableAnswers: ["30"],
            placeholder: "请填写整数",
          },
        ],
        explanation: "同位角相等时两直线平行，所以 4x - 10 = 3x + 20，解得 x = 30。",
        relatedLessonIds: ["lesson-g7x-parallel-line-properties"],
        relatedExampleIds: ["example-g7x-parallel-angle"],
      },
      {
        id: "q10",
        quizId: "quiz-g7-xia-unit-1",
        type: "single-choice",
        difficulty: "challenge",
        stem: "在相交直线中，若一个角是另一个邻补角的 2 倍，则较小的角是多少？",
        options: [
          { id: "a", label: "A", content: "50°" },
          { id: "b", label: "B", content: "60°" },
          { id: "c", label: "C", content: "70°" },
          { id: "d", label: "D", content: "80°" },
        ],
        correctOptionId: "b",
        explanation: "设较小角为 x，则另一个邻补角为 2x，且 x + 2x = 180，解得 x = 60°。",
        relatedLessonIds: ["lesson-g7x-intersecting-lines"],
        relatedExampleIds: ["example-g7x-vertical-angle"],
      },
    ],
  },
};
