import type { CurriculumSlice } from "@/types/content";

export const g7XiaUnit3Slice: CurriculumSlice = {
  grade: {
    id: "g7",
    label: "七年级",
    shortLabel: "七下",
    description: "从图形关系、方程模型到统计意识，继续搭建初中数学的基础骨架。",
  },
  volume: {
    id: "xia",
    gradeId: "g7",
    label: "下册",
    description: "以几何关系、坐标与方程思想为主线的进阶学习。",
  },
  chapter: {
    id: "g7-xia-unit-3",
    gradeId: "g7",
    volumeId: "xia",
    slug: "ping-mian-zhi-jiao-zuo-biao-xi",
    title: "第三章 平面直角坐标系",
    summary: "理解有序数对与平面直角坐标系，会根据点的坐标判断位置并解决简单图形平移问题。",
    order: 3,
    lessonIds: ["lesson-g7x3-ordered-pair", "lesson-g7x3-coordinate-plane"],
    workedExampleIds: ["example-g7x3-read-point", "example-g7x3-translate-point"],
    quizId: "quiz-g7-xia-unit-3",
  },
  lessons: [
    {
      id: "lesson-g7x3-ordered-pair",
      chapterId: "g7-xia-unit-3",
      slug: "you-xu-shu-dui",
      title: "有序数对",
      summary: "理解有序数对的意义，知道顺序不同表示的位置不同。",
      learningObjectives: [
        "能用有序数对表示平面内一点的位置。",
        "知道数对中前后位置不能随意交换。",
        "会在简单情境中根据描述写出有序数对。",
      ],
      keyRules: [
        "有序数对写作 (a, b)。",
        "前一个数和后一个数表示的含义不同。",
        "(a, b) 与 (b, a) 一般表示不同的位置。",
      ],
      bodyBlocks: [
        {
          type: "richText",
          id: "g7x3-ordered-context",
          title: "为什么强调“有序”",
          content: [
            "在座位、地图或棋盘中，先横后纵和先纵后横表示的往往不是同一个位置。",
            "所以写有序数对时，不仅要写对数字，还要写对顺序。",
          ],
        },
        {
          type: "formula",
          id: "g7x3-ordered-formula",
          title: "典型表示",
          formulas: ["A(2, 3)", "B(-1, 4)", "(2, 3) ≠ (3, 2)"],
          note: "括号和逗号都是有序数对的一部分。",
        },
        {
          type: "tip",
          id: "g7x3-ordered-tip",
          title: "易错提醒",
          content: "写点坐标时，要同时写点名和坐标，不要只写一个数字。",
        },
      ],
      relatedExampleIds: ["example-g7x3-read-point"],
      order: 1,
      videoPlaceholder: {
        title: "板书微课：有序数对的顺序为什么不能换",
        durationLabel: "4 分钟",
        description: "用座位表和棋盘格理解“先后次序”的作用。",
      },
    },
    {
      id: "lesson-g7x3-coordinate-plane",
      chapterId: "g7-xia-unit-3",
      slug: "ping-mian-zhi-jiao-zuo-biao-xi",
      title: "平面直角坐标系",
      summary: "掌握横轴、纵轴、原点和象限，会读写点坐标并描述平移后的变化。",
      learningObjectives: [
        "能在坐标系中读出点的坐标。",
        "知道原点、坐标轴和四个象限。",
        "会根据左右、上下平移写出新坐标。",
      ],
      keyRules: [
        "横轴上的点纵坐标为 0，纵轴上的点横坐标为 0。",
        "点在第一象限时，横纵坐标都为正。",
        "向右平移横坐标加，向左平移横坐标减；向上平移纵坐标加，向下平移纵坐标减。",
      ],
      bodyBlocks: [
        {
          type: "richText",
          id: "g7x3-plane-context",
          title: "先横后纵",
          content: [
            "在平面直角坐标系里，读点坐标一定是先看横向位置，再看纵向位置。",
            "平移时也一样，要分别观察横坐标和纵坐标怎样变化，不要一股脑一起改。",
          ],
        },
        {
          type: "formula",
          id: "g7x3-plane-formula",
          title: "平移变化",
          formulas: ["(x, y) 向右平移 3 个单位 → (x+3, y)", "(x, y) 向下平移 2 个单位 → (x, y-2)"],
          note: "只改对应方向上的坐标，另一个坐标保持不变。",
        },
        {
          type: "tip",
          id: "g7x3-plane-tip",
          title: "易错提醒",
          content: "点在坐标轴上时，不属于任何象限。",
        },
      ],
      relatedExampleIds: ["example-g7x3-translate-point"],
      order: 2,
      videoPlaceholder: {
        title: "板书微课：坐标系里的读点和平移",
        durationLabel: "5 分钟",
        description: "从坐标含义出发理解象限和点的平移。",
      },
    },
  ],
  workedExamples: [
    {
      id: "example-g7x3-read-point",
      chapterId: "g7-xia-unit-3",
      slug: "du-dian-zuo-biao",
      title: "例题 1：读点坐标",
      summary: "按先横后纵的顺序正确读出点坐标。",
      problem: "在平面直角坐标系中，点 A 在原点右侧 2 个单位、上方 3 个单位，写出点 A 的坐标。",
      steps: [
        { id: "step-1", title: "先看横向位置", content: "原点右侧 2 个单位，所以横坐标是 2。" },
        { id: "step-2", title: "再看纵向位置", content: "原点上方 3 个单位，所以纵坐标是 3。" },
        { id: "step-3", title: "写成有序数对", content: "因此点 A 的坐标是 (2, 3)。" },
      ],
      answer: "A(2, 3)",
      commonMistakes: ["把顺序写反成 (3, 2)。", "忘记写括号或逗号。"],
      relatedLessonIds: ["lesson-g7x3-ordered-pair", "lesson-g7x3-coordinate-plane"],
      order: 1,
    },
    {
      id: "example-g7x3-translate-point",
      chapterId: "g7-xia-unit-3",
      slug: "dian-de-ping-yi",
      title: "例题 2：点的平移",
      summary: "根据点的平移方向写出新坐标。",
      problem: "点 B 的坐标是 (-2, 5)，先向右平移 4 个单位，再向下平移 3 个单位，求平移后点 B' 的坐标。",
      steps: [
        { id: "step-1", title: "先向右平移", content: "横坐标加 4，所以变成 (-2 + 4, 5) = (2, 5)。" },
        { id: "step-2", title: "再向下平移", content: "纵坐标减 3，所以变成 (2, 5 - 3) = (2, 2)。" },
        { id: "step-3", title: "写出结果", content: "因此平移后点 B' 的坐标是 (2, 2)。" },
      ],
      answer: "B'(2, 2)",
      commonMistakes: ["向右平移时错误地改了纵坐标。", "两次平移只算了一次。"],
      relatedLessonIds: ["lesson-g7x3-coordinate-plane"],
      order: 2,
    },
  ],
  quiz: {
    id: "quiz-g7-xia-unit-3",
    chapterId: "g7-xia-unit-3",
    title: "第三章单元小测",
    instructions:
      "共 10 题，基础 2 题、进阶 4 题、压轴 4 题，整体难度明显上调，更强调多步推理、信息提取与综合应用。",
    passingScore: 80,
    questions: [
      {
        id: "q1",
        quizId: "quiz-g7-xia-unit-3",
        type: "single-choice",
        difficulty: "basic",
        stem: "下列各组中，表示同一个点坐标的是哪个？",
        options: [
          { id: "a", label: "A", content: "(2, 3) 和 (2, 3)" },
          { id: "b", label: "B", content: "(2, 3) 和 (3, 2)" },
          { id: "c", label: "C", content: "(-2, 3) 和 (2, -3)" },
          { id: "d", label: "D", content: "(0, 4) 和 (4, 0)" },
        ],
        correctOptionId: "a",
        explanation: "有序数对必须数字和顺序都相同，才表示同一个点。",
        relatedLessonIds: ["lesson-g7x3-ordered-pair"],
      },
      {
        id: "q2",
        quizId: "quiz-g7-xia-unit-3",
        type: "single-choice",
        difficulty: "basic",
        stem: "点 P(0, -4) 在哪里？",
        options: [
          { id: "a", label: "A", content: "第一象限" },
          { id: "b", label: "B", content: "第二象限" },
          { id: "c", label: "C", content: "y 轴上" },
          { id: "d", label: "D", content: "x 轴上" },
        ],
        correctOptionId: "c",
        explanation: "横坐标是 0，说明点在 y 轴上，不属于任何象限。",
        relatedLessonIds: ["lesson-g7x3-coordinate-plane"],
      },
      {
        id: "q3",
        quizId: "quiz-g7-xia-unit-3",
        type: "fill-blank",
        difficulty: "advanced",
        stem: "点 A 在第一象限，横坐标是 3，纵坐标比横坐标大 2。请写出点 A 的坐标，并判断它是否在直线 x = y 上。",
        blanks: [
          {
            id: "coord",
            prompt: "点 A 的坐标",
            hint: "先算纵坐标，再按先横后纵写坐标。",
            acceptableAnswers: ["(3,5)", "(3, 5)"],
            placeholder: "请填写坐标",
          },
          {
            id: "line",
            prompt: "是否在 x = y 上",
            hint: "比较横坐标和纵坐标是否相等。",
            acceptableAnswers: ["不在", "否"],
            placeholder: "请填写判断",
          },
        ],
        explanation: "依据题目中的条件和相关性质，纵坐标为 3 + 2 = 5，所以 A(3, 5)。因为 3 ≠ 5，所以它不在 x = y 上。",
        relatedLessonIds: ["lesson-g7x3-ordered-pair", "lesson-g7x3-coordinate-plane"],
      },
      {
        id: "q4",
        quizId: "quiz-g7-xia-unit-3",
        type: "single-choice",
        difficulty: "advanced",
        stem: "点 B(-2, 4) 向右平移 5 个单位后，坐标变成哪个？",
        options: [
          { id: "a", label: "A", content: "(3, 4)" },
          { id: "b", label: "B", content: "(-7, 4)" },
          { id: "c", label: "C", content: "(-2, 9)" },
          { id: "d", label: "D", content: "(3, 9)" },
        ],
        correctOptionId: "a",
        explanation: "向右平移只改变横坐标，-2 + 5 = 3，纵坐标不变。",
        relatedLessonIds: ["lesson-g7x3-coordinate-plane"],
      },
      {
        id: "q5",
        quizId: "quiz-g7-xia-unit-3",
        type: "fill-blank",
        difficulty: "advanced",
        stem: "点 C(a, 2) 在 y 轴上，点 D(-3, b) 在 x 轴上。请分别写出 a、b 的值。",
        blanks: [
          {
            id: "a-value",
            prompt: "a 的值",
            hint: "在 y 轴上的点横坐标是多少？",
            acceptableAnswers: ["0"],
            placeholder: "请填写结果",
          },
          {
            id: "b-value",
            prompt: "b 的值",
            hint: "在 x 轴上的点纵坐标是多少？",
            acceptableAnswers: ["0"],
            placeholder: "请填写结果",
          },
        ],
        explanation: "在 y 轴上的点横坐标为 0，在 x 轴上的点纵坐标为 0。",
        relatedLessonIds: ["lesson-g7x3-coordinate-plane"],
      },
      {
        id: "q6",
        quizId: "quiz-g7-xia-unit-3",
        type: "single-choice",
        difficulty: "advanced",
        stem: "若点 E(m, n) 在第二象限，则 m、n 的符号应是哪个？",
        options: [
          { id: "a", label: "A", content: "m > 0，n > 0" },
          { id: "b", label: "B", content: "m < 0，n > 0" },
          { id: "c", label: "C", content: "m < 0，n < 0" },
          { id: "d", label: "D", content: "m > 0，n < 0" },
        ],
        correctOptionId: "b",
        explanation: "第二象限内的点横坐标为负，纵坐标为正。",
        relatedLessonIds: ["lesson-g7x3-coordinate-plane"],
      },
      {
        id: "q7",
        quizId: "quiz-g7-xia-unit-3",
        type: "fill-blank",
        difficulty: "challenge",
        stem: "点 F(1, -2) 先向左平移 4 个单位，再向上平移 6 个单位。请写出中间坐标和最终坐标。",
        blanks: [
          {
            id: "middle",
            prompt: "第一次平移后的坐标",
            hint: "向左平移先减横坐标。",
            acceptableAnswers: ["(-3,-2)", "(-3, -2)"],
            placeholder: "请填写坐标",
          },
          {
            id: "final",
            prompt: "最终坐标",
            hint: "再把纵坐标加 6。",
            acceptableAnswers: ["(-3,4)", "(-3, 4)"],
            placeholder: "请填写坐标",
          },
        ],
        explanation: "先左移得 (-3, -2)，再上移得 (-3, 4)。",
        relatedLessonIds: ["lesson-g7x3-coordinate-plane"],
      },
      {
        id: "q8",
        quizId: "quiz-g7-xia-unit-3",
        type: "single-choice",
        difficulty: "challenge",
        stem: "点 A(2, 1)、B(2, 5)、C(-1, 1) 中，和点 A 在同一条竖直直线上的点是哪一个？",
        options: [
          { id: "a", label: "A", content: "B" },
          { id: "b", label: "B", content: "C" },
          { id: "c", label: "C", content: "B 和 C" },
          { id: "d", label: "D", content: "都不是" },
        ],
        correctOptionId: "a",
        explanation: "同一条竖直直线上的点横坐标相同，A 和 B 的横坐标都为 2。",
        relatedLessonIds: ["lesson-g7x3-coordinate-plane"],
      },
      {
        id: "q9",
        quizId: "quiz-g7-xia-unit-3",
        type: "fill-blank",
        difficulty: "challenge",
        stem: "已知点 P(x, y) 满足 x + y = 3，且横坐标比纵坐标大 1。请分别求 x 和 y。",
        blanks: [
          {
            id: "x",
            prompt: "x 的值",
            hint: "可把“横坐标比纵坐标大 1”写成 x = y + 1。",
            acceptableAnswers: ["2"],
            placeholder: "请填写结果",
          },
          {
            id: "y",
            prompt: "y 的值",
            hint: "把 x = y + 1 代入 x + y = 3。",
            acceptableAnswers: ["1"],
            placeholder: "请填写结果",
          },
        ],
        explanation: "由 x = y + 1，代入 x + y = 3 得 y + 1 + y = 3，所以 y = 1，x = 2。",
        relatedLessonIds: ["lesson-g7x3-ordered-pair", "lesson-g7x3-coordinate-plane"],
      },
      {
        id: "q10",
        quizId: "quiz-g7-xia-unit-3",
        type: "fill-blank",
        difficulty: "challenge",
        stem: "三角形三个顶点分别是 A(0, 0)、B(4, 0)、C(4, 3)。若将整个三角形向左平移 2 个单位、再向上平移 1 个单位，请写出点 C 的最终坐标，并判断平移前后 BC 的长度是否改变。",
        blanks: [
          {
            id: "c-final",
            prompt: "点 C 的最终坐标",
            hint: "先改横坐标，再改纵坐标。",
            acceptableAnswers: ["(2,4)", "(2, 4)"],
            placeholder: "请填写坐标",
          },
          {
            id: "length",
            prompt: "BC 的长度是否改变",
            hint: "平移只改变位置，不改变图形大小。",
            acceptableAnswers: ["不变", "没有改变"],
            placeholder: "请填写判断",
          },
        ],
        explanation: "点 C(4, 3) 左移 2 个单位得 (2, 3)，再上移 1 个单位得 (2, 4)。平移不改变线段长度，所以 BC 长度不变。",
        relatedLessonIds: ["lesson-g7x3-coordinate-plane"],
      },
    ],
  },
};
