import type { CurriculumSlice } from "@/types/content";

export const g7XiaUnit6Slice: CurriculumSlice = {
  grade: {
    id: "g7",
    label: "七年级",
    shortLabel: "七下",
    description: "从图形关系、方程模型到统计意识，继续搭建初中数学的基础骨架。",
  },
  volume: {
    id: "xia",
    gradeId: "g7",
    label: "下册",
    description: "以几何关系、坐标与方程思想为主线的进阶学习。",
  },
  chapter: {
    id: "g7-xia-unit-6",
    gradeId: "g7",
    volumeId: "xia",
    slug: "shu-ju-shou-ji-zheng-li-miao-shu",
    title: "第六章 数据的收集、整理与描述",
    summary: "理解数据的收集与表示方法，会用统计图表描述数据特征，并能做简单的对比与推断。",
    order: 6,
    lessonIds: ["lesson-g7x6-data-collection", "lesson-g7x6-charts-and-description"],
    workedExampleIds: ["example-g7x6-table-to-chart", "example-g7x6-compare-distribution"],
    quizId: "quiz-g7-xia-unit-6",
  },
  lessons: [
    {
      id: "lesson-g7x6-data-collection",
      chapterId: "g7-xia-unit-6",
      slug: "shu-ju-shou-ji",
      title: "数据的收集与整理",
      summary: "理解抽样、调查与统计表，能根据问题设计简单的数据收集方式并完成整理。",
      learningObjectives: [
        "知道全面调查与抽样调查的区别。",
        "会把原始数据整理成统计表。",
        "能判断不同调查方式可能带来的偏差。",
      ],
      keyRules: [
        "全面调查对全体对象调查，抽样调查只调查一部分样本。",
        "样本要具有代表性，否则结论可能失真。",
        "整理数据时要明确单位、范围和分类标准。",
      ],
      bodyBlocks: [
        {
          type: "richText",
          id: "g7x6-collect-context",
          title: "统计的第一步是“问对问题”",
          content: [
            "统计不是画图而已，关键是：你想用数据回答什么问题？",
            "如果调查对象或统计口径不一致，后面再漂亮的图也没有意义。",
          ],
        },
        {
          type: "formula",
          id: "g7x6-collect-formula",
          title: "常见口径",
          formulas: ["样本数 n", "频数", "频率 = 频数 / 样本数"],
          note: "先统一口径，再谈比较。",
        },
        {
          type: "tip",
          id: "g7x6-collect-tip",
          title: "易错提醒",
          content: "把“抽样调查”当成“随便抽几个”会导致偏差；抽样要尽量随机且覆盖整体。",
        },
      ],
      relatedExampleIds: ["example-g7x6-table-to-chart"],
      order: 1,
      videoPlaceholder: {
        title: "板书微课：统计为什么会有偏差",
        durationLabel: "5 分钟",
        description: "用样本代表性理解统计结论的可靠性。",
      },
    },
    {
      id: "lesson-g7x6-charts-and-description",
      chapterId: "g7-xia-unit-6",
      slug: "tong-ji-tu-biao-yu-miao-shu",
      title: "统计图表与数据描述",
      summary: "掌握条形图、折线图、扇形图的适用场景，会根据图表作出描述与简单推断。",
      learningObjectives: [
        "会选择合适的统计图表示数据。",
        "能从图表中读出关键信息并进行对比。",
        "会用“趋势、占比、差异”三类语言描述数据。",
      ],
      keyRules: [
        "条形图适合比较不同类别数量。",
        "折线图适合反映随时间变化的趋势。",
        "扇形图适合反映各部分占总体的比例。",
      ],
      bodyBlocks: [
        {
          type: "richText",
          id: "g7x6-chart-context",
          title: "读图先看“轴、单位、总量”",
          content: [
            "读统计图先看横纵轴表示什么、单位是什么、总量是多少。",
            "再看变化趋势或类别差异，最后才能做推断。",
          ],
        },
        {
          type: "formula",
          id: "g7x6-chart-formula",
          title: "常见描述句式",
          formulas: ["A 类比 B 类多 5 人", "某阶段呈上升趋势", "C 占总体的 25%"],
          note: "描述要有比较对象和数字依据。",
        },
        {
          type: "tip",
          id: "g7x6-chart-tip",
          title: "易错提醒",
          content: "扇形图比较大小要看比例，不要只看“图形看起来大”。",
        },
      ],
      relatedExampleIds: ["example-g7x6-compare-distribution"],
      order: 2,
      videoPlaceholder: {
        title: "板书微课：一张图怎么读出趋势和差异",
        durationLabel: "6 分钟",
        description: "从轴、单位、总量到结论，建立读图流程。",
      },
    },
  ],
  workedExamples: [
    {
      id: "example-g7x6-table-to-chart",
      chapterId: "g7-xia-unit-6",
      slug: "tong-ji-biao-zhuan-tong-ji-tu",
      title: "例题 1：从统计表到统计图",
      summary: "把分类数据整理成条形图，并用一句话描述差异。",
      problem: "某班喜欢的运动统计如下：篮球 12 人，足球 8 人，羽毛球 6 人。画条形图并说出人数最多的项目比人数最少的项目多多少人。",
      steps: [
        { id: "step-1", title: "画图准备", content: "横轴为项目，纵轴为人数，单位为人。" },
        { id: "step-2", title: "画条形图", content: "分别画出 12、8、6 的条形高度。" },
        { id: "step-3", title: "描述差异", content: "篮球人数最多，羽毛球人数最少，相差 12 - 6 = 6 人。" },
      ],
      answer: "篮球比羽毛球多 6 人",
      commonMistakes: ["纵轴单位没写清楚。", "只说“最多是篮球”，没给出差值。"],
      relatedLessonIds: ["lesson-g7x6-data-collection", "lesson-g7x6-charts-and-description"],
      order: 1,
    },
    {
      id: "example-g7x6-compare-distribution",
      chapterId: "g7-xia-unit-6",
      slug: "tong-ji-tu-bi-jiao",
      title: "例题 2：比较分布并作出推断",
      summary: "从比例和趋势角度描述数据差异，并说明推断依据。",
      problem: "某校两天的降雨量分别为 8mm 和 2mm。用折线图表示，并说明第二天降雨量比第一天减少了多少百分比。",
      steps: [
        { id: "step-1", title: "画折线图", content: "两天分别标点 (第1天, 8) 和 (第2天, 2)，连线表示趋势。" },
        { id: "step-2", title: "计算减少量", content: "减少了 8 - 2 = 6(mm)。" },
        { id: "step-3", title: "算减少百分比", content: "减少百分比为 6/8 = 75% 。" },
      ],
      answer: "减少了 75%",
      commonMistakes: ["把 6/2 当作百分比。", "忘记以第一天为基准计算减少百分比。"],
      relatedLessonIds: ["lesson-g7x6-charts-and-description"],
      order: 2,
    },
  ],
  quiz: {
    id: "quiz-g7-xia-unit-6",
    chapterId: "g7-xia-unit-6",
    title: "第六章单元小测",
    instructions:
      "共 10 题，基础 2 题、进阶 4 题、压轴 4 题，整体难度明显上调，更强调多步推理、信息提取与综合应用。",
    passingScore: 80,
    questions: [
      {
        id: "q1",
        quizId: "quiz-g7-xia-unit-6",
        type: "single-choice",
        difficulty: "basic",
        stem: "下列哪一种统计图最适合表示“某班各科成绩人数分布（各科的人数对比）”？",
        options: [
          { id: "a", label: "A", content: "条形图" },
          { id: "b", label: "B", content: "折线图" },
          { id: "c", label: "C", content: "散点图" },
          { id: "d", label: "D", content: "函数图像" },
        ],
        correctOptionId: "a",
        explanation: "条形图适合比较不同类别数量。",
        relatedLessonIds: ["lesson-g7x6-charts-and-description"],
      },
      {
        id: "q2",
        quizId: "quiz-g7-xia-unit-6",
        type: "single-choice",
        difficulty: "basic",
        stem: "抽样调查的关键要求是什么？",
        options: [
          { id: "a", label: "A", content: "样本越少越好" },
          { id: "b", label: "B", content: "样本要有代表性" },
          { id: "c", label: "C", content: "只调查成绩最好的一组" },
          { id: "d", label: "D", content: "只用扇形图表示结果" },
        ],
        correctOptionId: "b",
        explanation: "样本要具有代表性，否则结论可能失真。",
        relatedLessonIds: ["lesson-g7x6-data-collection"],
      },
      {
        id: "q3",
        quizId: "quiz-g7-xia-unit-6",
        type: "fill-blank",
        difficulty: "advanced",
        stem: "某班 40 人中有 10 人喜欢篮球。请填写篮球爱好者的频率，并写成百分数。",
        blanks: [
          {
            id: "freq",
            prompt: "频率",
            hint: "频率 = 频数 / 样本数。",
            acceptableAnswers: ["0.25"],
            placeholder: "请填写小数",
          },
          {
            id: "percent",
            prompt: "依据相关关系，百分数表示",
            hint: "先判断所用关系或方法，再把 0.25 转成百分数。",
            acceptableAnswers: ["25%"],
            placeholder: "请填写百分数",
          },
        ],
        explanation: "依据题目中的条件和相关性质，频率为 10/40 = 0.25，写成百分数为 25%。",
        relatedLessonIds: ["lesson-g7x6-data-collection"],
      },
      {
        id: "q4",
        quizId: "quiz-g7-xia-unit-6",
        type: "single-choice",
        difficulty: "advanced",
        stem: "某同学用扇形图表示“不同水果销量占比”。若苹果占 30%，梨占 20%，其余为香蕉。香蕉占比是多少？",
        options: [
          { id: "a", label: "A", content: "30%" },
          { id: "b", label: "B", content: "40%" },
          { id: "c", label: "C", content: "50%" },
          { id: "d", label: "D", content: "70%" },
        ],
        correctOptionId: "c",
        explanation: "总占比 100%，香蕉占 100% - 30% - 20% = 50%。",
        relatedLessonIds: ["lesson-g7x6-charts-and-description"],
      },
      {
        id: "q5",
        quizId: "quiz-g7-xia-unit-6",
        type: "fill-blank",
        difficulty: "advanced",
        stem: "某班 5 天跑步人数分别为 12、15、18、18、20。请填写从第 1 天到第 5 天的总增长量，以及第 3 天到第 5 天的平均每天增长量。",
        blanks: [
          {
            id: "total",
            prompt: "总增长量",
            hint: "用第 5 天减第 1 天。",
            acceptableAnswers: ["8"],
            placeholder: "请填写数值",
          },
          {
            id: "avg",
            prompt: "平均每天增长量",
            hint: "第 3 天到第 5 天跨了 2 天。",
            acceptableAnswers: ["1"],
            placeholder: "请填写数值",
          },
        ],
        explanation: "总增长量为 20 - 12 = 8；第 3 天到第 5 天为 (20 - 18)/2 = 1。",
        relatedLessonIds: ["lesson-g7x6-charts-and-description"],
      },
      {
        id: "q6",
        quizId: "quiz-g7-xia-unit-6",
        type: "single-choice",
        difficulty: "advanced",
        stem: "为了解“全校学生最常用的交通方式”，下列哪种抽样方式更合理？",
        options: [
          { id: "a", label: "A", content: "只调查一个年级" },
          { id: "b", label: "B", content: "只调查离学校最近的班" },
          { id: "c", label: "C", content: "随机抽取不同年级多个班" },
          { id: "d", label: "D", content: "只调查家离学校最远的同学" },
        ],
        correctOptionId: "c",
        explanation: "随机抽取不同年级多个班更能保证样本具有代表性。",
        relatedLessonIds: ["lesson-g7x6-data-collection"],
      },
      {
        id: "q7",
        quizId: "quiz-g7-xia-unit-6",
        type: "fill-blank",
        difficulty: "challenge",
        stem: "两组同学做“每天阅读时间”抽样：A 组只在图书馆门口随机问，B 组在校门口、食堂、操场分时段随机问。请填写更可能代表全校的组别，并写出理由关键词。",
        blanks: [
          {
            id: "group",
            prompt: "更合理的组别",
            hint: "看样本来源是否更广。",
            acceptableAnswers: ["B", "B组"],
            placeholder: "请填写 A 或 B",
          },
          {
            id: "reason",
            prompt: "理由关键词",
            hint: "一句话写“代表性”或“覆盖面”。",
            acceptableAnswers: ["代表性", "覆盖面", "更有代表性"],
            placeholder: "请填写关键词",
          },
        ],
        explanation: "B 组在不同地点和时段抽样，覆盖面更广，样本更有代表性。",
        relatedLessonIds: ["lesson-g7x6-data-collection"],
      },
      {
        id: "q8",
        quizId: "quiz-g7-xia-unit-6",
        type: "single-choice",
        difficulty: "challenge",
        stem: "某商店两周销量折线图显示：第 1 周每天销量基本稳定，第 2 周前半周上升后半周下降。下列描述最准确的是哪个？",
        options: [
          { id: "a", label: "A", content: "两周销量一直上升" },
          { id: "b", label: "B", content: "第 1 周波动更大" },
          { id: "c", label: "C", content: "第 2 周存在先升后降的趋势变化" },
          { id: "d", label: "D", content: "第 2 周比第 1 周每天都少" },
        ],
        correctOptionId: "c",
        explanation: "题干描述的趋势就是第 2 周先升后降，属于趋势变化。",
        relatedLessonIds: ["lesson-g7x6-charts-and-description"],
      },
      {
        id: "q9",
        quizId: "quiz-g7-xia-unit-6",
        type: "fill-blank",
        difficulty: "challenge",
        stem: "某班两次测验平均分分别为 72 和 78。请填写平均分提升了多少分，以及提升百分比（以第一次为基准，保留到 1%）。",
        blanks: [
          {
            id: "diff",
            prompt: "提升分数",
            hint: "用后一次减前一次。",
            acceptableAnswers: ["6"],
            placeholder: "请填写数值",
          },
          {
            id: "percent",
            prompt: "提升百分比",
            hint: "6/72 转成百分数。",
            acceptableAnswers: ["8%", "8% ", "8.3%", "8%"],
            placeholder: "请填写百分数",
          },
        ],
        explanation: "提升分数为 78 - 72 = 6；提升百分比为 6/72 ≈ 8.3%。",
        relatedLessonIds: ["lesson-g7x6-charts-and-description"],
      },
      {
        id: "q10",
        quizId: "quiz-g7-xia-unit-6",
        type: "fill-blank",
        difficulty: "challenge",
        stem: "某班身高数据按 5cm 分组统计：150-154 有 4 人，155-159 有 10 人，160-164 有 12 人，165-169 有 6 人。请填写人数最多的组别，并写出“160cm 以上（含 160）”占全班的比例。",
        blanks: [
          {
            id: "group",
            prompt: "人数最多的组别",
            hint: "直接找频数最大的一组。",
            acceptableAnswers: ["160-164", "160—164"],
            placeholder: "请填写区间",
          },
          {
            id: "ratio",
            prompt: "160cm 以上占比",
            hint: "先算 160-164 与 165-169 的总人数，再除以总人数。",
            acceptableAnswers: ["56%", "56.25%"],
            placeholder: "请填写百分数",
          },
        ],
        explanation: "最多的是 160-164 组。160 以上人数为 12 + 6 = 18，总人数 4 + 10 + 12 + 6 = 32，占比 18/32 = 56.25%（约 56%）。",
        relatedLessonIds: ["lesson-g7x6-data-collection", "lesson-g7x6-charts-and-description"],
      },
    ],
  },
};
