import type { CurriculumSlice } from "@/types/content";
import { createNumberLineFigure } from "./quiz-figures";

export const g7XiaUnit5Slice: CurriculumSlice = {
  grade: {
    id: "g7",
    label: "七年级",
    shortLabel: "七下",
    description: "从图形关系、方程模型到统计意识，继续搭建初中数学的基础骨架。",
  },
  volume: {
    id: "xia",
    gradeId: "g7",
    label: "下册",
    description: "以几何关系、坐标与方程思想为主线的进阶学习。",
  },
  chapter: {
    id: "g7-xia-unit-5",
    gradeId: "g7",
    volumeId: "xia",
    slug: "yi-yuan-yi-ci-bu-deng-shi",
    title: "第五章 一元一次不等式与一元一次不等式组",
    summary: "理解不等式的意义，会解一元一次不等式和简单不等式组，并能在数轴上表示解集。",
    order: 5,
    lessonIds: ["lesson-g7x5-inequality-meaning", "lesson-g7x5-solve-inequality"],
    workedExampleIds: ["example-g7x5-solve", "example-g7x5-system"],
    quizId: "quiz-g7-xia-unit-5",
  },
  lessons: [
    {
      id: "lesson-g7x5-inequality-meaning",
      chapterId: "g7-xia-unit-5",
      slug: "bu-deng-shi-de-yi-yi",
      title: "不等式与解集",
      summary: "理解不等式和不等式解集的含义，会在数轴上表示简单解集。",
      learningObjectives: [
        "知道不等式是表示大小关系的式子。",
        "理解不等式的解与解集。",
        "会在数轴上表示 x>a、x≤b 这类简单解集。",
      ],
      keyRules: [
        "能使不等式成立的未知数的值叫做不等式的解。",
        "一个不等式的所有解组成这个不等式的解集。",
        "数轴表示时，空心点表示不包含端点，实心点表示包含端点。",
      ],
      bodyBlocks: [
        {
          type: "richText",
          id: "g7x5-meaning-context",
          title: "从“一个解”到“所有解”",
          content: [
            "方程通常找一个或几个确定解，而不等式更常见的是一段范围。",
            "所以学不等式时要特别注意：最后写的往往不是一个数，而是一类满足条件的数。",
          ],
        },
        {
          type: "formula",
          id: "g7x5-meaning-formula",
          title: "常见写法",
          formulas: ["x > 3", "x ≤ -1", "-2 < x ≤ 4"],
          note: "写解集时既要注意不等号方向，也要注意端点是否取到。",
        },
        {
          type: "tip",
          id: "g7x5-meaning-tip",
          title: "易错提醒",
          content: "“大于”与“大于等于”在数轴上的端点表示不同，不要混写。",
        },
      ],
      relatedExampleIds: ["example-g7x5-solve"],
      order: 1,
      videoPlaceholder: {
        title: "板书微课：不等式的解为什么是一段范围",
        durationLabel: "4 分钟",
        description: "从数轴角度理解不等式的解集。",
        src: "/videos/chapter-videos/g7-xia-unit-5-yi-yuan-yi-ci-bu-deng-shi.mp4",
        posterSrc: "/videos/chapter-videos/g7-xia-unit-5-yi-yuan-yi-ci-bu-deng-shi.jpg",
        status: "rendered",
      },
    },
    {
      id: "lesson-g7x5-solve-inequality",
      chapterId: "g7-xia-unit-5",
      slug: "jie-bu-deng-shi-yu-bu-deng-shi-zu",
      title: "解一元一次不等式与不等式组",
      summary: "掌握移项、合并同类项、去括号等基本方法，会解简单一元一次不等式组。",
      learningObjectives: [
        "会解形如 ax+b>c 的一元一次不等式。",
        "知道不等式两边同乘或同除以负数时要变号。",
        "会通过数轴或公共范围求一元一次不等式组的解集。",
      ],
      keyRules: [
        "移项、合并同类项的思想与解方程相似。",
        "不等式两边同乘或同除以同一个负数时，不等号方向要改变。",
        "不等式组的解集是每个不等式解集的公共部分。",
      ],
      bodyBlocks: [
        {
          type: "richText",
          id: "g7x5-solve-context",
          title: "最容易错在“变号”",
          content: [
            "解不等式前半段和方程很像，但当需要除以负数时，不等号方向必须改变。",
            "不等式组则要把两个范围放到一起看，最终留下公共部分。",
          ],
        },
        {
          type: "formula",
          id: "g7x5-solve-formula",
          title: "关键规则",
          formulas: ["-2x > 6 ⇒ x < -3", "x > 1 且 x ≤ 4 ⇒ 1 < x ≤ 4"],
          note: "看到负系数时，先警惕不等号是否要反向。",
        },
        {
          type: "tip",
          id: "g7x5-solve-tip",
          title: "易错提醒",
          content: "求不等式组解集时不要把两个范围并在一起，而要取公共部分。",
        },
      ],
      relatedExampleIds: ["example-g7x5-solve", "example-g7x5-system"],
      order: 2,
      videoPlaceholder: {
        title: "板书微课：解不等式组的公共部分怎么看",
        durationLabel: "6 分钟",
        description: "用数轴对照不等式组的解集。",
        src: "/videos/chapter-videos/g7-xia-unit-5-yi-yuan-yi-ci-bu-deng-shi.mp4",
        posterSrc: "/videos/chapter-videos/g7-xia-unit-5-yi-yuan-yi-ci-bu-deng-shi.jpg",
        status: "rendered",
      },
    },
  ],
  workedExamples: [
    {
      id: "example-g7x5-solve",
      chapterId: "g7-xia-unit-5",
      slug: "jie-yi-yuan-yi-ci-bu-deng-shi",
      title: "例题 1：解一元一次不等式",
      summary: "用移项和除法求出不等式的解集。",
      problem: "解不等式 3x - 5 > 7，并在数轴上表示解集。",
      steps: [
        { id: "step-1", title: "先移项", content: "把 -5 移到右边，得 3x > 12。" },
        { id: "step-2", title: "再除以 3", content: "两边同除以 3，得 x > 4。" },
        { id: "step-3", title: "表示解集", content: "在数轴上 4 处画空心点，向右画射线。" },
      ],
      answer: "x > 4",
      commonMistakes: ["把空心点画成实心点。", "只写 x=4，没有写范围。"],
      relatedLessonIds: ["lesson-g7x5-inequality-meaning", "lesson-g7x5-solve-inequality"],
      order: 1,
    },
    {
      id: "example-g7x5-system",
      chapterId: "g7-xia-unit-5",
      slug: "jie-yi-yuan-yi-ci-bu-deng-shi-zu",
      title: "例题 2：解一元一次不等式组",
      summary: "分别求解，再取公共部分。",
      problem: "解不等式组 x > -1，x ≤ 3。",
      steps: [
        { id: "step-1", title: "分别看两个范围", content: "第一个不等式表示 x 在 -1 右侧，第二个表示 x 不超过 3。" },
        { id: "step-2", title: "找公共部分", content: "同时满足两个条件的数位于 -1 和 3 之间，并且包含 3，不包含 -1。" },
        { id: "step-3", title: "写解集", content: "所以解集是 -1 < x ≤ 3。" },
      ],
      answer: "-1 < x ≤ 3",
      commonMistakes: ["把两个范围并起来写。", "把端点取值情况写错。"],
      relatedLessonIds: ["lesson-g7x5-solve-inequality"],
      order: 2,
    },
  ],
  quiz: {
    id: "quiz-g7-xia-unit-5",
    chapterId: "g7-xia-unit-5",
    title: "第五章单元小测",
    instructions:
      "共 10 题，基础 2 题、进阶 4 题、压轴 4 题，整体难度明显上调，更强调多步推理、信息提取与综合应用。",
    passingScore: 80,
    questions: [
      {
        id: "q1",
        quizId: "quiz-g7-xia-unit-5",
        type: "single-choice",
        difficulty: "basic",
        stem: "下列数中，哪个是不等式 x > 2 的一个解？",
        options: [
          { id: "a", label: "A", content: "1" },
          { id: "b", label: "B", content: "2" },
          { id: "c", label: "C", content: "3" },
          { id: "d", label: "D", content: "-1" },
        ],
        correctOptionId: "c",
        explanation: "只有 3 大于 2，满足不等式。",
        relatedLessonIds: ["lesson-g7x5-inequality-meaning"],
      },
      {
        id: "q2",
        quizId: "quiz-g7-xia-unit-5",
        type: "single-choice",
        difficulty: "basic",
        stem: "解集 x ≤ -2 在数轴上应如何表示？",
        options: [
          { id: "a", label: "A", content: "-2 处空心点，向右" },
          { id: "b", label: "B", content: "-2 处实心点，向左" },
          { id: "c", label: "C", content: "-2 处空心点，向左" },
          { id: "d", label: "D", content: "-2 处实心点，向右" },
        ],
        correctOptionId: "b",
        explanation: "“≤” 包含端点，要画实心点，且小于等于 -2 所以向左。",
        relatedLessonIds: ["lesson-g7x5-inequality-meaning"],
      },
      {
        id: "q3",
        quizId: "quiz-g7-xia-unit-5",
        type: "fill-blank",
        difficulty: "advanced",
        stem: "解不等式 2x + 3 > 9。请先写出去常数项后的结果，再写出最终解集。",
        blanks: [
          {
            id: "mid",
            prompt: "去常数项后的结果",
            hint: "把 3 移到右边。",
            acceptableAnswers: ["2x>6", "2x > 6"],
            placeholder: "请填写结果",
          },
          {
            id: "answer",
            prompt: "依据相关关系，最终解集",
            hint: "先判断所用关系或方法，再两边同除以 2。",
            acceptableAnswers: ["x>3", "x > 3"],
            placeholder: "请填写解集",
          },
        ],
        explanation: "依据题目中的条件和相关性质，移项得 2x > 6，两边同除以 2，得 x > 3。",
        relatedLessonIds: ["lesson-g7x5-solve-inequality"],
      },
      {
        id: "q4",
        quizId: "quiz-g7-xia-unit-5",
        type: "single-choice",
        difficulty: "advanced",
        stem: "解不等式 -3x < 12 时，不等号方向怎样变化？",
        options: [
          { id: "a", label: "A", content: "不变，解为 x < -4" },
          { id: "b", label: "B", content: "改变，解为 x > -4" },
          { id: "c", label: "C", content: "不变，解为 x > -4" },
          { id: "d", label: "D", content: "改变，解为 x < -4" },
        ],
        correctOptionId: "b",
        explanation: "两边同除以 -3 时，不等号要变向，所以 x > -4。",
        relatedLessonIds: ["lesson-g7x5-solve-inequality"],
      },
      {
        id: "q5",
        quizId: "quiz-g7-xia-unit-5",
        type: "fill-blank",
        difficulty: "advanced",
        stem: "已知不等式组 x > 1，x ≤ 5。请写出它的解集，并判断 5 是否是它的解。",
        blanks: [
          {
            id: "set",
            prompt: "解集",
            hint: "取两个范围的公共部分。",
            acceptableAnswers: ["1<x≤5", "1 < x ≤ 5"],
            placeholder: "请填写解集",
          },
          {
            id: "judge",
            prompt: "5 是否是它的解",
            hint: "检查 5 是否同时满足两个条件。",
            acceptableAnswers: ["是", "是的"],
            placeholder: "请填写判断",
          },
        ],
        explanation: "公共部分是 1 < x ≤ 5，因此 5 是这个不等式组的解。",
        relatedLessonIds: ["lesson-g7x5-solve-inequality"],
      },
      {
        id: "q6",
        quizId: "quiz-g7-xia-unit-5",
        type: "single-choice",
        difficulty: "advanced",
        stem: "若 a 是不等式 x - 4 < 0 的最大整数解，则 a 等于多少？",
        options: [
          { id: "a", label: "A", content: "3" },
          { id: "b", label: "B", content: "4" },
          { id: "c", label: "C", content: "-4" },
          { id: "d", label: "D", content: "0" },
        ],
        correctOptionId: "a",
        explanation: "不等式解为 x < 4，满足条件的最大整数是 3。",
        relatedLessonIds: ["lesson-g7x5-inequality-meaning", "lesson-g7x5-solve-inequality"],
      },
      {
        id: "q7",
        quizId: "quiz-g7-xia-unit-5",
        type: "fill-blank",
        difficulty: "challenge",
        stem: "在数轴上，点 P 表示不等式 x ≥ -2 的端点。请先写出解集，再写出满足该不等式的最小整数解。",
        figure: createNumberLineFigure("数轴上端点为 -2 的不等式示意图。", "-4", "-2", "3", "P"),
        blanks: [
          {
            id: "set",
            prompt: "解集",
            hint: "注意“≥”包含端点。",
            acceptableAnswers: ["x≥-2", "x ≥ -2"],
            placeholder: "请填写解集",
          },
          {
            id: "min-int",
            prompt: "最小整数解",
            hint: "看包含端点后的最小整数。",
            acceptableAnswers: ["-2"],
            placeholder: "请填写结果",
          },
        ],
        explanation: "解集是 x ≥ -2，因为包含端点，所以最小整数解就是 -2。",
        relatedLessonIds: ["lesson-g7x5-inequality-meaning"],
      },
      {
        id: "q8",
        quizId: "quiz-g7-xia-unit-5",
        type: "single-choice",
        difficulty: "challenge",
        stem: "不等式组 x > -1，x < 2 的整数解有多少个？",
        options: [
          { id: "a", label: "A", content: "1 个" },
          { id: "b", label: "B", content: "2 个" },
          { id: "c", label: "C", content: "3 个" },
          { id: "d", label: "D", content: "无数个" },
        ],
        correctOptionId: "b",
        explanation: "满足 -1 < x < 2 的整数只有 0 和 1，共 2 个。",
        relatedLessonIds: ["lesson-g7x5-solve-inequality"],
      },
      {
        id: "q9",
        quizId: "quiz-g7-xia-unit-5",
        type: "fill-blank",
        difficulty: "challenge",
        stem: "若 3x - 2 ≤ 10 且 x + 1 > 0，请先分别写出两个不等式的解，再写出不等式组的解集。",
        blanks: [
          {
            id: "first",
            prompt: "第一个不等式的解",
            hint: "先移项再除以 3。",
            acceptableAnswers: ["x≤4", "x ≤ 4"],
            placeholder: "请填写解集",
          },
          {
            id: "system",
            prompt: "不等式组的解集",
            hint: "第二个不等式解为 x > -1，取公共部分。",
            acceptableAnswers: ["-1<x≤4", "-1 < x ≤ 4"],
            placeholder: "请填写解集",
          },
        ],
        explanation: "3x - 2 ≤ 10 得 x ≤ 4；x + 1 > 0 得 x > -1，所以解集是 -1 < x ≤ 4。",
        relatedLessonIds: ["lesson-g7x5-solve-inequality"],
      },
      {
        id: "q10",
        quizId: "quiz-g7-xia-unit-5",
        type: "fill-blank",
        difficulty: "challenge",
        stem: "某班准备用不超过 60 元的班费购买笔记本，每本 7 元。若已买 3 本，设还能再买 x 本。请先列出不等式，再写出 x 的最大整数值。",
        blanks: [
          {
            id: "ineq",
            prompt: "不等式",
            hint: "总费用不能超过 60 元。",
            acceptableAnswers: ["7(x+3)≤60", "7(x + 3) ≤ 60"],
            placeholder: "请填写不等式",
          },
          {
            id: "max",
            prompt: "x 的最大整数值",
            hint: "解出 x 的范围后，再取最大整数。",
            acceptableAnswers: ["5"],
            placeholder: "请填写结果",
          },
        ],
        explanation: "由 7(x + 3) ≤ 60，得 x + 3 ≤ 60/7，即 x ≤ 39/7，约等于 5.57，所以最大整数值是 5。",
        relatedLessonIds: ["lesson-g7x5-solve-inequality"],
      },
    ],
  },
};
