import type { CurriculumSlice } from "@/types/content";
import { createNumberLineFigure } from "./quiz-figures";

export const g7XiaUnit2Slice: CurriculumSlice = {
  grade: {
    id: "g7",
    label: "七年级",
    shortLabel: "七下",
    description: "从图形关系、方程模型到统计意识，继续搭建初中数学的基础骨架。",
  },
  volume: {
    id: "xia",
    gradeId: "g7",
    label: "下册",
    description: "以几何关系、坐标与方程思想为主线的进阶学习。",
  },
  chapter: {
    id: "g7-xia-unit-2",
    gradeId: "g7",
    volumeId: "xia",
    slug: "shi-shu",
    title: "第二章 实数",
    summary: "理解平方根、立方根与无理数，能在数轴上表示实数并解决简单计算与比较问题。",
    order: 2,
    lessonIds: ["lesson-g7x2-square-root", "lesson-g7x2-real-number"],
    workedExampleIds: ["example-g7x2-root-calc", "example-g7x2-compare-real"],
    quizId: "quiz-g7-xia-unit-2",
  },
  lessons: [
    {
      id: "lesson-g7x2-square-root",
      chapterId: "g7-xia-unit-2",
      slug: "ping-fang-gen-yu-li-fang-gen",
      title: "平方根与立方根",
      summary: "掌握平方根、算术平方根和立方根的意义，会进行基础求值与逆向判断。",
      learningObjectives: [
        "能区分平方根与算术平方根。",
        "会求完全平方数和完全立方数的平方根或立方根。",
        "会根据平方或立方关系反向找数。",
      ],
      keyRules: [
        "若 x² = a（a ≥ 0），则 x 叫做 a 的平方根。",
        "正数 a 的算术平方根记作 √a。",
        "若 x³ = a，则 x 叫做 a 的立方根，记作 ∛a。",
      ],
      bodyBlocks: [
        {
          type: "richText",
          id: "g7x2-square-root-context",
          title: "先看“谁平方后得到它”",
          content: [
            "求平方根时，不是只记住一个结果，而是要反问：什么数平方后等于这个数？",
            "算术平方根只取非负值，而平方根一般要写两个互为相反数的结果。",
          ],
        },
        {
          type: "formula",
          id: "g7x2-square-root-formula",
          title: "常见结果",
          formulas: ["√49 = 7", "49 的平方根是 ±7", "∛(-8) = -2"],
          note: "注意“平方根”和“算术平方根”的答案个数不一样。",
        },
        {
          type: "tip",
          id: "g7x2-square-root-tip",
          title: "易错提醒",
          content: "负数没有平方根，但可以有立方根，例如 ∛(-27) = -3。",
        },
      ],
      relatedExampleIds: ["example-g7x2-root-calc"],
      order: 1,
      videoPlaceholder: {
        title: "板书微课：平方根到底怎么想",
        durationLabel: "5 分钟",
        description: "用“逆运算”视角理解平方根与立方根。",
      },
    },
    {
      id: "lesson-g7x2-real-number",
      chapterId: "g7-xia-unit-2",
      slug: "shi-shu-yu-shu-zhou",
      title: "实数与数轴",
      summary: "认识无理数，理解实数都可以在数轴上表示，会比较大小并进行简单估算。",
      learningObjectives: [
        "知道有理数和无理数统称实数。",
        "会在数轴上判断实数的大致位置。",
        "会比较两个实数大小并进行区间估算。",
      ],
      keyRules: [
        "有限小数和无限循环小数都是有理数。",
        "无限不循环小数叫做无理数。",
        "所有实数都能在数轴上找到对应点。",
      ],
      bodyBlocks: [
        {
          type: "richText",
          id: "g7x2-real-context",
          title: "为什么要估算",
          content: [
            "像 √5 这样的数写不成有限小数，这时就需要借助平方关系先判断它落在哪两个整数之间。",
            "实数比较大小时，先看符号，再看位置，必要时用平方或近似值辅助判断。",
          ],
        },
        {
          type: "formula",
          id: "g7x2-real-formula",
          title: "区间判断",
          formulas: ["2² < 5 < 3²，所以 2 < √5 < 3", "1.4² = 1.96，1.5² = 2.25"],
          note: "估算时抓住相邻整数的平方，是最稳定的思路。",
        },
        {
          type: "tip",
          id: "g7x2-real-tip",
          title: "易错提醒",
          content: "√9 = 3 是有理数，不是无理数；并不是所有带根号的数都是无理数。",
        },
      ],
      relatedExampleIds: ["example-g7x2-compare-real"],
      order: 2,
      videoPlaceholder: {
        title: "板书微课：用数轴看实数",
        durationLabel: "5 分钟",
        description: "通过估算把根号数放到数轴上。",
      },
    },
  ],
  workedExamples: [
    {
      id: "example-g7x2-root-calc",
      chapterId: "g7-xia-unit-2",
      slug: "ping-fang-gen-ji-suan",
      title: "例题 1：平方根与立方根计算",
      summary: "区分题目要求的是平方根、算术平方根还是立方根。",
      problem: "分别求 64 的算术平方根、64 的平方根以及 -27 的立方根。",
      steps: [
        { id: "step-1", title: "算术平方根", content: "因为 8² = 64，且算术平方根取非负，所以 64 的算术平方根是 8。" },
        { id: "step-2", title: "平方根", content: "平方根要写两个结果，所以 64 的平方根是 ±8。" },
        { id: "step-3", title: "立方根", content: "因为 (-3)³ = -27，所以 -27 的立方根是 -3。" },
      ],
      answer: "8，±8，-3",
      commonMistakes: ["把平方根和算术平方根混为一谈。", "忘记负数也可以有立方根。"],
      relatedLessonIds: ["lesson-g7x2-square-root"],
      order: 1,
    },
    {
      id: "example-g7x2-compare-real",
      chapterId: "g7-xia-unit-2",
      slug: "shi-shu-bi-jiao-da-xiao",
      title: "例题 2：比较实数大小",
      summary: "利用区间估算比较根号数与整数或小数大小。",
      problem: "比较 √10 与 3.1 的大小。",
      steps: [
        { id: "step-1", title: "先估算 √10", content: "因为 3² = 9，4² = 16，所以 3 < √10 < 4。" },
        { id: "step-2", title: "继续缩小范围", content: "3.1² = 9.61，3.2² = 10.24，所以 3.1 < √10 < 3.2。" },
        { id: "step-3", title: "得出结论", content: "因此 √10 > 3.1。" },
      ],
      answer: "√10 > 3.1",
      commonMistakes: ["只用 3 和 4 比较，没有继续缩小范围。", "把 3.1² 算错。"],
      relatedLessonIds: ["lesson-g7x2-real-number"],
      order: 2,
    },
  ],
  quiz: {
    id: "quiz-g7-xia-unit-2",
    chapterId: "g7-xia-unit-2",
    title: "第二章单元小测",
    instructions:
      "共 10 题，基础 2 题、进阶 4 题、压轴 4 题，整体难度明显上调，更强调多步推理、信息提取与综合应用。",
    passingScore: 80,
    questions: [
      {
        id: "q1",
        quizId: "quiz-g7-xia-unit-2",
        type: "single-choice",
        difficulty: "basic",
        stem: "下列各数中，哪个是无理数？",
        options: [
          { id: "a", label: "A", content: "0.25" },
          { id: "b", label: "B", content: "√2" },
          { id: "c", label: "C", content: "-3" },
          { id: "d", label: "D", content: "1.333..." },
        ],
        correctOptionId: "b",
        explanation: "√2 是无限不循环小数，属于无理数。",
        relatedLessonIds: ["lesson-g7x2-real-number"],
      },
      {
        id: "q2",
        quizId: "quiz-g7-xia-unit-2",
        type: "single-choice",
        difficulty: "basic",
        stem: "64 的算术平方根是多少？",
        options: [
          { id: "a", label: "A", content: "8" },
          { id: "b", label: "B", content: "-8" },
          { id: "c", label: "C", content: "±8" },
          { id: "d", label: "D", content: "4" },
        ],
        correctOptionId: "a",
        explanation: "算术平方根只取非负值，所以是 8。",
        relatedLessonIds: ["lesson-g7x2-square-root"],
      },
      {
        id: "q3",
        quizId: "quiz-g7-xia-unit-2",
        type: "fill-blank",
        difficulty: "advanced",
        stem: "请完成两个填空：先写出 49 的平方根，再写出 -125 的立方根。",
        blanks: [
          {
            id: "sqrt",
            prompt: "49 的平方根",
            hint: "平方根一般要写两个互为相反数的结果。",
            acceptableAnswers: ["±7", "+7,-7", "-7,+7"],
            placeholder: "请填写结果",
          },
          {
            id: "cube",
            prompt: "依据相关关系，-125 的立方根",
            hint: "先判断所用关系或方法，再想一想哪个数立方后等于 -125。",
            acceptableAnswers: ["-5"],
            placeholder: "请填写结果",
          },
        ],
        explanation: "依据题目中的条件和相关性质，49 的平方根是 ±7；因为 (-5)³ = -125，所以 -125 的立方根是 -5。",
        relatedLessonIds: ["lesson-g7x2-square-root"],
      },
      {
        id: "q4",
        quizId: "quiz-g7-xia-unit-2",
        type: "fill-blank",
        difficulty: "advanced",
        stem: "已知 2² < 7 < 3²，请完成两个填空：先写出 √7 所在的整数区间，再写出它更接近 2 还是 3。",
        blanks: [
          {
            id: "interval",
            prompt: "√7 的整数区间",
            hint: "直接根据平方关系写成“2<√7<3”的形式。",
            acceptableAnswers: ["2<√7<3", "2＜√7＜3"],
            placeholder: "请填写不等式",
          },
          {
            id: "near",
            prompt: "√7 更接近的整数",
            hint: "可比较 7 与 2.5² 的大小，或直接估算。",
            acceptableAnswers: ["3"],
            placeholder: "请填写整数",
          },
        ],
        explanation: "因为 2² < 7 < 3²，所以 2 < √7 < 3；又因为 √7 约等于 2.65，更接近 3。",
        relatedLessonIds: ["lesson-g7x2-real-number"],
      },
      {
        id: "q5",
        quizId: "quiz-g7-xia-unit-2",
        type: "single-choice",
        difficulty: "advanced",
        stem: "若 a = √5，b = 2.3，则 a 与 b 的大小关系是哪个？",
        options: [
          { id: "a", label: "A", content: "a > b" },
          { id: "b", label: "B", content: "a = b" },
          { id: "c", label: "C", content: "a < b" },
          { id: "d", label: "D", content: "无法判断" },
        ],
        correctOptionId: "c",
        explanation: "√5 约等于 2.236，小于 2.3。",
        relatedLessonIds: ["lesson-g7x2-real-number"],
      },
      {
        id: "q6",
        quizId: "quiz-g7-xia-unit-2",
        type: "fill-blank",
        difficulty: "advanced",
        stem: "在数轴上，点 A 表示 -√9，点 B 表示 √16。请分别写出点 A、点 B 表示的数。",
        figure: createNumberLineFigure("数轴上标出 -√9 和 √16 的位置。", "-3", "0", "4", "A"),
        blanks: [
          {
            id: "a-value",
            prompt: "点 A 表示的数",
            hint: "-√9 先算根号，再带上前面的负号。",
            acceptableAnswers: ["-3"],
            placeholder: "请填写结果",
          },
          {
            id: "b-value",
            prompt: "点 B 表示的数",
            hint: "√16 是哪个正整数？",
            acceptableAnswers: ["4"],
            placeholder: "请填写结果",
          },
        ],
        explanation: "因为 √9 = 3，所以 -√9 = -3；因为 √16 = 4，所以点 B 表示 4。",
        relatedLessonIds: ["lesson-g7x2-square-root", "lesson-g7x2-real-number"],
      },
      {
        id: "q7",
        quizId: "quiz-g7-xia-unit-2",
        type: "single-choice",
        difficulty: "challenge",
        stem: "若 x 是 169 的平方根，y 是 27 的立方根，则 x + y 可能是多少？",
        options: [
          { id: "a", label: "A", content: "16" },
          { id: "b", label: "B", content: "-10" },
          { id: "c", label: "C", content: "10 或 -16" },
          { id: "d", label: "D", content: "16 或 -10" },
        ],
        correctOptionId: "d",
        explanation: "169 的平方根是 ±13，27 的立方根是 3，所以 x + y 可能是 16 或 -10。",
        relatedLessonIds: ["lesson-g7x2-square-root"],
      },
      {
        id: "q8",
        quizId: "quiz-g7-xia-unit-2",
        type: "fill-blank",
        difficulty: "challenge",
        stem: "若一个正数的平方根是 ±m，且 m = 6，那么这个正数是多少？再写出它的算术平方根。",
        blanks: [
          {
            id: "number",
            prompt: "这个正数",
            hint: "平方根是 ±6，说明原数是多少？",
            acceptableAnswers: ["36"],
            placeholder: "请填写结果",
          },
          {
            id: "arith",
            prompt: "它的算术平方根",
            hint: "算术平方根只取非负值。",
            acceptableAnswers: ["6"],
            placeholder: "请填写结果",
          },
        ],
        explanation: "因为一个数的平方根是 ±6，所以这个数是 36；它的算术平方根是 6。",
        relatedLessonIds: ["lesson-g7x2-square-root"],
      },
      {
        id: "q9",
        quizId: "quiz-g7-xia-unit-2",
        type: "single-choice",
        difficulty: "challenge",
        stem: "如果 1.7 < √a < 1.8，那么整数 a 可能是哪个？",
        options: [
          { id: "a", label: "A", content: "2" },
          { id: "b", label: "B", content: "3" },
          { id: "c", label: "C", content: "4" },
          { id: "d", label: "D", content: "5" },
        ],
        correctOptionId: "b",
        explanation: "两边平方得 2.89 < a < 3.24，满足的整数只有 3。",
        relatedLessonIds: ["lesson-g7x2-real-number"],
      },
      {
        id: "q10",
        quizId: "quiz-g7-xia-unit-2",
        type: "fill-blank",
        difficulty: "challenge",
        stem: "比较 √12 与 √27 - 2 的大小：先分别估算它们，再填写最终的不等号关系。",
        blanks: [
          {
            id: "left-est",
            prompt: "√12 的近似值（保留 1 位小数）",
            hint: "√12 介于 3 和 4 之间，更靠近 3.5。",
            acceptableAnswers: ["3.5", "3.4"],
            placeholder: "请填写近似值",
          },
          {
            id: "relation",
            prompt: "最终大小关系",
            hint: "√27 约为 5.2，所以 √27 - 2 约为 3.2。",
            acceptableAnswers: ["√12>√27-2", "√12 > √27 - 2"],
            placeholder: "请填写关系",
          },
        ],
        explanation: "√12 约为 3.46，√27 - 2 约为 5.20 - 2 = 3.20，所以 √12 > √27 - 2。",
        relatedLessonIds: ["lesson-g7x2-real-number"],
      },
    ],
  },
};
