import type { CurriculumSlice } from "@/types/content";
import {
  createCongruentTrianglesFigure,
  createTriangleFigure,
} from "./quiz-figures";

export const g8ShangUnit1Slice: CurriculumSlice = {
  grade: {
    id: "g8",
    label: "八年级",
    shortLabel: "八上",
    description: "从图形证明、代数运算与函数关系中提升推理能力。",
  },
  volume: {
    id: "shang",
    gradeId: "g8",
    label: "上册",
    description: "以三角形、整式乘法与勾股思想为重点的能力提升阶段。",
  },
  chapter: {
    id: "g8-shang-unit-1",
    gradeId: "g8",
    volumeId: "shang",
    slug: "quan-deng-san-jiao-xing",
    title: "第一章 全等三角形",
    summary:
      "理解全等三角形的概念与判定，会利用对应边、对应角相等解决长度和角度问题。",
    order: 1,
    lessonIds: [
      "lesson-g8s-congruent-concept",
      "lesson-g8s-congruent-criteria",
    ],
    workedExampleIds: [
      "example-g8s-identify-congruent",
      "example-g8s-solve-side-length",
    ],
    quizId: "quiz-g8-shang-unit-1",
    coverImage: {
      src: "/images/content/g8-shang-unit-1-cover.svg",
      alt: "第一章全等三角形封面示意图",
    },
  },
  lessons: [
    {
      id: "lesson-g8s-congruent-concept",
      chapterId: "g8-shang-unit-1",
      slug: "quan-deng-san-jiao-xing-de-gai-nian",
      title: "全等三角形的概念",
      summary: "认识全等三角形的含义，知道对应边、对应角分别相等。",
      learningObjectives: [
        "能说出什么是全等三角形。",
        "会根据顶点顺序找对应边与对应角。",
        "知道全等三角形的周长和面积分别相等。",
      ],
      keyRules: [
        "能够完全重合的两个三角形叫做全等三角形。",
        "全等三角形的对应边相等，对应角相等。",
        "书写全等时，顶点顺序要一一对应。",
      ],
      bodyBlocks: [
        {
          type: "richText",
          id: "g8s-context-1",
          title: "看懂“完全重合”",
          content: [
            "全等不是“差不多大”，而是能够通过平移、旋转、翻折后完全重合。",
            "一旦判断出两个三角形全等，就能立刻得到对应边、对应角都相等，这是后续证明和求值的重要跳板。",
          ],
        },
        {
          type: "formula",
          id: "g8s-formula-1",
          title: "记号与对应",
          formulas: [
            "△ABC ≌ △DEF",
            "AB = DE，BC = EF，AC = DF",
            "∠A = ∠D，∠B = ∠E，∠C = ∠F",
          ],
          note: "写全等符号时，顺序错了，对应关系也会跟着错。",
        },
        {
          type: "tip",
          id: "g8s-tip-1",
          title: "易错提醒",
          content: "面积相等的两个三角形不一定全等，全等要求形状和大小都一样。",
        },
      ],
      relatedExampleIds: ["example-g8s-identify-congruent"],
      order: 1,
      videoPlaceholder: {
        title: "板书微课：全等到底看什么",
        durationLabel: "4 分钟",
        description: "从“完全重合”和“对应关系”两个角度切入。",
      },
    },
    {
      id: "lesson-g8s-congruent-criteria",
      chapterId: "g8-shang-unit-1",
      slug: "quan-deng-san-jiao-xing-de-pan-ding",
      title: "全等三角形的判定",
      summary: "掌握 SSS、SAS、ASA 等常见判定思路，能据此求边求角。",
      learningObjectives: [
        "会区分常见的全等判定条件。",
        "能根据题目给出的边角条件选择合适判定方法。",
        "会在判定全等后继续求未知边或未知角。",
      ],
      keyRules: [
        "三边对应相等可以判定两个三角形全等。",
        "两边及其夹角对应相等可以判定两个三角形全等。",
        "两角及其夹边对应相等可以判定两个三角形全等。",
      ],
      bodyBlocks: [
        {
          type: "richText",
          id: "g8s-context-2",
          title: "先判断已知条件够不够",
          content: [
            "做判定题时，第一步不是急着写结论，而是先整理题目到底给了哪些边、哪些角。",
            "只有当条件恰好落在已学过的判定模板里，才能直接判定全等；否则还需要补充推理。",
          ],
        },
        {
          type: "formula",
          id: "g8s-formula-2",
          title: "常见判定模板",
          formulas: ["SSS", "SAS", "ASA", "AAS", "HL（直角三角形）"],
          note: "AAA 只能判定相似，不能判定全等。",
        },
        {
          type: "tip",
          id: "g8s-tip-2",
          title: "易错提醒",
          content: "两边和一个不夹角相等，一般不能直接判定全等。",
        },
      ],
      relatedExampleIds: ["example-g8s-solve-side-length"],
      order: 2,
      videoPlaceholder: {
        title: "板书微课：全等判定模板速记",
        durationLabel: "5 分钟",
        description: "用条件卡片快速判断该走哪种判定路线。",
      },
    },
  ],
  workedExamples: [
    {
      id: "example-g8s-identify-congruent",
      chapterId: "g8-shang-unit-1",
      slug: "pan-duan-dui-ying-guan-xi",
      title: "例题 1：判断对应关系",
      summary: "根据全等书写顺序找对应边和对应角。",
      problem: "已知 △ABC ≌ △DEF，写出与边 AC、角 B 对应的边和角。",
      steps: [
        {
          id: "step-1",
          title: "看顶点顺序",
          content: "由 △ABC ≌ △DEF 可知 A 对应 D，B 对应 E，C 对应 F。",
        },
        {
          id: "step-2",
          title: "找对应元素",
          content: "所以边 AC 对应边 DF，角 B 对应角 E。",
        },
        {
          id: "step-3",
          title: "写出答案",
          content: "对应边是 DF，对应角是 ∠E。",
        },
      ],
      answer: "DF，∠E",
      commonMistakes: [
        "忽略书写顺序，把 AC 错配成 EF。",
        "只记住全等，不去核对顶点对应关系。",
      ],
      relatedLessonIds: ["lesson-g8s-congruent-concept"],
      order: 1,
    },
    {
      id: "example-g8s-solve-side-length",
      chapterId: "g8-shang-unit-1",
      slug: "li-yong-quan-deng-qiu-bian",
      title: "例题 2：利用全等求边长",
      summary: "先判定全等，再由对应边相等求未知量。",
      problem: "已知在 △ABC 和 △DEF 中，AB = DE = 5，BC = EF = 7，∠B = ∠E，求证两三角形全等，并写出 AC 与 DF 的关系。",
      steps: [
        {
          id: "step-1",
          title: "整理条件",
          content: "已知两边分别相等，且夹角 ∠B = ∠E。",
        },
        {
          id: "step-2",
          title: "选择判定方法",
          content: "满足两边及其夹角对应相等，所以 △ABC ≌ △DEF。",
        },
        {
          id: "step-3",
          title: "推出结论",
          content: "全等后对应边相等，因此 AC = DF。",
        },
      ],
      answer: "△ABC ≌ △DEF，且 AC = DF",
      commonMistakes: [
        "把给出的角误当成非夹角，导致不会选择 SAS。",
        "判定出全等后，没有继续使用对应边相等求结论。",
      ],
      relatedLessonIds: ["lesson-g8s-congruent-criteria"],
      order: 2,
    },
  ],
  quiz: {
    id: "quiz-g8-shang-unit-1",
    chapterId: "g8-shang-unit-1",
    title: "第一章单元小测",
    instructions:
      "共 10 题，基础 2 题、进阶 4 题、压轴 4 题，整体难度明显上调，更强调多步推理、信息提取与综合应用。",
    passingScore: 80,
    questions: [
      {
        id: "q1",
        quizId: "quiz-g8-shang-unit-1",
        type: "single-choice",
        difficulty: "basic",
        stem: "能够完全重合的两个三角形叫做什么三角形？",
        options: [
          { id: "a", label: "A", content: "相似三角形" },
          { id: "b", label: "B", content: "全等三角形" },
          { id: "c", label: "C", content: "等腰三角形" },
          { id: "d", label: "D", content: "直角三角形" },
        ],
        correctOptionId: "b",
        explanation: "能完全重合的两个三角形叫做全等三角形。",
        relatedLessonIds: ["lesson-g8s-congruent-concept"],
        relatedExampleIds: ["example-g8s-identify-congruent"],
      },
      {
        id: "q2",
        quizId: "quiz-g8-shang-unit-1",
        type: "fill-blank",
        difficulty: "basic",
        stem: "观察图中的 △ABC 与 △DEF。若已知 △ABC ≌ △DEF，请填写 ∠B 的对应角，以及边 AC 的对应边。",
        figure: createCongruentTrianglesFigure(
          "全等三角形 ABC 与 DEF 的示意图，用于判断对应顶点和对应边。",
          {
            vertexLabels: ["A", "B", "C"],
            leftSide: "AB",
            rightSide: "BC",
            baseSide: "AC",
          },
          {
            vertexLabels: ["D", "E", "F"],
            leftSide: "DE",
            rightSide: "EF",
            baseSide: "DF",
          },
        ),
        blanks: [
          {
            id: "angle",
            prompt: "∠B 的对应角",
            hint: "按照全等书写顺序 A↔D、B↔E、C↔F，因此 ∠B 对应 ∠E。",
            acceptableAnswers: ["∠E"],
            placeholder: "请填写角名",
          },
          {
            id: "side",
            prompt: "与边 AC 对应的边",
            hint: "先找 A 和 C 分别对应的顶点，再写出对应边的两个字母。",
            acceptableAnswers: ["DF"],
            placeholder: "请填写边名",
          },
        ],
        explanation: "由 △ABC ≌ △DEF 的书写顺序可知，∠B 对应 ∠E，A 对应 D，C 对应 F，所以边 AC 对应 DF。",
        relatedLessonIds: ["lesson-g8s-congruent-concept"],
        relatedExampleIds: ["example-g8s-identify-congruent"],
      },
      {
        id: "q3",
        quizId: "quiz-g8-shang-unit-1",
        type: "fill-blank",
        difficulty: "advanced",
        stem: "已知 △ABC ≌ △DEF，且 ∠A = 58°，∠B = 47°。请先填写 ∠F 的度数，再说明求解所依据的对应关系。",
        blanks: [
          {
            id: "angle",
            prompt: "∠F 的度数",
            hint: "先在 △ABC 中求出第三个角，再利用全等对应关系。",
            acceptableAnswers: ["75°", "75"],
            placeholder: "请填写结果",
          },
          {
            id: "relation",
            prompt: "求解依据",
            hint: "先用三角形内角和，再用全等三角形对应角相等。",
            acceptableAnswers: ["∠C=∠F", "全等三角形对应角相等", "三角形内角和180°且全等对应角相等"],
            placeholder: "请填写依据",
          },
        ],
        explanation: "依据三角形内角和 180°，先求 ∠C = 75°；再由全等三角形对应角相等，得到 ∠F = 75°。",
        relatedLessonIds: ["lesson-g8s-congruent-concept"],
        relatedExampleIds: ["example-g8s-identify-congruent"],
      },
      {
        id: "q4",
        quizId: "quiz-g8-shang-unit-1",
        type: "single-choice",
        difficulty: "advanced",
        stem: "下列哪组条件可以直接判定两个三角形全等？",
        options: [
          { id: "a", label: "A", content: "三个角分别相等" },
          { id: "b", label: "B", content: "两边和夹角分别相等" },
          { id: "c", label: "C", content: "一个角和面积相等" },
          { id: "d", label: "D", content: "周长相等" },
        ],
        correctOptionId: "b",
        explanation: "两边及其夹角分别相等符合 SAS 判定，可以直接判定全等。",
        relatedLessonIds: ["lesson-g8s-congruent-criteria"],
        relatedExampleIds: ["example-g8s-solve-side-length"],
      },
      {
        id: "q5",
        quizId: "quiz-g8-shang-unit-1",
        type: "single-choice",
        difficulty: "advanced",
        stem: "若两个三角形三边分别相等，则可用哪一种方法判定全等？",
        options: [
          { id: "a", label: "A", content: "ASA" },
          { id: "b", label: "B", content: "SSS" },
          { id: "c", label: "C", content: "AAS" },
          { id: "d", label: "D", content: "AAA" },
        ],
        correctOptionId: "b",
        explanation: "三边分别相等时，用 SSS 判定两个三角形全等。",
        relatedLessonIds: ["lesson-g8s-congruent-criteria"],
        relatedExampleIds: ["example-g8s-solve-side-length"],
      },
      {
        id: "q6",
        quizId: "quiz-g8-shang-unit-1",
        type: "single-choice",
        difficulty: "advanced",
        stem: "已知 ∠A = ∠D，∠B = ∠E，AB = DE，则判定 △ABC 与 △DEF 全等最适合使用哪一类条件？",
        options: [
          { id: "a", label: "A", content: "ASA" },
          { id: "b", label: "B", content: "SSS" },
          { id: "c", label: "C", content: "SAS" },
          { id: "d", label: "D", content: "AAA" },
        ],
        correctOptionId: "a",
        explanation: "已知两个角和它们的夹边分别相等，符合 ASA 判定条件。",
        relatedLessonIds: ["lesson-g8s-congruent-criteria"],
        relatedExampleIds: ["example-g8s-solve-side-length"],
      },
      {
        id: "q7",
        quizId: "quiz-g8-shang-unit-1",
        type: "single-choice",
        difficulty: "challenge",
        stem: "已知 △ABC ≌ △DEF，AB = 6，BC = 8，AC = 10，则 DF 的长度是多少？",
        options: [
          { id: "a", label: "A", content: "6" },
          { id: "b", label: "B", content: "8" },
          { id: "c", label: "C", content: "10" },
          { id: "d", label: "D", content: "24" },
        ],
        correctOptionId: "c",
        explanation: "由书写顺序可知 AC 对应 DF，所以 DF = AC = 10。",
        relatedLessonIds: ["lesson-g8s-congruent-concept", "lesson-g8s-congruent-criteria"],
        relatedExampleIds: ["example-g8s-identify-congruent", "example-g8s-solve-side-length"],
      },
      {
        id: "q8",
        quizId: "quiz-g8-shang-unit-1",
        type: "single-choice",
        difficulty: "challenge",
        stem: "若两个三角形满足 AB = DE，AC = DF，且 ∠A = ∠D，那么下列结论正确的是哪个？",
        options: [
          { id: "a", label: "A", content: "一定不能判定全等" },
          { id: "b", label: "B", content: "可用 SAS 判定全等" },
          { id: "c", label: "C", content: "只能判定相似" },
          { id: "d", label: "D", content: "必须再知道面积相等" },
        ],
        correctOptionId: "b",
        explanation: "已知两边及其夹角分别相等，符合 SAS 判定条件，可以判定全等。",
        relatedLessonIds: ["lesson-g8s-congruent-criteria"],
        relatedExampleIds: ["example-g8s-solve-side-length"],
      },
      {
        id: "q9",
        quizId: "quiz-g8-shang-unit-1",
        type: "fill-blank",
        difficulty: "challenge",
        stem: "如图，若全等三角形中对应边 AB = 2x + 1，DE = 11，请先写出等式，再填写 x 的值。",
        figure: createCongruentTrianglesFigure(
          "全等三角形中 AB 标为 2x+1，DE 标为 11 的示意图。",
          {
            vertexLabels: ["A", "B", "C"],
            leftSide: "2x+1",
            rightSide: "7",
            baseSide: "10",
          },
          {
            vertexLabels: ["D", "E", "F"],
            leftSide: "11",
            rightSide: "7",
            baseSide: "10",
          },
        ),
        blanks: [
          {
            id: "equation",
            prompt: "对应边相等得到的等式",
            hint: "利用全等三角形对应边相等，把 AB 和 DE 写成等式。",
            acceptableAnswers: ["2x+1=11", "11=2x+1"],
            placeholder: "请填写等式",
          },
          {
            id: "value",
            prompt: "x 的值",
            hint: "先解出上面的等式，再填写 x 的具体数值。",
            acceptableAnswers: ["5"],
            placeholder: "请填写整数",
          },
        ],
        explanation: "全等三角形对应边相等，所以 AB = DE，即 2x + 1 = 11，解得 x = 5。",
        relatedLessonIds: ["lesson-g8s-congruent-concept", "lesson-g8s-congruent-criteria"],
        relatedExampleIds: ["example-g8s-solve-side-length"],
      },
      {
        id: "q10",
        quizId: "quiz-g8-shang-unit-1",
        type: "single-choice",
        difficulty: "challenge",
        stem: "若在两个直角三角形中，斜边分别相等，一条直角边也分别相等，则这两个三角形可以依据哪种方法判定全等？",
        options: [
          { id: "a", label: "A", content: "HL" },
          { id: "b", label: "B", content: "AAA" },
          { id: "c", label: "C", content: "只有面积法" },
          { id: "d", label: "D", content: "不能判定" },
        ],
        correctOptionId: "a",
        explanation: "直角三角形中，斜边和一条直角边分别相等，可用 HL 判定全等。",
        relatedLessonIds: ["lesson-g8s-congruent-criteria"],
        relatedExampleIds: ["example-g8s-solve-side-length"],
      },
    ],
  },
};
