import type { CurriculumSlice } from "@/types/content";

export const g8ShangUnit4Slice: CurriculumSlice = {
  grade: {
    id: "g8",
    label: "八年级",
    shortLabel: "八上",
    description: "从图形证明、代数运算与函数关系中提升推理能力。",
  },
  volume: {
    id: "shang",
    gradeId: "g8",
    label: "上册",
    description: "以三角形、代数运算与数量关系为主线的能力提升阶段。",
  },
  chapter: {
    id: "g8-shang-unit-4",
    gradeId: "g8",
    volumeId: "shang",
    slug: "fen-shi",
    title: "第四章 分式",
    summary: "理解分式及其有意义条件，会进行基本约分、通分与四则运算，并能解决简单应用问题。",
    order: 4,
    lessonIds: ["lesson-g8s4-rational-expression", "lesson-g8s4-fraction-operations"],
    workedExampleIds: ["example-g8s4-simplify", "example-g8s4-addition"],
    quizId: "quiz-g8-shang-unit-4",
  },
  lessons: [
    {
      id: "lesson-g8s4-rational-expression",
      chapterId: "g8-shang-unit-4",
      slug: "fen-shi-yu-you-yi-yi-tiao-jian",
      title: "分式与有意义条件",
      summary: "理解分式的概念与分母不为零的条件，会判断分式何时有意义。",
      learningObjectives: [
        "能识别分式。",
        "会求分式有意义的条件。",
        "能在化简前先排除分母为零的情况。",
      ],
      keyRules: [
        "形如 A/B 的式子，当 B 含有字母且 B≠0 时叫做分式。",
        "分式有意义的条件是分母不为 0。",
        "约分和化简都不能改变有意义条件。",
      ],
      bodyBlocks: [
        {
          type: "richText",
          id: "g8s4-meaning-context",
          title: "先看分母",
          content: [
            "做分式题的第一反应不是急着算，而是先看分母什么时候会出问题。",
            "很多错不是算错，而是忘了写或忽略有意义条件。",
          ],
        },
        {
          type: "formula",
          id: "g8s4-meaning-formula",
          title: "常见条件",
          formulas: ["x/(x-2) 有意义 ⇒ x≠2", "(x+1)/(x²-9) 有意义 ⇒ x≠±3"],
          note: "分母要整体看成一个式子。",
        },
      ],
      relatedExampleIds: ["example-g8s4-simplify"],
      order: 1,
      videoPlaceholder: {
        title: "板书微课：分式题为什么总要先看分母",
        durationLabel: "4 分钟",
        description: "把有意义条件放到第一步来处理。",
      },
    },
    {
      id: "lesson-g8s4-fraction-operations",
      chapterId: "g8-shang-unit-4",
      slug: "fen-shi-yun-suan",
      title: "分式的约分与运算",
      summary: "掌握分式约分、通分以及加减乘除的基本方法。",
      learningObjectives: [
        "会对分式进行约分。",
        "会进行分式加减乘除。",
        "能在通分时正确找最简公分母。",
      ],
      keyRules: [
        "分式乘法：分子乘分子，分母乘分母。",
        "分式除法：除以一个分式，等于乘它的倒数。",
        "分式加减要先通分。",
      ],
      bodyBlocks: [
        {
          type: "richText",
          id: "g8s4-op-context",
          title: "运算顺序要清晰",
          content: [
            "分式运算中最容易乱的是：该先约分还是先通分、该不该直接相加。",
            "乘除看约分，加减先通分，这是最稳的判断顺序。",
          ],
        },
        {
          type: "formula",
          id: "g8s4-op-formula",
          title: "常见形式",
          formulas: ["a/b · c/d = ac/bd", "a/b ÷ c/d = ad/bc", "1/x + 1/y = (x+y)/xy"],
          note: "最后结果一般要化成最简分式。",
        },
      ],
      relatedExampleIds: ["example-g8s4-addition"],
      order: 2,
      videoPlaceholder: {
        title: "板书微课：分式加减乘除怎么不混",
        durationLabel: "6 分钟",
        description: "用统一顺序处理分式运算。",
      },
    },
  ],
  workedExamples: [
    {
      id: "example-g8s4-simplify",
      chapterId: "g8-shang-unit-4",
      slug: "fen-shi-hua-jian",
      title: "例题 1：分式化简",
      summary: "先找分式有意义条件，再进行约分。",
      problem: "化简 (x²-4)/(x²+2x)，并写出有意义条件。",
      steps: [
        { id: "step-1", title: "写条件", content: "分母 x²+2x = x(x+2) ≠ 0，所以 x≠0 且 x≠-2。" },
        { id: "step-2", title: "因式分解", content: "x²-4=(x-2)(x+2)，x²+2x=x(x+2)。" },
        { id: "step-3", title: "约分", content: "约去 (x+2)，得 (x-2)/x。" },
      ],
      answer: "(x-2)/x，且 x≠0,-2",
      commonMistakes: ["只化简，不写有意义条件。", "把 x+2 约掉后忘了原条件仍然保留。"],
      relatedLessonIds: ["lesson-g8s4-rational-expression", "lesson-g8s4-fraction-operations"],
      order: 1,
    },
    {
      id: "example-g8s4-addition",
      chapterId: "g8-shang-unit-4",
      slug: "fen-shi-jia-jian",
      title: "例题 2：分式加减",
      summary: "先通分，再合并分子。",
      problem: "计算 1/x + 2/(x+1)。",
      steps: [
        { id: "step-1", title: "找公分母", content: "最简公分母是 x(x+1)。" },
        { id: "step-2", title: "通分", content: "1/x = (x+1)/[x(x+1)]，2/(x+1) = 2x/[x(x+1)]。" },
        { id: "step-3", title: "合并分子", content: "结果为 (x+1+2x)/[x(x+1)] = (3x+1)/[x(x+1)]。" },
      ],
      answer: "(3x+1)/[x(x+1)]",
      commonMistakes: ["直接把分母相加。", "通分后分子没同步扩大。"],
      relatedLessonIds: ["lesson-g8s4-fraction-operations"],
      order: 2,
    },
  ],
  quiz: {
    id: "quiz-g8-shang-unit-4",
    chapterId: "g8-shang-unit-4",
    title: "第四章单元小测",
    instructions:
      "共 10 题，基础 2 题、进阶 4 题、压轴 4 题，整体难度明显上调，更强调多步推理、信息提取与综合应用。",
    passingScore: 80,
    questions: [
      { id: "q1", quizId: "quiz-g8-shang-unit-4", type: "single-choice", difficulty: "basic", stem: "分式 1/(x-3) 有意义时，x 不能取哪个值？", options: [{ id: "a", label: "A", content: "0" }, { id: "b", label: "B", content: "1" }, { id: "c", label: "C", content: "3" }, { id: "d", label: "D", content: "-3" }], correctOptionId: "c", explanation: "分母不能为 0，所以 x≠3。", relatedLessonIds: ["lesson-g8s4-rational-expression"] },
      { id: "q2", quizId: "quiz-g8-shang-unit-4", type: "single-choice", difficulty: "basic", stem: "下列运算正确的是哪个？", options: [{ id: "a", label: "A", content: "1/x+1/x=2/x" }, { id: "b", label: "B", content: "1/x+1/y=2/(x+y)" }, { id: "c", label: "C", content: "x/x=0" }, { id: "d", label: "D", content: "1/x·1/x=2/x²" }], correctOptionId: "a", explanation: "同分母分式相加，分子相加，得 2/x。", relatedLessonIds: ["lesson-g8s4-fraction-operations"] },
      { id: "q3", quizId: "quiz-g8-shang-unit-4", type: "fill-blank", difficulty: "advanced", stem: "请完成两个填空：先写出分式 (x+1)/(x²-1) 的有意义条件，再写出它化简后的结果。", blanks: [{ id: "cond", prompt: "有意义条件", hint: "x²-1=(x-1)(x+1) 不为 0。", acceptableAnswers: ["x≠1且x≠-1", "x≠±1", "x ≠ 1 且 x ≠ -1"], placeholder: "请填写条件" }, { id: "simple", prompt: "依据相关关系，化简结果", hint: "先判断所用关系或方法，再约去公因式前保留原条件。", acceptableAnswers: ["1/(x-1)", "1/(x - 1)"], placeholder: "请填写结果" }], explanation: "依据题目中的条件和相关性质，分母不能为 0，所以 x≠±1；约分后得 1/(x-1)。", relatedLessonIds: ["lesson-g8s4-rational-expression", "lesson-g8s4-fraction-operations"] },
      { id: "q4", quizId: "quiz-g8-shang-unit-4", type: "single-choice", difficulty: "advanced", stem: "计算 x/(x+1) ÷ 2/(x+1) 的结果是哪个？", options: [{ id: "a", label: "A", content: "x/2" }, { id: "b", label: "B", content: "2/x" }, { id: "c", label: "C", content: "x" }, { id: "d", label: "D", content: "(x+1)/2" }], correctOptionId: "a", explanation: "除以 2/(x+1) 等于乘 (x+1)/2，约分后得 x/2。", relatedLessonIds: ["lesson-g8s4-fraction-operations"] },
      { id: "q5", quizId: "quiz-g8-shang-unit-4", type: "fill-blank", difficulty: "advanced", stem: "计算 2/x - 1/x，并写出当 x=4 时该式的值。", blanks: [{ id: "simple", prompt: "化简结果", hint: "同分母直接相减。", acceptableAnswers: ["1/x"], placeholder: "请填写结果" }, { id: "value", prompt: "x=4 时的值", hint: "把 x=4 代入 1/x。", acceptableAnswers: ["1/4"], placeholder: "请填写结果" }], explanation: "2/x-1/x=1/x，代入 x=4 得 1/4。", relatedLessonIds: ["lesson-g8s4-fraction-operations"] },
      { id: "q6", quizId: "quiz-g8-shang-unit-4", type: "single-choice", difficulty: "advanced", stem: "若 a/b = 2/3，则 (2a)/(3b) 等于多少？", options: [{ id: "a", label: "A", content: "2/3" }, { id: "b", label: "B", content: "4/9" }, { id: "c", label: "C", content: "1" }, { id: "d", label: "D", content: "3/2" }], correctOptionId: "b", explanation: "(2a)/(3b)=(2/3)(a/b)=(2/3)(2/3)=4/9。", relatedLessonIds: ["lesson-g8s4-fraction-operations"] },
      { id: "q7", quizId: "quiz-g8-shang-unit-4", type: "fill-blank", difficulty: "challenge", stem: "已知 1/x = 2，1/y = 3，求 1/x + 1/y 与 (x+y)/(xy) 的值，并比较两者关系。", blanks: [{ id: "sum", prompt: "1/x + 1/y 的值", hint: "直接代入。", acceptableAnswers: ["5"], placeholder: "请填写结果" }, { id: "relation", prompt: "两者关系", hint: "利用恒等式 (x+y)/(xy)=1/x+1/y。", acceptableAnswers: ["相等", "二者相等"], placeholder: "请填写判断" }], explanation: "1/x+1/y=2+3=5，且 (x+y)/(xy)=1/x+1/y，所以二者相等。", relatedLessonIds: ["lesson-g8s4-fraction-operations"] },
      { id: "q8", quizId: "quiz-g8-shang-unit-4", type: "single-choice", difficulty: "challenge", stem: "若分式 (x²-9)/(x-3) 的值要等于 8，则 x 的值是多少？", options: [{ id: "a", label: "A", content: "5" }, { id: "b", label: "B", content: "3" }, { id: "c", label: "C", content: "-3" }, { id: "d", label: "D", content: "8" }], correctOptionId: "a", explanation: "x≠3，原式可化为 x+3，所以 x+3=8，得 x=5。", relatedLessonIds: ["lesson-g8s4-rational-expression", "lesson-g8s4-fraction-operations"] },
      { id: "q9", quizId: "quiz-g8-shang-unit-4", type: "fill-blank", difficulty: "challenge", stem: "某工程甲队单独完成需 x 天，乙队单独完成需 y 天。请写出两队合作一天完成的工作量，并在 x=3、y=6 时求其值。", blanks: [{ id: "form", prompt: "合作一天完成的工作量", hint: "工作效率相加。", acceptableAnswers: ["1/x+1/y", "1/x + 1/y"], placeholder: "请填写表达式" }, { id: "value", prompt: "x=3,y=6 时的值", hint: "代入后通分。", acceptableAnswers: ["1/2"], placeholder: "请填写结果" }], explanation: "合作效率为 1/x+1/y，代入得 1/3+1/6=1/2。", relatedLessonIds: ["lesson-g8s4-fraction-operations"] },
      { id: "q10", quizId: "quiz-g8-shang-unit-4", type: "fill-blank", difficulty: "challenge", stem: "若 A=(x+2)/(x-2)，B=(x-2)/(x+2)。请先求 AB，再写出当 x=4 时 A+B 的值。", blanks: [{ id: "product", prompt: "AB 的值", hint: "分子分母对应相乘后约分。", acceptableAnswers: ["1"], placeholder: "请填写结果" }, { id: "sum", prompt: "x=4 时 A+B 的值", hint: "先分别代入 A、B。", acceptableAnswers: ["10/3"], placeholder: "请填写结果" }], explanation: "AB=1；当 x=4 时，A=3，B=1/3，所以 A+B=10/3。", relatedLessonIds: ["lesson-g8s4-fraction-operations"] },
    ],
  },
};
