import type { CurriculumSlice } from "@/types/content";
import { createExpressionFigure } from "./quiz-figures";

export const g8ShangUnit3Slice: CurriculumSlice = {
  grade: {
    id: "g8",
    label: "八年级",
    shortLabel: "八上",
    description: "从图形证明、代数运算与函数关系中提升推理能力。",
  },
  volume: {
    id: "shang",
    gradeId: "g8",
    label: "上册",
    description: "以三角形、整式运算与代数化简为重点的能力提升阶段。",
  },
  chapter: {
    id: "g8-shang-unit-3",
    gradeId: "g8",
    volumeId: "shang",
    slug: "zheng-shi-de-cheng-fa-yu-yin-shi-fen-jie",
    title: "第三章 整式的乘法与因式分解",
    summary: "掌握幂的运算、整式乘法与常见因式分解方法，会利用结构化思维化简与求值。",
    order: 3,
    lessonIds: ["lesson-g8s3-monomial-polynomial", "lesson-g8s3-factorization"],
    workedExampleIds: ["example-g8s3-expand", "example-g8s3-factorize"],
    quizId: "quiz-g8-shang-unit-3",
  },
  lessons: [
    {
      id: "lesson-g8s3-monomial-polynomial",
      chapterId: "g8-shang-unit-3",
      slug: "zheng-shi-cheng-fa",
      title: "整式乘法",
      summary: "理解同底数幂、幂的乘方与单项式乘多项式，会按法则有序展开。",
      learningObjectives: [
        "会进行同底数幂乘法与幂的乘方运算。",
        "会进行单项式乘多项式、多项式乘多项式。",
        "能用分配律和结构化书写减少漏项。",
      ],
      keyRules: [
        "a^m · a^n = a^(m+n)",
        "(a^m)^n = a^(mn)",
        "单项式乘多项式要逐项相乘",
      ],
      bodyBlocks: [
        {
          type: "richText",
          id: "g8s3-mul-context",
          title: "整式乘法最怕漏项",
          content: [
            "遇到多项式乘法时，先确定每一项都要乘到，不要凭感觉一口气写完。",
            "幂的运算和整式乘法常常会叠在一起，需要先看结构再下手。",
          ],
        },
        {
          type: "formula",
          id: "g8s3-mul-formula",
          title: "常见形式",
          formulas: ["2x(x+3)=2x²+6x", "(x+2)(x+3)=x²+5x+6"],
          note: "展开后记得合并同类项。",
        },
        {
          type: "tip",
          id: "g8s3-mul-tip",
          title: "易错提醒",
          content: "多项式乘多项式时不要漏掉“中间项”，也不要把指数直接相乘。",
        },
      ],
      relatedExampleIds: ["example-g8s3-expand"],
      order: 1,
      videoPlaceholder: {
        title: "板书微课：整式乘法如何不漏项",
        durationLabel: "5 分钟",
        description: "用表格和分配律整理整式乘法。",
      },
    },
    {
      id: "lesson-g8s3-factorization",
      chapterId: "g8-shang-unit-3",
      slug: "yin-shi-fen-jie",
      title: "因式分解",
      summary: "掌握提公因式和公式法，会把多项式逆向转化为乘积形式。",
      learningObjectives: [
        "会提取公因式。",
        "会识别平方差和完全平方公式。",
        "能把因式分解与整式乘法互相转化。",
      ],
      keyRules: [
        "ab+ac=a(b+c)",
        "a²-b²=(a-b)(a+b)",
        "a²±2ab+b²=(a±b)²",
      ],
      bodyBlocks: [
        {
          type: "richText",
          id: "g8s3-fac-context",
          title: "因式分解是整式乘法的逆过程",
          content: [
            "做因式分解时，不是随便拆，而是要反问：这个式子是怎么乘出来的？",
            "先看能不能提公因式，再看是否符合公式结构，效率最高。",
          ],
        },
        {
          type: "formula",
          id: "g8s3-fac-formula",
          title: "常见拆法",
          formulas: ["3x²+6x=3x(x+2)", "x²-9=(x-3)(x+3)", "x²+6x+9=(x+3)²"],
          note: "拆分后可以反乘回去检验。",
        },
        {
          type: "tip",
          id: "g8s3-fac-tip",
          title: "易错提醒",
          content: "看到平方差时是两项，看到完全平方时是三项，不要把公式混用。",
        },
      ],
      relatedExampleIds: ["example-g8s3-factorize"],
      order: 2,
      videoPlaceholder: {
        title: "板书微课：因式分解的判断顺序",
        durationLabel: "6 分钟",
        description: "先公因式，后公式，建立固定思路。",
      },
    },
  ],
  workedExamples: [
    {
      id: "example-g8s3-expand",
      chapterId: "g8-shang-unit-3",
      slug: "zhan-kai-yu-he-bing",
      title: "例题 1：展开并化简",
      summary: "按顺序进行整式乘法并合并同类项。",
      problem: "化简 2x(x-3)+x(x+4)。",
      steps: [
        { id: "step-1", title: "分别展开", content: "2x(x-3)=2x²-6x，x(x+4)=x²+4x。" },
        { id: "step-2", title: "合并同类项", content: "2x²-6x+x²+4x=3x²-2x。" },
        { id: "step-3", title: "写结果", content: "化简结果为 3x²-2x。" },
      ],
      answer: "3x²-2x",
      commonMistakes: ["展开时漏乘某一项。", "合并同类项时符号看错。"],
      relatedLessonIds: ["lesson-g8s3-monomial-polynomial"],
      order: 1,
    },
    {
      id: "example-g8s3-factorize",
      chapterId: "g8-shang-unit-3",
      slug: "yin-shi-fen-jie-zong-he",
      title: "例题 2：因式分解",
      summary: "先提公因式，再识别平方差或完全平方结构。",
      problem: "分解因式 2x²-18。",
      steps: [
        { id: "step-1", title: "先提公因式", content: "2x²-18=2(x²-9)。" },
        { id: "step-2", title: "再看结构", content: "x²-9=x²-3²，是平方差。" },
        { id: "step-3", title: "完成分解", content: "所以 2x²-18=2(x-3)(x+3)。" },
      ],
      answer: "2(x-3)(x+3)",
      commonMistakes: ["直接套平方差，忘记先提公因式。", "平方差符号写错。"],
      relatedLessonIds: ["lesson-g8s3-factorization"],
      order: 2,
    },
  ],
  quiz: {
    id: "quiz-g8-shang-unit-3",
    chapterId: "g8-shang-unit-3",
    title: "第三章单元小测",
    instructions:
      "共 10 题，基础 2 题、进阶 4 题、压轴 4 题，整体难度明显上调，更强调多步推理、信息提取与综合应用。",
    passingScore: 80,
    questions: [
      {
        id: "q1",
        quizId: "quiz-g8-shang-unit-3",
        type: "single-choice",
        difficulty: "basic",
        stem: "计算 a²·a³ 的结果是哪个？",
        options: [
          { id: "a", label: "A", content: "a5" },
          { id: "b", label: "B", content: "a^6" },
          { id: "c", label: "C", content: "a^5" },
          { id: "d", label: "D", content: "2a^5" },
        ],
        correctOptionId: "c",
        explanation: "同底数幂相乘，指数相加，所以得 a^(2+3)=a^5。",
        relatedLessonIds: ["lesson-g8s3-monomial-polynomial"],
      },
      {
        id: "q2",
        quizId: "quiz-g8-shang-unit-3",
        type: "single-choice",
        difficulty: "basic",
        stem: "下列式子中，能用平方差公式分解的是哪个？",
        options: [
          { id: "a", label: "A", content: "x²+6x+9" },
          { id: "b", label: "B", content: "x²-16" },
          { id: "c", label: "C", content: "x²+4x" },
          { id: "d", label: "D", content: "x²+16" },
        ],
        correctOptionId: "b",
        explanation: "x²-16=x²-4²，符合平方差公式。",
        relatedLessonIds: ["lesson-g8s3-factorization"],
      },
      {
        id: "q3",
        quizId: "quiz-g8-shang-unit-3",
        type: "fill-blank",
        difficulty: "advanced",
        stem: "请完成两个填空：先展开 (x+2)(x-5)，再写出其中一次项的系数。",
        blanks: [
          {
            id: "expand",
            prompt: "展开结果",
            hint: "每一项都要分别相乘，再合并同类项。",
            acceptableAnswers: ["x^2-3x-10", "x²-3x-10", "x^2 - 3x - 10", "x² - 3x - 10"],
            placeholder: "请填写结果",
          },
          {
            id: "coef",
            prompt: "依据相关关系，一次项系数",
            hint: "先判断所用关系或方法，再展开后找到 x 项前面的系数。",
            acceptableAnswers: ["-3"],
            placeholder: "请填写结果",
          },
        ],
        explanation: "依据题目中的条件和相关性质，(x+2)(x-5)=x²-5x+2x-10=x²-3x-10，所以一次项系数是 -3。",
        relatedLessonIds: ["lesson-g8s3-monomial-polynomial"],
      },
      {
        id: "q4",
        quizId: "quiz-g8-shang-unit-3",
        type: "single-choice",
        difficulty: "advanced",
        stem: "把 3x²+12x 因式分解，正确的是哪个？",
        options: [
          { id: "a", label: "A", content: "3x(x+4)" },
          { id: "b", label: "B", content: "3(x²+4x)" },
          { id: "c", label: "C", content: "x(3x+12)" },
          { id: "d", label: "D", content: "3x²(1+4)" },
        ],
        correctOptionId: "a",
        explanation: "先提公因式 3x，得 3x(x+4)。",
        relatedLessonIds: ["lesson-g8s3-factorization"],
      },
      {
        id: "q5",
        quizId: "quiz-g8-shang-unit-3",
        type: "fill-blank",
        difficulty: "advanced",
        stem: "化简 2a(a+1)-a(3a-2)，先写出化简后的结果，再写出当 a=2 时的值。",
        blanks: [
          {
            id: "simplify",
            prompt: "化简结果",
            hint: "先展开，再合并同类项。",
            acceptableAnswers: ["-a^2+4a", "-a²+4a", "-a^2 + 4a", "-a² + 4a"],
            placeholder: "请填写结果",
          },
          {
            id: "value",
            prompt: "a=2 时的值",
            hint: "把 a=2 代入化简后的式子。",
            acceptableAnswers: ["4"],
            placeholder: "请填写结果",
          },
        ],
        explanation: "2a(a+1)-a(3a-2)=2a²+2a-3a²+2a=-a²+4a；当 a=2 时，值为 -4+8=4。",
        relatedLessonIds: ["lesson-g8s3-monomial-polynomial"],
      },
      {
        id: "q6",
        quizId: "quiz-g8-shang-unit-3",
        type: "single-choice",
        difficulty: "advanced",
        stem: "若 x+y=6，xy=8，则 (x+2)(y+2) 的值是多少？",
        options: [
          { id: "a", label: "A", content: "12" },
          { id: "b", label: "B", content: "20" },
          { id: "c", label: "C", content: "24" },
          { id: "d", label: "D", content: "28" },
        ],
        correctOptionId: "c",
        explanation: "(x+2)(y+2)=xy+2x+2y+4=8+2(x+y)+4=8+12+4=24。",
        relatedLessonIds: ["lesson-g8s3-monomial-polynomial"],
      },
      {
        id: "q7",
        quizId: "quiz-g8-shang-unit-3",
        type: "fill-blank",
        difficulty: "challenge",
        stem: "把 x²-10x+25 进行因式分解，再写出这个结果在 x=7 时的值。",
        blanks: [
          {
            id: "factor",
            prompt: "因式分解结果",
            hint: "看是否符合完全平方公式。",
            acceptableAnswers: ["(x-5)^2", "(x-5)²", "(x - 5)^2", "(x - 5)²"],
            placeholder: "请填写结果",
          },
          {
            id: "value",
            prompt: "x=7 时的值",
            hint: "代入因式分解后的式子更快。",
            acceptableAnswers: ["4"],
            placeholder: "请填写结果",
          },
        ],
        explanation: "x²-10x+25=(x-5)²，代入 x=7 得 (7-5)²=4。",
        relatedLessonIds: ["lesson-g8s3-factorization"],
      },
      {
        id: "q8",
        quizId: "quiz-g8-shang-unit-3",
        type: "single-choice",
        difficulty: "challenge",
        stem: "已知 2x²-8x 可以分解为 2x(x-4)。下列哪一步解释最合理？",
        options: [
          { id: "a", label: "A", content: "把 2 和 x² 分别提出" },
          { id: "b", label: "B", content: "把公共因式 2x 提出" },
          { id: "c", label: "C", content: "直接套用了平方差公式" },
          { id: "d", label: "D", content: "把指数各减 1" },
        ],
        correctOptionId: "b",
        explanation: "2x² 和 -8x 的公共因式是 2x，提出来后得 2x(x-4)。",
        relatedLessonIds: ["lesson-g8s3-factorization"],
      },
      {
        id: "q9",
        quizId: "quiz-g8-shang-unit-3",
        type: "fill-blank",
        difficulty: "challenge",
        stem: "如图，整式结构图表示 x(x+3)-2(x+3)。请先提取公因式，再写出结果在 x=5 时的值。",
        figure: createExpressionFigure("表达式 x(x+3)-2(x+3) 的结构图。", "x(x+3)-2(x+3)", "x(x+3)", "-2(x+3)", ""),
        blanks: [
          {
            id: "factor",
            prompt: "提公因式后的结果",
            hint: "两个部分都含有 (x+3)。",
            acceptableAnswers: ["(x+3)(x-2)", "(x - 2)(x + 3)"],
            placeholder: "请填写结果",
          },
          {
            id: "value",
            prompt: "x=5 时的值",
            hint: "代入分解后的式子更快。",
            acceptableAnswers: ["24"],
            placeholder: "请填写结果",
          },
        ],
        explanation: "原式=(x+3)(x-2)，当 x=5 时，值为 8×3=24。",
        relatedLessonIds: ["lesson-g8s3-factorization"],
      },
      {
        id: "q10",
        quizId: "quiz-g8-shang-unit-3",
        type: "fill-blank",
        difficulty: "challenge",
        stem: "若 A=x²+4x+4，B=x²-4，先分别因式分解 A 和 B，再写出 A-B 的化简结果。",
        blanks: [
          {
            id: "a-factor",
            prompt: "A 的因式分解",
            hint: "A 是完全平方。",
            acceptableAnswers: ["(x+2)^2", "(x+2)²", "(x + 2)^2", "(x + 2)²"],
            placeholder: "请填写结果",
          },
          {
            id: "diff",
            prompt: "A-B 的化简结果",
            hint: "先直接用原式相减再合并同类项。",
            acceptableAnswers: ["4x+8", "4x + 8"],
            placeholder: "请填写结果",
          },
        ],
        explanation: "A=(x+2)²，B=(x-2)(x+2)；A-B=(x²+4x+4)-(x²-4)=4x+8。",
        relatedLessonIds: ["lesson-g8s3-factorization"],
      },
    ],
  },
};
