import type { CurriculumSlice } from "@/types/content";
import { createTriangleFigure } from "./quiz-figures";

export const g8ShangUnit2Slice: CurriculumSlice = {
  grade: {
    id: "g8",
    label: "八年级",
    shortLabel: "八上",
    description: "从图形证明、代数运算与函数关系中提升推理能力。",
  },
  volume: {
    id: "shang",
    gradeId: "g8",
    label: "上册",
    description: "以三角形、整式乘法与勾股思想为重点的能力提升阶段。",
  },
  chapter: {
    id: "g8-shang-unit-2",
    gradeId: "g8",
    volumeId: "shang",
    slug: "zhou-dui-cheng",
    title: "第二章 轴对称",
    summary: "理解轴对称图形与线段垂直平分线的性质，会用对称关系解决距离、角度与作图问题。",
    order: 2,
    lessonIds: ["lesson-g8s2-axis-symmetry", "lesson-g8s2-perpendicular-bisector"],
    workedExampleIds: ["example-g8s2-find-symmetric-point", "example-g8s2-bisector-property"],
    quizId: "quiz-g8-shang-unit-2",
  },
  lessons: [
    {
      id: "lesson-g8s2-axis-symmetry",
      chapterId: "g8-shang-unit-2",
      slug: "zhou-dui-cheng-tu-xing",
      title: "轴对称图形与对称点",
      summary: "理解对称轴、对应点和对应线段的关系，会根据对称性判断长度和位置。",
      learningObjectives: [
        "能识别轴对称图形。",
        "会描述对称点到对称轴距离相等的性质。",
        "能利用对称关系判断线段和角的对应关系。",
      ],
      keyRules: [
        "轴对称图形沿某条直线折叠后两部分能够重合。",
        "对称点到对称轴的距离相等。",
        "连结一对对称点的线段被对称轴垂直平分。",
      ],
      bodyBlocks: [
        {
          type: "richText",
          id: "g8s2-axis-context",
          title: "看“垂直”和“平分”",
          content: [
            "判断对称时，不只看两边像不像，还要看对应点连线是否被对称轴垂直平分。",
            "一旦找到对称轴，就能立刻用“到轴距离相等”来求线段长度。",
          ],
        },
        {
          type: "formula",
          id: "g8s2-axis-formula",
          title: "核心关系",
          formulas: ["AP = A'P", "l ⟂ AA'", "P 为 AA' 中点"],
          note: "P 是对称轴与 AA' 的交点。",
        },
        {
          type: "tip",
          id: "g8s2-axis-tip",
          title: "易错提醒",
          content: "对称轴不是任意平分线，必须既平分又垂直。",
        },
      ],
      relatedExampleIds: ["example-g8s2-find-symmetric-point"],
      order: 1,
      videoPlaceholder: {
        title: "板书微课：轴对称一眼看准",
        durationLabel: "4 分钟",
        description: "从折叠和对应点两个角度理解轴对称。",
      },
    },
    {
      id: "lesson-g8s2-perpendicular-bisector",
      chapterId: "g8-shang-unit-2",
      slug: "xian-duan-chui-zhi-ping-fen-xian",
      title: "线段垂直平分线",
      summary: "掌握线段垂直平分线的性质与判定，会利用“到两端点距离相等”解决几何问题。",
      learningObjectives: [
        "知道垂直平分线上的点到线段两端点距离相等。",
        "会根据距离相等判定一个点在线段垂直平分线上。",
        "能把对称问题转化为垂直平分线问题。",
      ],
      keyRules: [
        "线段垂直平分线上的点到这条线段两个端点距离相等。",
        "到线段两个端点距离相等的点在线段的垂直平分线上。",
        "轴对称中的对称轴常常就是对应点连线的垂直平分线。",
      ],
      bodyBlocks: [
        {
          type: "richText",
          id: "g8s2-bisector-context",
          title: "把图形关系转成距离关系",
          content: [
            "很多题并不会直接告诉你‘垂直平分线’，而是给出两个距离相等的条件。",
            "这时要主动把‘PA = PB’看成‘P 在线段 AB 的垂直平分线上’来使用。",
          ],
        },
        {
          type: "formula",
          id: "g8s2-bisector-formula",
          title: "双向结论",
          formulas: ["P 在线段 AB 的垂直平分线上 ⇒ PA = PB", "PA = PB ⇒ P 在线段 AB 的垂直平分线上"],
          note: "用前先判断题目是性质还是判定。",
        },
        {
          type: "tip",
          id: "g8s2-bisector-tip",
          title: "易错提醒",
          content: "“到端点距离相等”是判定点的位置，不是直接说明线段长度相等。",
        },
      ],
      relatedExampleIds: ["example-g8s2-bisector-property"],
      order: 2,
      videoPlaceholder: {
        title: "板书微课：垂直平分线的双向结论",
        durationLabel: "5 分钟",
        description: "从性质到判定，整理一条完整思路链。",
      },
    },
  ],
  workedExamples: [
    {
      id: "example-g8s2-find-symmetric-point",
      chapterId: "g8-shang-unit-2",
      slug: "li-yong-dui-cheng-qiu-chang",
      title: "例题 1：利用对称求长",
      summary: "利用对称点到对称轴距离相等求未知线段。",
      problem: "点 A 与点 B 关于直线 l 对称，若点 A 到直线 l 的距离为 4 cm，求点 B 到直线 l 的距离，并说明 AB 与 l 的位置关系。",
      steps: [
        { id: "step-1", title: "用对称性质", content: "对称点到对称轴距离相等，所以点 B 到 l 的距离也是 4 cm。" },
        { id: "step-2", title: "看对应点连线", content: "对称点连线被对称轴垂直平分，所以 AB ⟂ l。" },
        { id: "step-3", title: "整理答案", content: "点 B 到 l 的距离为 4 cm，且 AB 被 l 垂直平分。" },
      ],
      answer: "4 cm，AB 被 l 垂直平分",
      commonMistakes: ["只答出距离相等，没有继续说明位置关系。", "把“垂直平分”误写成“平分但不垂直”。"],
      relatedLessonIds: ["lesson-g8s2-axis-symmetry"],
      order: 1,
    },
    {
      id: "example-g8s2-bisector-property",
      chapterId: "g8-shang-unit-2",
      slug: "chui-zhi-ping-fen-xian-pan-ding",
      title: "例题 2：用距离相等判定垂直平分线",
      summary: "把 PA = PB 转化成点 P 在线段 AB 的垂直平分线上。",
      problem: "在△ABC中，点 P 满足 PA = PB。若 AB = 6，且 P 到 A、B 的距离都为 5，说明 P 与线段 AB 的关系。",
      steps: [
        { id: "step-1", title: "抓住已知条件", content: "已知 PA = PB，说明点 P 到 A、B 两点距离相等。" },
        { id: "step-2", title: "使用判定", content: "根据判定定理，点 P 在线段 AB 的垂直平分线上。" },
        { id: "step-3", title: "得出结论", content: "P 所在位置已经被确定为 AB 的垂直平分线。" },
      ],
      answer: "点 P 在线段 AB 的垂直平分线上",
      commonMistakes: ["只看到等腰关系，没有转化为垂直平分线。", "误以为 PA = PB 能推出 AB = 5。"],
      relatedLessonIds: ["lesson-g8s2-perpendicular-bisector"],
      order: 2,
    },
  ],
  quiz: {
    id: "quiz-g8-shang-unit-2",
    chapterId: "g8-shang-unit-2",
    title: "第二章单元小测",
    instructions:
      "共 10 题，基础 2 题、进阶 4 题、压轴 4 题，整体难度明显上调，更强调多步推理、信息提取与综合应用。",
    passingScore: 80,
    questions: [
      {
        id: "q1",
        quizId: "quiz-g8-shang-unit-2",
        type: "single-choice",
        difficulty: "basic",
        stem: "下列说法正确的是哪个？",
        options: [
          { id: "a", label: "A", content: "轴对称图形只有一条对称轴" },
          { id: "b", label: "B", content: "对称点到对称轴的距离相等" },
          { id: "c", label: "C", content: "垂直平分线上的点到一个端点距离较短" },
          { id: "d", label: "D", content: "等边三角形不是轴对称图形" },
        ],
        correctOptionId: "b",
        explanation: "对称点到对称轴距离相等，这是轴对称的基本性质。",
        relatedLessonIds: ["lesson-g8s2-axis-symmetry"],
      },
      {
        id: "q2",
        quizId: "quiz-g8-shang-unit-2",
        type: "single-choice",
        difficulty: "basic",
        stem: "若点 P 在线段 AB 的垂直平分线上，则一定有哪个结论？",
        options: [
          { id: "a", label: "A", content: "PA = PB" },
          { id: "b", label: "B", content: "PA > PB" },
          { id: "c", label: "C", content: "PA < PB" },
          { id: "d", label: "D", content: "AB = PA" },
        ],
        correctOptionId: "a",
        explanation: "垂直平分线上的点到线段两个端点距离相等。",
        relatedLessonIds: ["lesson-g8s2-perpendicular-bisector"],
      },
      {
        id: "q3",
        quizId: "quiz-g8-shang-unit-2",
        type: "fill-blank",
        difficulty: "advanced",
        stem: "点 A 与点 A' 关于直线 l 对称。若 A 到 l 的距离是 3 cm，请填写 A' 到 l 的距离，并写出 l 与 AA' 的关系。",
        blanks: [
          {
            id: "distance",
            prompt: "A' 到 l 的距离",
            hint: "对称点到对称轴距离相等。",
            acceptableAnswers: ["3", "3cm", "3 cm"],
            placeholder: "请填写结果",
          },
          {
            id: "relation",
            prompt: "l 与 AA' 的关系",
            hint: "先判断所用关系或方法，再对称轴会垂直平分对称点连线。",
            acceptableAnswers: ["垂直平分", "垂直平分AA'", "l垂直平分AA'"],
            placeholder: "请填写关系",
          },
        ],
        explanation: "依据题目中的条件和相关性质，轴对称中，对称点到对称轴距离相等，且对称轴垂直平分对应点连线。",
        relatedLessonIds: ["lesson-g8s2-axis-symmetry"],
      },
      {
        id: "q4",
        quizId: "quiz-g8-shang-unit-2",
        type: "single-choice",
        difficulty: "advanced",
        stem: "已知点 P 满足 PA = PB，下列结论一定正确的是哪个？",
        options: [
          { id: "a", label: "A", content: "P 是 AB 的中点" },
          { id: "b", label: "B", content: "P 在线段 AB 上" },
          { id: "c", label: "C", content: "P 在线段 AB 的垂直平分线上" },
          { id: "d", label: "D", content: "P 与 A、B 三点共线" },
        ],
        correctOptionId: "c",
        explanation: "到 A、B 两点距离相等的点，在线段 AB 的垂直平分线上。",
        relatedLessonIds: ["lesson-g8s2-perpendicular-bisector"],
      },
      {
        id: "q5",
        quizId: "quiz-g8-shang-unit-2",
        type: "fill-blank",
        difficulty: "advanced",
        stem: "如图，在等腰三角形中 AB = AC = 5，BC = 6，顶点 A 到底边 BC 的垂足为 D。请填写 BD 的长度，并写出 AD 与 BC 的关系。",
        figure: createTriangleFigure("等腰三角形中两腰都为 5，底边为 6。", "5", "5", "6"),
        blanks: [
          {
            id: "bd",
            prompt: "BD 的长度",
            hint: "等腰三角形顶角平分线、底边中线和高重合，底边被平分。",
            acceptableAnswers: ["3"],
            placeholder: "请填写结果",
          },
          {
            id: "relation",
            prompt: "AD 与 BC 的关系",
            hint: "高与底边垂直。",
            acceptableAnswers: ["垂直", "AD⊥BC", "AD ⟂ BC"],
            placeholder: "请填写关系",
          },
        ],
        explanation: "等腰三角形顶点到底边的线段会平分底边，所以 BD = 3，且 AD ⟂ BC。",
        relatedLessonIds: ["lesson-g8s2-perpendicular-bisector"],
      },
      {
        id: "q6",
        quizId: "quiz-g8-shang-unit-2",
        type: "single-choice",
        difficulty: "advanced",
        stem: "点 P 在 AB 的垂直平分线上，且 AB = 8，PA = 6，则 PB 是多少？",
        options: [
          { id: "a", label: "A", content: "4" },
          { id: "b", label: "B", content: "6" },
          { id: "c", label: "C", content: "8" },
          { id: "d", label: "D", content: "14" },
        ],
        correctOptionId: "b",
        explanation: "垂直平分线上的点到 A、B 距离相等，所以 PB = PA = 6。",
        relatedLessonIds: ["lesson-g8s2-perpendicular-bisector"],
      },
      {
        id: "q7",
        quizId: "quiz-g8-shang-unit-2",
        type: "single-choice",
        difficulty: "challenge",
        stem: "在△ABC中，若点 P、Q 都满足 PA = PB，且 QA = QB，那么直线 PQ 与 AB 有什么关系？",
        options: [
          { id: "a", label: "A", content: "PQ ∥ AB" },
          { id: "b", label: "B", content: "PQ ⟂ AB" },
          { id: "c", label: "C", content: "PQ 与 AB 相交但不垂直" },
          { id: "d", label: "D", content: "无法判断" },
        ],
        correctOptionId: "b",
        explanation: "P、Q 都在线段 AB 的垂直平分线上，因此直线 PQ 就是这条垂直平分线，所以 PQ ⟂ AB。",
        relatedLessonIds: ["lesson-g8s2-perpendicular-bisector"],
      },
      {
        id: "q8",
        quizId: "quiz-g8-shang-unit-2",
        type: "fill-blank",
        difficulty: "challenge",
        stem: "已知点 M 在角的内部，且 M 到角两边的距离相等。请填写点 M 所在的特殊线，并说明这种判定与哪条几何思想相似。",
        blanks: [
          {
            id: "line",
            prompt: "点 M 所在的特殊线",
            hint: "想一想“到两边距离相等”的点在什么线上。",
            acceptableAnswers: ["角平分线", "在角平分线上"],
            placeholder: "请填写名称",
          },
          {
            id: "idea",
            prompt: "相似的几何思想",
            hint: "和“到线段两个端点距离相等”所在线有关。",
            acceptableAnswers: ["垂直平分线", "线段垂直平分线"],
            placeholder: "请填写名称",
          },
        ],
        explanation: "到角两边距离相等的点在角平分线上，这和“到线段两个端点距离相等的点在线段垂直平分线上”是类似的判定思想。",
        relatedLessonIds: ["lesson-g8s2-perpendicular-bisector"],
      },
      {
        id: "q9",
        quizId: "quiz-g8-shang-unit-2",
        type: "single-choice",
        difficulty: "challenge",
        stem: "在直线 l 上取一点 P，使 PA + PB 最小，其中点 A、B 在直线 l 同侧。最常用的转化思路是什么？",
        options: [
          { id: "a", label: "A", content: "把 A、B 都向 l 作垂线" },
          { id: "b", label: "B", content: "把其中一个点关于 l 对称，再连直线" },
          { id: "c", label: "C", content: "取 AB 中点作为 P" },
          { id: "d", label: "D", content: "直接猜测靠近 A 的点" },
        ],
        correctOptionId: "b",
        explanation: "最短路径问题常借助轴对称，把一个点关于直线 l 对称后转化为线段最短问题。",
        relatedLessonIds: ["lesson-g8s2-axis-symmetry"],
      },
      {
        id: "q10",
        quizId: "quiz-g8-shang-unit-2",
        type: "fill-blank",
        difficulty: "challenge",
        stem: "在线段 AB 的垂直平分线上取点 P，若 AB = 10，PA = 13。再在线段 AB 上取点 M 为中点。请填写 AM 的长度，并写出 PM 与 AM、BM 形成的三角形中相等的边。",
        blanks: [
          {
            id: "am",
            prompt: "AM 的长度",
            hint: "中点把 AB 平分。",
            acceptableAnswers: ["5"],
            placeholder: "请填写结果",
          },
          {
            id: "equal-side",
            prompt: "相等的两条边",
            hint: "因为 P 在垂直平分线上，所以 PA 与 PB 相等。",
            acceptableAnswers: ["PA=PB", "PA = PB"],
            placeholder: "请填写关系",
          },
        ],
        explanation: "中点 M 把 AB 平分，所以 AM = 5；又因为 P 在 AB 的垂直平分线上，所以 PA = PB。",
        relatedLessonIds: ["lesson-g8s2-perpendicular-bisector"],
      },
    ],
  },
};
