import type { CurriculumSlice } from "@/types/content";

export const g8XiaUnit5Slice: CurriculumSlice = {
  grade: {
    id: "g8",
    label: "八年级",
    shortLabel: "八下",
    description: "从图形证明、代数运算与函数关系中提升推理能力。",
  },
  volume: {
    id: "xia",
    gradeId: "g8",
    label: "下册",
    description: "以二次根式、勾股定理、四边形与函数为主要内容的综合提升阶段。",
  },
  chapter: {
    id: "g8-xia-unit-5",
    gradeId: "g8",
    volumeId: "xia",
    slug: "shu-ju-de-fen-xi",
    title: "第五章 数据的分析",
    summary: "会用平均数、中位数、众数和方差分析数据，并根据问题背景选择合适的统计量。",
    order: 5,
    lessonIds: ["lesson-g8x5-center", "lesson-g8x5-variance"],
    workedExampleIds: ["example-g8x5-represent", "example-g8x5-stability"],
    quizId: "quiz-g8-xia-unit-5",
  },
  lessons: [
    {
      id: "lesson-g8x5-center",
      chapterId: "g8-xia-unit-5",
      slug: "ji-zhong-qu-shi-tong-ji-liang",
      title: "平均数、中位数与众数",
      summary: "理解集中趋势统计量的含义，会结合数据特征判断哪个更有代表性。",
      learningObjectives: [
        "会计算平均数、中位数和众数。",
        "能比较它们各自适合描述的情境。",
        "会识别极端值对平均数的影响。",
      ],
      keyRules: [
        "平均数反映整体水平，但受极端值影响较大。",
        "中位数反映中间位置，受极端值影响较小。",
        "众数反映出现次数最多的数值。",
      ],
      bodyBlocks: [
        {
          type: "richText",
          id: "g8x5-center-context",
          title: "不是每次都该选平均数",
          content: [
            "统计题难点常常不在算，而在于为什么选这个统计量。",
            "只要数据里有明显离群值，就要警惕平均数是否失真。",
          ],
        },
      ],
      relatedExampleIds: ["example-g8x5-represent"],
      order: 1,
      videoPlaceholder: {
        title: "板书微课：三种统计量该怎么选",
        durationLabel: "5 分钟",
        description: "从代表性和稳定性两个角度比较。",
      },
    },
    {
      id: "lesson-g8x5-variance",
      chapterId: "g8-xia-unit-5",
      slug: "fang-cha-yu-wen-ding-xing",
      title: "方差与稳定性",
      summary: "理解方差反映波动程度，会用方差比较两组数据的稳定性。",
      learningObjectives: [
        "知道方差越小，数据越稳定。",
        "会结合平均数与方差综合评价两组数据。",
        "能避免把极差和方差混为一谈。",
      ],
      keyRules: [
        "方差体现数据偏离平均数的整体程度。",
        "平均数相同的两组数据，方差小的更稳定。",
        "分析数据时要同时看集中趋势与离散程度。",
      ],
      bodyBlocks: [
        {
          type: "tip",
          id: "g8x5-var-tip",
          title: "易错提醒",
          content: "“平均数相同”不代表两组数据表现一样，波动大小常常决定实际表现是否稳定。",
        },
      ],
      relatedExampleIds: ["example-g8x5-stability"],
      order: 2,
      videoPlaceholder: {
        title: "板书微课：方差到底在比较什么",
        durationLabel: "5 分钟",
        description: "从“离平均数有多远”理解方差。",
      },
    },
  ],
  workedExamples: [
    {
      id: "example-g8x5-represent",
      chapterId: "g8-xia-unit-5",
      slug: "dai-you-ji-duan-zhi-de-shu-ju",
      title: "例题 1：极端值下选哪个统计量",
      summary: "比较平均数、中位数和众数在不同场景中的代表性。",
      problem: "某组数据为 4，5，5，6，30。求平均数、中位数、众数，并说明哪个更能代表这组数据。",
      steps: [
        { id: "step-1", title: "分别计算", content: "平均数为 10，中位数为 5，众数为 5。" },
        { id: "step-2", title: "分析极端值影响", content: "30 明显偏大，使平均数远离大多数数据。" },
        { id: "step-3", title: "给出选择", content: "更适合用中位数或众数描述这组数据。" },
      ],
      answer: "平均数 10，中位数 5，众数 5；更适合用中位数或众数",
      commonMistakes: ["只因为平均数计算出来了，就默认它最有代表性。"],
      relatedLessonIds: ["lesson-g8x5-center"],
      order: 1,
    },
    {
      id: "example-g8x5-stability",
      chapterId: "g8-xia-unit-5",
      slug: "ping-jun-shu-xiang-tong-bi-fang-cha",
      title: "例题 2：平均数相同，比较稳定性",
      summary: "在平均数相同的情况下用方差判断哪组数据更稳定。",
      problem: "甲组数据为 8，8，8，8；乙组数据为 5，7，9，11。两组平均数都为 8，哪组更稳定？",
      steps: [
        { id: "step-1", title: "看平均数", content: "两组平均数相同，都是 8。" },
        { id: "step-2", title: "看偏离情况", content: "甲组每个数都等于平均数，乙组数据偏离平均数更明显。" },
        { id: "step-3", title: "下结论", content: "甲组方差更小，因此更稳定。" },
      ],
      answer: "甲组更稳定",
      commonMistakes: ["只比较最大值和最小值，不看整体波动。"],
      relatedLessonIds: ["lesson-g8x5-variance"],
      order: 2,
    },
  ],
  quiz: {
    id: "quiz-g8-xia-unit-5",
    chapterId: "g8-xia-unit-5",
    title: "第五章单元小测",
    instructions:
      "共 10 题，基础 2 题、进阶 4 题、压轴 4 题，整体难度明显上调，更强调多步推理、信息提取与综合应用。",
    passingScore: 80,
    questions: [
      {
        id: "q1",
        quizId: "quiz-g8-xia-unit-5",
        type: "single-choice",
        difficulty: "basic",
        stem: "数据 2，3，3，5，8 的中位数是多少？",
        options: [
          { id: "a", label: "A", content: "2" },
          { id: "b", label: "B", content: "3" },
          { id: "c", label: "C", content: "4" },
          { id: "d", label: "D", content: "5" },
        ],
        correctOptionId: "b",
        explanation: "中位数是排好序后最中间的数，即 3。",
        relatedLessonIds: ["lesson-g8x5-center"],
      },
      {
        id: "q2",
        quizId: "quiz-g8-xia-unit-5",
        type: "single-choice",
        difficulty: "basic",
        stem: "比较两组数据稳定性时，最常用哪个统计量？",
        options: [
          { id: "a", label: "A", content: "众数" },
          { id: "b", label: "B", content: "平均数" },
          { id: "c", label: "C", content: "方差" },
          { id: "d", label: "D", content: "中位数" },
        ],
        correctOptionId: "c",
        explanation: "比较稳定性时通常看方差大小。",
        relatedLessonIds: ["lesson-g8x5-variance"],
      },
      {
        id: "q3",
        quizId: "quiz-g8-xia-unit-5",
        type: "fill-blank",
        difficulty: "advanced",
        stem: "数据 4，6，8，10，12 的平均数和中位数分别是多少？",
        blanks: [
          {
            id: "mean",
            prompt: "平均数",
            hint: "求和后除以 5。",
            acceptableAnswers: ["8"],
            placeholder: "请填写结果",
          },
          {
            id: "median",
            prompt: "依据相关关系，中位数",
            hint: "先判断所用关系或方法，再已按从小到大排列。",
            acceptableAnswers: ["8"],
            placeholder: "请填写结果",
          },
        ],
        explanation: "依据题目中的条件和相关性质，这组数据平均数为 8，中位数也为 8。",
        relatedLessonIds: ["lesson-g8x5-center"],
      },
      {
        id: "q4",
        quizId: "quiz-g8-xia-unit-5",
        type: "single-choice",
        difficulty: "advanced",
        stem: "一组数据中加入一个远大于其他数的极端值后，哪个统计量最可能明显变化？",
        options: [
          { id: "a", label: "A", content: "平均数" },
          { id: "b", label: "B", content: "中位数" },
          { id: "c", label: "C", content: "众数" },
          { id: "d", label: "D", content: "以上都不会变" },
        ],
        correctOptionId: "a",
        explanation: "平均数受极端值影响最明显。",
        relatedLessonIds: ["lesson-g8x5-center"],
      },
      {
        id: "q5",
        quizId: "quiz-g8-xia-unit-5",
        type: "fill-blank",
        difficulty: "advanced",
        stem: "某组数据的众数是 7，中位数也是 7。请填写这能说明 7 在这组数据中的两个含义。",
        blanks: [
          {
            id: "mode",
            prompt: "众数含义",
            hint: "看出现次数。",
            acceptableAnswers: ["出现次数最多", "7出现次数最多"],
            placeholder: "请填写结果",
          },
          {
            id: "median",
            prompt: "中位数含义",
            hint: "看中间位置。",
            acceptableAnswers: ["位于中间位置", "排序后中间的数是7"],
            placeholder: "请填写结果",
          },
        ],
        explanation: "众数说明 7 出现次数最多，中位数说明排序后中间的数是 7。",
        relatedLessonIds: ["lesson-g8x5-center"],
      },
      {
        id: "q6",
        quizId: "quiz-g8-xia-unit-5",
        type: "single-choice",
        difficulty: "advanced",
        stem: "甲、乙两组数据平均数都为 90，且甲组更稳定。下列判断正确的是哪个？",
        options: [
          { id: "a", label: "A", content: "甲组方差更大" },
          { id: "b", label: "B", content: "乙组方差更小" },
          { id: "c", label: "C", content: "甲组方差更小" },
          { id: "d", label: "D", content: "两组方差相等" },
        ],
        correctOptionId: "c",
        explanation: "更稳定意味着方差更小。",
        relatedLessonIds: ["lesson-g8x5-variance"],
      },
      {
        id: "q7",
        quizId: "quiz-g8-xia-unit-5",
        type: "fill-blank",
        difficulty: "challenge",
        stem: "某班 5 名同学成绩为 60，70，80，90，100。请填写平均数，并判断它与中位数的大小关系。",
        blanks: [
          {
            id: "mean",
            prompt: "平均数",
            hint: "总分除以人数。",
            acceptableAnswers: ["80"],
            placeholder: "请填写结果",
          },
          {
            id: "compare",
            prompt: "与中位数的关系",
            hint: "这组数据关于 80 对称。",
            acceptableAnswers: ["相等", "平均数等于中位数"],
            placeholder: "请填写结果",
          },
        ],
        explanation: "平均数为 80，中位数也是 80，因此二者相等。",
        relatedLessonIds: ["lesson-g8x5-center"],
      },
      {
        id: "q8",
        quizId: "quiz-g8-xia-unit-5",
        type: "single-choice",
        difficulty: "challenge",
        stem: "两组数据：甲 6，6，6，10；乙 5，6，7，10。若只比较波动大小，哪个结论正确？",
        options: [
          { id: "a", label: "A", content: "甲更稳定" },
          { id: "b", label: "B", content: "乙更稳定" },
          { id: "c", label: "C", content: "一样稳定" },
          { id: "d", label: "D", content: "无法比较" },
        ],
        correctOptionId: "a",
        explanation: "甲组数据更集中，波动更小，因此更稳定。",
        relatedLessonIds: ["lesson-g8x5-variance"],
      },
      {
        id: "q9",
        quizId: "quiz-g8-xia-unit-5",
        type: "fill-blank",
        difficulty: "challenge",
        stem: "甲班平均分 82，乙班平均分 82，但甲班方差更小。请填写更适合用来说明“更整齐”的统计量名称，并写出大小规律。",
        blanks: [
          {
            id: "stat",
            prompt: "统计量名称",
            hint: "看波动。",
            acceptableAnswers: ["方差"],
            placeholder: "请填写结果",
          },
          {
            id: "rule",
            prompt: "大小规律",
            hint: "越整齐越小。",
            acceptableAnswers: ["越小越整齐", "方差越小越整齐"],
            placeholder: "请填写结果",
          },
        ],
        explanation: "说明整齐程度更适合看方差，方差越小越整齐。",
        relatedLessonIds: ["lesson-g8x5-variance"],
      },
      {
        id: "q10",
        quizId: "quiz-g8-xia-unit-5",
        type: "fill-blank",
        difficulty: "challenge",
        stem: "某商店一周顾客数为 20，20，22，22，22，24，40。请填写更适合描述这组数据“典型水平”的统计量，并说明原因。",
        blanks: [
          {
            id: "stat",
            prompt: "更合适的统计量",
            hint: "注意极端值 40。",
            acceptableAnswers: ["中位数", "众数"],
            placeholder: "请填写结果",
          },
          {
            id: "reason",
            prompt: "原因",
            hint: "平均数会被极端值拉高。",
            acceptableAnswers: ["受极端值影响较小", "40是极端值，平均数受影响较大"],
            placeholder: "请填写原因",
          },
        ],
        explanation: "中位数或众数更能代表典型水平，因为 40 是极端值，会明显影响平均数。",
        relatedLessonIds: ["lesson-g8x5-center", "lesson-g8x5-variance"],
      },
    ],
  },
};
