import type { CurriculumSlice } from "@/types/content";

export const g8XiaUnit4Slice: CurriculumSlice = {
  grade: {
    id: "g8",
    label: "八年级",
    shortLabel: "八下",
    description: "从图形证明、代数运算与函数关系中提升推理能力。",
  },
  volume: {
    id: "xia",
    gradeId: "g8",
    label: "下册",
    description: "以二次根式、勾股定理、四边形与函数为主要内容的综合提升阶段。",
  },
  chapter: {
    id: "g8-xia-unit-4",
    gradeId: "g8",
    volumeId: "xia",
    slug: "yi-ci-han-shu",
    title: "第四章 一次函数",
    summary: "理解一次函数与正比例函数的图象和性质，会用解析式、图象和实际情境解决问题。",
    order: 4,
    lessonIds: ["lesson-g8x4-expression", "lesson-g8x4-image"],
    workedExampleIds: ["example-g8x4-point", "example-g8x4-application"],
    quizId: "quiz-g8-xia-unit-4",
  },
  lessons: [
    {
      id: "lesson-g8x4-expression",
      chapterId: "g8-xia-unit-4",
      slug: "yi-ci-han-shu-jie-xi-shi",
      title: "一次函数解析式",
      summary: "掌握 y=kx+b 的基本形式，会由点的坐标或条件求函数解析式。",
      learningObjectives: [
        "会判断一个关系式是否为一次函数。",
        "会区分正比例函数与一般一次函数。",
        "会用已知点求简单一次函数解析式。",
      ],
      keyRules: [
        "一次函数一般形式是 y=kx+b（k≠0）。",
        "当 b=0 时，一次函数退化为正比例函数 y=kx。",
        "点在图象上，就满足函数解析式。",
      ],
      bodyBlocks: [
        {
          type: "richText",
          id: "g8x4-expression-context",
          title: "坐标和解析式要来回切换",
          content: [
            "一次函数题常常把图象、表格和文字条件混在一起，本质都是在找 k 和 b。",
            "只要点在图象上，就能把坐标代进解析式列方程。",
          ],
        },
      ],
      relatedExampleIds: ["example-g8x4-point"],
      order: 1,
      videoPlaceholder: {
        title: "板书微课：一次函数的 k 和 b 怎么找",
        durationLabel: "5 分钟",
        description: "从点坐标出发列方程。",
      },
    },
    {
      id: "lesson-g8x4-image",
      chapterId: "g8-xia-unit-4",
      slug: "yi-ci-han-shu-tu-xiang-yu-xing-zhi",
      title: "一次函数图象与应用",
      summary: "理解 k、b 对图象的影响，会结合图象判断增减性和截距。",
      learningObjectives: [
        "会根据 k 的正负判断图象升降。",
        "会根据 b 判断与 y 轴交点。",
        "会在实际问题中建立一次函数模型。",
      ],
      keyRules: [
        "k>0 时，函数值随 x 增大而增大；k<0 时相反。",
        "b 是图象与 y 轴交点的纵坐标。",
        "实际应用题要先确定自变量和函数值含义。",
      ],
      bodyBlocks: [
        {
          type: "formula",
          id: "g8x4-image-formula",
          title: "读图关键",
          formulas: ["y=2x+1：k=2，b=1", "y=-3x+4：k=-3，b=4"],
          note: "先看斜率方向，再看截距位置。",
        },
      ],
      relatedExampleIds: ["example-g8x4-application"],
      order: 2,
      videoPlaceholder: {
        title: "板书微课：一次函数图象怎样快速读",
        durationLabel: "6 分钟",
        description: "把 k、b 和图上的变化一一对应。",
      },
    },
  ],
  workedExamples: [
    {
      id: "example-g8x4-point",
      chapterId: "g8-xia-unit-4",
      slug: "yong-dian-zuo-biao-qiu-jie-xi-shi",
      title: "例题 1：由点求解析式",
      summary: "利用图象经过已知点求一次函数表达式。",
      problem: "已知一次函数 y=kx+b 经过点 (1,3) 和 (0,1)，求它的解析式。",
      steps: [
        {
          id: "step-1",
          title: "先求 b",
          content: "点 (0,1) 在图象上，所以 b=1。",
        },
        {
          id: "step-2",
          title: "再求 k",
          content: "把 (1,3) 代入得 3=k+1，所以 k=2。",
        },
        {
          id: "step-3",
          title: "写解析式",
          content: "所以函数解析式为 y=2x+1。",
        },
      ],
      answer: "y=2x+1",
      commonMistakes: ["忘记 x=0 时函数值就是 b。"],
      relatedLessonIds: ["lesson-g8x4-expression"],
      order: 1,
    },
    {
      id: "example-g8x4-application",
      chapterId: "g8-xia-unit-4",
      slug: "shou-fei-mo-xing",
      title: "例题 2：建立收费模型",
      summary: "把固定费用和按量收费结合成一次函数。",
      problem: "某打车计费方式为起步价 8 元，每千米加收 2 元。设行驶 x 千米后的费用为 y 元，写出 y 与 x 的函数关系。",
      steps: [
        { id: "step-1", title: "识别固定部分", content: "起步价 8 元对应常数项。" },
        { id: "step-2", title: "识别变化部分", content: "每千米加收 2 元，对应系数 2。" },
        { id: "step-3", title: "写出函数关系", content: "所以 y=2x+8。" },
      ],
      answer: "y=2x+8",
      commonMistakes: ["把起步价漏掉，只写成 y=2x。"],
      relatedLessonIds: ["lesson-g8x4-image"],
      order: 2,
    },
  ],
  quiz: {
    id: "quiz-g8-xia-unit-4",
    chapterId: "g8-xia-unit-4",
    title: "第四章单元小测",
    instructions:
      "共 10 题，基础 2 题、进阶 4 题、压轴 4 题，整体难度明显上调，更强调多步推理、信息提取与综合应用。",
    passingScore: 80,
    questions: [
      {
        id: "q1",
        quizId: "quiz-g8-xia-unit-4",
        type: "single-choice",
        difficulty: "basic",
        stem: "下列哪个式子表示一次函数？",
        options: [
          { id: "a", label: "A", content: "y=3x+2" },
          { id: "b", label: "B", content: "y=x²+1" },
          { id: "c", label: "C", content: "y=1/x" },
          { id: "d", label: "D", content: "y=5" },
        ],
        correctOptionId: "a",
        explanation: "只有 y=3x+2 符合 y=kx+b（k≠0）的形式。",
        relatedLessonIds: ["lesson-g8x4-expression"],
      },
      {
        id: "q2",
        quizId: "quiz-g8-xia-unit-4",
        type: "single-choice",
        difficulty: "basic",
        stem: "函数 y=-2x+3 中，图象随 x 的增大如何变化？",
        options: [
          { id: "a", label: "A", content: "上升" },
          { id: "b", label: "B", content: "下降" },
          { id: "c", label: "C", content: "先升后降" },
          { id: "d", label: "D", content: "保持不变" },
        ],
        correctOptionId: "b",
        explanation: "因为 k=-2<0，所以图象从左到右下降。",
        relatedLessonIds: ["lesson-g8x4-image"],
      },
      {
        id: "q3",
        quizId: "quiz-g8-xia-unit-4",
        type: "fill-blank",
        difficulty: "advanced",
        stem: "若一次函数 y=kx+4 经过点 (2,10)，请填写 k 的值，并写出完整解析式。",
        blanks: [
          {
            id: "k",
            prompt: "k 的值",
            hint: "把点坐标代入。",
            acceptableAnswers: ["3"],
            placeholder: "请填写结果",
          },
          {
            id: "expression",
            prompt: "依据相关关系，完整解析式",
            hint: "先判断所用关系或方法，再代回 y=kx+4。",
            acceptableAnswers: ["y=3x+4", "y = 3x + 4"],
            placeholder: "请填写结果",
          },
        ],
        explanation: "依据题目中的条件和相关性质，10=2k+4，所以 k=3，解析式为 y=3x+4。",
        relatedLessonIds: ["lesson-g8x4-expression"],
      },
      {
        id: "q4",
        quizId: "quiz-g8-xia-unit-4",
        type: "single-choice",
        difficulty: "advanced",
        stem: "一次函数 y=2x-5 与 y 轴的交点坐标是哪个？",
        options: [
          { id: "a", label: "A", content: "(0,-5)" },
          { id: "b", label: "B", content: "(-5,0)" },
          { id: "c", label: "C", content: "(2,0)" },
          { id: "d", label: "D", content: "(0,2)" },
        ],
        correctOptionId: "a",
        explanation: "与 y 轴交点时 x=0，因此坐标为 (0,-5)。",
        relatedLessonIds: ["lesson-g8x4-image"],
      },
      {
        id: "q5",
        quizId: "quiz-g8-xia-unit-4",
        type: "fill-blank",
        difficulty: "advanced",
        stem: "正比例函数经过点 (3,6)。请填写它的解析式，并说明它是否经过原点。",
        blanks: [
          {
            id: "expression",
            prompt: "解析式",
            hint: "正比例函数形如 y=kx。",
            acceptableAnswers: ["y=2x", "y = 2x"],
            placeholder: "请填写结果",
          },
          {
            id: "origin",
            prompt: "是否经过原点",
            hint: "正比例函数的 b=0。",
            acceptableAnswers: ["是"],
            placeholder: "请填写判断",
          },
        ],
        explanation: "6=3k，所以 k=2，解析式为 y=2x；正比例函数经过原点。",
        relatedLessonIds: ["lesson-g8x4-expression"],
      },
      {
        id: "q6",
        quizId: "quiz-g8-xia-unit-4",
        type: "single-choice",
        difficulty: "advanced",
        stem: "若一次函数图象经过点 (0,2) 和 (1,5)，则它的解析式是哪个？",
        options: [
          { id: "a", label: "A", content: "y=3x+2" },
          { id: "b", label: "B", content: "y=2x+3" },
          { id: "c", label: "C", content: "y=5x+1" },
          { id: "d", label: "D", content: "y=-3x+2" },
        ],
        correctOptionId: "a",
        explanation: "由 (0,2) 得 b=2，再代入 (1,5) 得 k=3。",
        relatedLessonIds: ["lesson-g8x4-expression", "lesson-g8x4-image"],
      },
      {
        id: "q7",
        quizId: "quiz-g8-xia-unit-4",
        type: "fill-blank",
        difficulty: "challenge",
        stem: "某水箱原有 20 升水，每分钟流入 3 升。请填写 t 分钟后的水量表达式，并求 10 分钟后的水量。",
        blanks: [
          {
            id: "expression",
            prompt: "水量表达式",
            hint: "固定量加变化量。",
            acceptableAnswers: ["y=3t+20", "y = 3t + 20"],
            placeholder: "请填写结果",
          },
          {
            id: "value",
            prompt: "10 分钟后的水量",
            hint: "代入 t=10。",
            acceptableAnswers: ["50"],
            placeholder: "请填写结果",
          },
        ],
        explanation: "y=3t+20，当 t=10 时，y=50。",
        relatedLessonIds: ["lesson-g8x4-image"],
      },
      {
        id: "q8",
        quizId: "quiz-g8-xia-unit-4",
        type: "single-choice",
        difficulty: "challenge",
        stem: "下列关于一次函数 y=-x+4 的说法正确的是哪个？",
        options: [
          { id: "a", label: "A", content: "图象经过原点" },
          { id: "b", label: "B", content: "图象随 x 增大而增大" },
          { id: "c", label: "C", content: "与 y 轴交于点 (0,4)" },
          { id: "d", label: "D", content: "k=4，b=-1" },
        ],
        correctOptionId: "c",
        explanation: "函数 y=-x+4 中 b=4，所以与 y 轴交于点 (0,4)。",
        relatedLessonIds: ["lesson-g8x4-image"],
      },
      {
        id: "q9",
        quizId: "quiz-g8-xia-unit-4",
        type: "fill-blank",
        difficulty: "challenge",
        stem: "一次函数 y=kx+b 的图象经过点 (2,1) 和 (-1,-5)。请填写 k、b 的值。",
        blanks: [
          {
            id: "k",
            prompt: "k 的值",
            hint: "可由斜率差求出。",
            acceptableAnswers: ["2"],
            placeholder: "请填写结果",
          },
          {
            id: "b",
            prompt: "b 的值",
            hint: "代回任一点。",
            acceptableAnswers: ["-3"],
            placeholder: "请填写结果",
          },
        ],
        explanation: "由两点可得 k=(1-(-5))/(2-(-1))=2，再代入得 b=-3。",
        relatedLessonIds: ["lesson-g8x4-expression"],
      },
      {
        id: "q10",
        quizId: "quiz-g8-xia-unit-4",
        type: "fill-blank",
        difficulty: "challenge",
        stem: "甲、乙两条收费直线分别表示 y=4x 和 y=3x+6。请填写两者费用相等时的 x 值，并判断当 x>这个值时哪条更贵。",
        blanks: [
          {
            id: "x",
            prompt: "费用相等时的 x 值",
            hint: "令 4x=3x+6。",
            acceptableAnswers: ["6"],
            placeholder: "请填写结果",
          },
          {
            id: "compare",
            prompt: "x 更大时哪条更贵",
            hint: "比较斜率大小。",
            acceptableAnswers: ["甲", "y=4x 更贵"],
            placeholder: "请填写结果",
          },
        ],
        explanation: "解得 x=6；当 x>6 时，斜率更大的 y=4x 增长更快，所以甲更贵。",
        relatedLessonIds: ["lesson-g8x4-expression", "lesson-g8x4-image"],
      },
    ],
  },
};
