import type { CurriculumSlice } from "@/types/content";

export const g8XiaUnit1Slice: CurriculumSlice = {
  grade: {
    id: "g8",
    label: "八年级",
    shortLabel: "八下",
    description: "从图形证明、代数运算与函数关系中提升推理能力。",
  },
  volume: {
    id: "xia",
    gradeId: "g8",
    label: "下册",
    description: "以二次根式、勾股定理、四边形与函数为主要内容的综合提升阶段。",
  },
  chapter: {
    id: "g8-xia-unit-1",
    gradeId: "g8",
    volumeId: "xia",
    slug: "er-ci-gen-shi",
    title: "第一章 二次根式",
    summary: "理解二次根式的意义与性质，会进行化简、运算并解决简单应用问题。",
    order: 1,
    lessonIds: ["lesson-g8x1-concept", "lesson-g8x1-operations"],
    workedExampleIds: ["example-g8x1-simplify", "example-g8x1-calculate"],
    quizId: "quiz-g8-xia-unit-1",
  },
  lessons: [
    {
      id: "lesson-g8x1-concept",
      chapterId: "g8-xia-unit-1",
      slug: "er-ci-gen-shi-de-gai-nian-yu-xing-zhi",
      title: "二次根式的概念与性质",
      summary: "掌握二次根式有意义条件，会利用被开方数的非负性判断取值范围。",
      learningObjectives: [
        "理解形如 √a 的式子什么时候有意义。",
        "会判断二次根式中字母的取值范围。",
        "会使用 √a 的非负性解决简单问题。",
      ],
      keyRules: [
        "二次根式 √a 有意义的条件是 a≥0。",
        "二次根式的值恒为非负数。",
        "√(a²)=|a|，不能直接写成 a。",
      ],
      bodyBlocks: [
        {
          type: "richText",
          id: "g8x1-concept-context",
          title: "先看被开方数",
          content: [
            "二次根式题最先看的是被开方数能不能取到负数，而不是立刻去化简。",
            "很多后续错误，都源于一开始忽略了有意义条件。",
          ],
        },
      ],
      relatedExampleIds: ["example-g8x1-simplify"],
      order: 1,
      videoPlaceholder: {
        title: "板书微课：二次根式先看什么",
        durationLabel: "5 分钟",
        description: "抓住“被开方数非负”这个第一原则。",
      },
    },
    {
      id: "lesson-g8x1-operations",
      chapterId: "g8-xia-unit-1",
      slug: "er-ci-gen-shi-de-hua-jian-yu-yun-suan",
      title: "二次根式的化简与运算",
      summary: "会对二次根式进行化简、加减和乘除，理解同类二次根式的合并方法。",
      learningObjectives: [
        "会把根号内的完全平方因式提出。",
        "会识别并合并同类二次根式。",
        "会进行简单的二次根式乘除运算。",
      ],
      keyRules: [
        "√(ab)=√a·√b（a、b 均非负）。",
        "只有同类二次根式才能直接合并。",
        "化简后的结果一般写成最简二次根式。",
      ],
      bodyBlocks: [
        {
          type: "formula",
          id: "g8x1-op-formula",
          title: "常见形式",
          formulas: ["√12=2√3", "3√2+2√2=5√2", "√18÷√2=3"],
          note: "做运算前先化简，往往更容易发现同类项。",
        },
      ],
      relatedExampleIds: ["example-g8x1-calculate"],
      order: 2,
      videoPlaceholder: {
        title: "板书微课：二次根式运算怎么不乱",
        durationLabel: "6 分钟",
        description: "先化简、再分类、后运算。",
      },
    },
  ],
  workedExamples: [
    {
      id: "example-g8x1-simplify",
      chapterId: "g8-xia-unit-1",
      slug: "pan-duan-you-yi-yi-bing-hua-jian",
      title: "例题 1：先判断有意义，再化简",
      summary: "把有意义条件和二次根式化简结合起来处理。",
      problem: "化简 √(12x²)，并写出它有意义时 x 需要满足的条件。",
      steps: [
        {
          id: "step-1",
          title: "判断有意义条件",
          content: "12x²≥0 对任意实数 x 都成立，所以这个式子对任意实数 x 都有意义。",
        },
        {
          id: "step-2",
          title: "拆出完全平方因式",
          content: "√(12x²)=√(4×3×x²)=2|x|√3。",
        },
        {
          id: "step-3",
          title: "写结论",
          content: "原式化简为 2|x|√3，且对任意实数 x 都有意义。",
        },
      ],
      answer: "2|x|√3；对任意实数 x 都有意义",
      commonMistakes: ["把 √(x²) 直接写成 x。"],
      relatedLessonIds: ["lesson-g8x1-concept", "lesson-g8x1-operations"],
      order: 1,
    },
    {
      id: "example-g8x1-calculate",
      chapterId: "g8-xia-unit-1",
      slug: "tong-lei-er-ci-gen-shi-he-bing",
      title: "例题 2：合并同类二次根式",
      summary: "先化简，再判断是否能合并。",
      problem: "计算：√50-2√8+√18。",
      steps: [
        {
          id: "step-1",
          title: "分别化简",
          content: "√50=5√2，2√8=4√2，√18=3√2。",
        },
        {
          id: "step-2",
          title: "合并同类项",
          content: "5√2-4√2+3√2=4√2。",
        },
      ],
      answer: "4√2",
      commonMistakes: ["没有先化简就直接把根号内数字相减。"],
      relatedLessonIds: ["lesson-g8x1-operations"],
      order: 2,
    },
  ],
  quiz: {
    id: "quiz-g8-xia-unit-1",
    chapterId: "g8-xia-unit-1",
    title: "第一章单元小测",
    instructions:
      "共 10 题，基础 2 题、进阶 4 题、压轴 4 题，整体难度明显上调，更强调多步推理、信息提取与综合应用。",
    passingScore: 80,
    questions: [
      {
        id: "q1",
        quizId: "quiz-g8-xia-unit-1",
        type: "single-choice",
        difficulty: "basic",
        stem: "下列式子中，一定有意义的是哪一个？",
        options: [
          { id: "a", label: "A", content: "√(-2)" },
          { id: "b", label: "B", content: "√x" },
          { id: "c", label: "C", content: "√(x²+1)" },
          { id: "d", label: "D", content: "√(3-x)" },
        ],
        correctOptionId: "c",
        explanation: "x²+1 恒大于 0，因此 √(x²+1) 对任意实数 x 都有意义。",
        relatedLessonIds: ["lesson-g8x1-concept"],
      },
      {
        id: "q2",
        quizId: "quiz-g8-xia-unit-1",
        type: "single-choice",
        difficulty: "basic",
        stem: "化简 √20 的结果是哪个？",
        options: [
          { id: "a", label: "A", content: "10√2" },
          { id: "b", label: "B", content: "2√5" },
          { id: "c", label: "C", content: "4√5" },
          { id: "d", label: "D", content: "5√2" },
        ],
        correctOptionId: "b",
        explanation: "√20=√(4×5)=2√5。",
        relatedLessonIds: ["lesson-g8x1-operations"],
      },
      {
        id: "q3",
        quizId: "quiz-g8-xia-unit-1",
        type: "fill-blank",
        difficulty: "advanced",
        stem: "若二次根式 √(x-1) 有意义，请填写 x 的取值范围，并写出当 x=10 时原式的值。",
        blanks: [
          {
            id: "range",
            prompt: "x 的取值范围",
            hint: "被开方数要不小于 0。",
            acceptableAnswers: ["x≥1", "x >= 1"],
            placeholder: "请填写结果",
          },
          {
            id: "value",
            prompt: "依据相关关系，x=10 时原式的值",
            hint: "先判断所用关系或方法，再代入后再开方。",
            acceptableAnswers: ["3"],
            placeholder: "请填写结果",
          },
        ],
        explanation: "依据题目中的条件和相关性质，x-1≥0，所以 x≥1；当 x=10 时，原式为 √9=3。",
        relatedLessonIds: ["lesson-g8x1-concept"],
      },
      {
        id: "q4",
        quizId: "quiz-g8-xia-unit-1",
        type: "single-choice",
        difficulty: "advanced",
        stem: "下列化简正确的是哪一个？",
        options: [
          { id: "a", label: "A", content: "√(a²)=a" },
          { id: "b", label: "B", content: "√45=3√5" },
          { id: "c", label: "C", content: "√12=3√4" },
          { id: "d", label: "D", content: "√18=2√3" },
        ],
        correctOptionId: "b",
        explanation: "√45=√(9×5)=3√5。其余选项均有错误。",
        relatedLessonIds: ["lesson-g8x1-operations"],
      },
      {
        id: "q5",
        quizId: "quiz-g8-xia-unit-1",
        type: "fill-blank",
        difficulty: "advanced",
        stem: "计算：3√2+√8，并写出你先做的关键一步。",
        blanks: [
          {
            id: "result",
            prompt: "计算结果",
            hint: "先化简 √8。",
            acceptableAnswers: ["5√2"],
            placeholder: "请填写结果",
          },
          {
            id: "step",
            prompt: "关键一步",
            hint: "把 √8 化成同类二次根式。",
            acceptableAnswers: ["把√8化简为2√2", "先把√8化简为2√2"],
            placeholder: "请填写步骤",
          },
        ],
        explanation: "√8=2√2，所以 3√2+√8=3√2+2√2=5√2。",
        relatedLessonIds: ["lesson-g8x1-operations"],
      },
      {
        id: "q6",
        quizId: "quiz-g8-xia-unit-1",
        type: "single-choice",
        difficulty: "advanced",
        stem: "若 √(2x+6)=4，则 x 的值为多少？",
        options: [
          { id: "a", label: "A", content: "3" },
          { id: "b", label: "B", content: "4" },
          { id: "c", label: "C", content: "5" },
          { id: "d", label: "D", content: "6" },
        ],
        correctOptionId: "c",
        explanation: "2x+6=16，所以 x=5，且满足有意义条件。",
        relatedLessonIds: ["lesson-g8x1-concept"],
      },
      {
        id: "q7",
        quizId: "quiz-g8-xia-unit-1",
        type: "fill-blank",
        difficulty: "challenge",
        stem: "已知 a=√12，b=√27。请分别化简 a、b，并判断 a 与 b 的大小关系。",
        blanks: [
          {
            id: "simplify",
            prompt: "化简后的 a、b",
            hint: "分别提出完全平方因式。",
            acceptableAnswers: ["a=2√3,b=3√3", "a=2√3，b=3√3"],
            placeholder: "请填写结果",
          },
          {
            id: "compare",
            prompt: "大小关系",
            hint: "化简后比较系数。",
            acceptableAnswers: ["a<b", "b>a"],
            placeholder: "请填写结果",
          },
        ],
        explanation: "a=2√3，b=3√3，所以 a<b。",
        relatedLessonIds: ["lesson-g8x1-operations"],
      },
      {
        id: "q8",
        quizId: "quiz-g8-xia-unit-1",
        type: "single-choice",
        difficulty: "challenge",
        stem: "若 x≥0，且 √(x²)=6，则 x 等于多少？",
        options: [
          { id: "a", label: "A", content: "-6" },
          { id: "b", label: "B", content: "6" },
          { id: "c", label: "C", content: "±6" },
          { id: "d", label: "D", content: "36" },
        ],
        correctOptionId: "b",
        explanation: "√(x²)=|x|，又因为 x≥0，所以 |x|=x=6。",
        relatedLessonIds: ["lesson-g8x1-concept"],
      },
      {
        id: "q9",
        quizId: "quiz-g8-xia-unit-1",
        type: "fill-blank",
        difficulty: "challenge",
        stem: "计算：√75-√12+2√3，并写出结果中是否还存在可化简部分。",
        blanks: [
          {
            id: "result",
            prompt: "计算结果",
            hint: "先把各项都化成 √3 的形式。",
            acceptableAnswers: ["5√3"],
            placeholder: "请填写结果",
          },
          {
            id: "final",
            prompt: "是否还可继续化简",
            hint: "最简二次根式不能再提出完全平方因式。",
            acceptableAnswers: ["不能", "不可以"],
            placeholder: "请填写判断",
          },
        ],
        explanation: "√75=5√3，√12=2√3，所以原式为 5√3-2√3+2√3=5√3，已是最简形式。",
        relatedLessonIds: ["lesson-g8x1-operations"],
      },
      {
        id: "q10",
        quizId: "quiz-g8-xia-unit-1",
        type: "fill-blank",
        difficulty: "challenge",
        stem: "若 x、y 都是正整数，且 √x=2√3，√y=3√2。请填写 x+y 的值，并说明你是如何由根式反推被开方数的。",
        blanks: [
          {
            id: "sum",
            prompt: "x+y 的值",
            hint: "先分别平方。",
            acceptableAnswers: ["30"],
            placeholder: "请填写结果",
          },
          {
            id: "method",
            prompt: "反推方法",
            hint: "利用平方把根号去掉。",
            acceptableAnswers: ["两边平方", "分别两边平方"],
            placeholder: "请填写方法",
          },
        ],
        explanation: "由 √x=2√3 得 x=12，由 √y=3√2 得 y=18，所以 x+y=30。",
        relatedLessonIds: ["lesson-g8x1-concept", "lesson-g8x1-operations"],
      },
    ],
  },
};
