import type { CurriculumSlice } from "@/types/content";

export const g8XiaUnit3Slice: CurriculumSlice = {
  grade: {
    id: "g8",
    label: "八年级",
    shortLabel: "八下",
    description: "从图形证明、代数运算与函数关系中提升推理能力。",
  },
  volume: {
    id: "xia",
    gradeId: "g8",
    label: "下册",
    description: "以二次根式、勾股定理、四边形与函数为主要内容的综合提升阶段。",
  },
  chapter: {
    id: "g8-xia-unit-3",
    gradeId: "g8",
    volumeId: "xia",
    slug: "ping-xing-si-bian-xing",
    title: "第三章 平行四边形",
    summary: "掌握平行四边形的性质与判定，会处理矩形、菱形、正方形等特殊四边形问题。",
    order: 3,
    lessonIds: ["lesson-g8x3-property", "lesson-g8x3-special"],
    workedExampleIds: ["example-g8x3-diagonal", "example-g8x3-judge"],
    quizId: "quiz-g8-xia-unit-3",
  },
  lessons: [
    {
      id: "lesson-g8x3-property",
      chapterId: "g8-xia-unit-3",
      slug: "ping-xing-si-bian-xing-de-xing-zhi",
      title: "平行四边形的性质与判定",
      summary: "理解对边、对角、对角线的性质，会利用边角关系判断四边形类型。",
      learningObjectives: [
        "会使用平行四边形对边平行且相等的性质。",
        "会使用对角相等、邻角互补的性质。",
        "会用对角线互相平分等条件判定平行四边形。",
      ],
      keyRules: [
        "平行四边形的对边平行且相等。",
        "平行四边形的对角相等，对角线互相平分。",
        "两组对边分别平行或分别相等的四边形是平行四边形。",
      ],
      bodyBlocks: [
        {
          type: "richText",
          id: "g8x3-property-context",
          title: "性质和判定不要混用",
          content: [
            "已知是平行四边形去求线段和角，用性质；已知边角关系想证明它是平行四边形，用判定。",
            "这类题的关键不是公式多，而是方向要分清。",
          ],
        },
      ],
      relatedExampleIds: ["example-g8x3-diagonal"],
      order: 1,
      videoPlaceholder: {
        title: "板书微课：平行四边形题先想性质还是判定",
        durationLabel: "5 分钟",
        description: "把“已知”和“目标”对应起来。",
      },
    },
    {
      id: "lesson-g8x3-special",
      chapterId: "g8-xia-unit-3",
      slug: "ju-xing-ling-xing-zheng-fang-xing",
      title: "矩形、菱形与正方形",
      summary: "掌握特殊平行四边形的额外性质，会比较不同图形的联系与区别。",
      learningObjectives: [
        "会区分矩形、菱形、正方形的关键性质。",
        "会利用对角线性质解决特殊四边形问题。",
        "能从定义链条理解图形之间的包含关系。",
      ],
      keyRules: [
        "矩形的四个角都是直角，对角线相等。",
        "菱形的四条边都相等，对角线互相垂直。",
        "正方形同时具有矩形和菱形的性质。",
      ],
      bodyBlocks: [
        {
          type: "tip",
          id: "g8x3-special-tip",
          title: "易错提醒",
          content: "“对角线相等”可以想到矩形，但不能直接想到菱形；“对角线垂直”可以想到菱形，但不能单独推出正方形。",
        },
      ],
      relatedExampleIds: ["example-g8x3-judge"],
      order: 2,
      videoPlaceholder: {
        title: "板书微课：特殊平行四边形如何快速辨认",
        durationLabel: "6 分钟",
        description: "抓住最有区分度的那条性质。",
      },
    },
  ],
  workedExamples: [
    {
      id: "example-g8x3-diagonal",
      chapterId: "g8-xia-unit-3",
      slug: "dui-jiao-xian-hu-xiang-ping-fen",
      title: "例题 1：用对角线性质求线段",
      summary: "在平行四边形中利用对角线互相平分求未知长度。",
      problem: "在平行四边形 ABCD 中，对角线 AC、BD 交于点 O，若 AC=18，求 AO 的长度。",
      steps: [
        { id: "step-1", title: "调用性质", content: "平行四边形的对角线互相平分。" },
        { id: "step-2", title: "求长度", content: "所以 AO=AC÷2=9。" },
      ],
      answer: "9",
      commonMistakes: ["把 AO 误当成与 AC 相等。"],
      relatedLessonIds: ["lesson-g8x3-property"],
      order: 1,
    },
    {
      id: "example-g8x3-judge",
      chapterId: "g8-xia-unit-3",
      slug: "pan-duan-shi-fou-wei-ju-xing",
      title: "例题 2：从平行四边形进一步判定矩形",
      summary: "在平行四边形的基础上，加入直角条件判定矩形。",
      problem: "四边形 ABCD 是平行四边形，且 ∠A=90°，判断 ABCD 的形状。",
      steps: [
        { id: "step-1", title: "已知基础图形", content: "ABCD 已经是平行四边形。" },
        { id: "step-2", title: "看附加条件", content: "平行四边形中若有一个角是直角，则四个角都是直角。" },
        { id: "step-3", title: "下结论", content: "所以 ABCD 是矩形。" },
      ],
      answer: "矩形",
      commonMistakes: ["只说“有直角”，没有结合平行四边形条件。"],
      relatedLessonIds: ["lesson-g8x3-property", "lesson-g8x3-special"],
      order: 2,
    },
  ],
  quiz: {
    id: "quiz-g8-xia-unit-3",
    chapterId: "g8-xia-unit-3",
    title: "第三章单元小测",
    instructions:
      "共 10 题，基础 2 题、进阶 4 题、压轴 4 题，整体难度明显上调，更强调多步推理、信息提取与综合应用。",
    passingScore: 80,
    questions: [
      {
        id: "q1",
        quizId: "quiz-g8-xia-unit-3",
        type: "single-choice",
        difficulty: "basic",
        stem: "平行四边形的对角线具有哪条性质？",
        options: [
          { id: "a", label: "A", content: "互相垂直" },
          { id: "b", label: "B", content: "互相平分" },
          { id: "c", label: "C", content: "一定相等" },
          { id: "d", label: "D", content: "一定平行" },
        ],
        correctOptionId: "b",
        explanation: "平行四边形的对角线互相平分。",
        relatedLessonIds: ["lesson-g8x3-property"],
      },
      {
        id: "q2",
        quizId: "quiz-g8-xia-unit-3",
        type: "single-choice",
        difficulty: "basic",
        stem: "下列哪个图形一定是平行四边形？",
        options: [
          { id: "a", label: "A", content: "两组对边分别平行的四边形" },
          { id: "b", label: "B", content: "一组对边平行的四边形" },
          { id: "c", label: "C", content: "有两个直角的四边形" },
          { id: "d", label: "D", content: "有两边相等的四边形" },
        ],
        correctOptionId: "a",
        explanation: "两组对边分别平行的四边形是平行四边形。",
        relatedLessonIds: ["lesson-g8x3-property"],
      },
      {
        id: "q3",
        quizId: "quiz-g8-xia-unit-3",
        type: "fill-blank",
        difficulty: "advanced",
        stem: "在平行四边形 ABCD 中，若 AB=7，BC=5。请填写 CD 与 AD 的长度。",
        blanks: [
          {
            id: "cd",
            prompt: "CD 的长度",
            hint: "对边相等。",
            acceptableAnswers: ["7"],
            placeholder: "请填写结果",
          },
          {
            id: "ad",
            prompt: "依据相关关系，AD 的长度",
            hint: "先判断所用关系或方法，再另一组对边也相等。",
            acceptableAnswers: ["5"],
            placeholder: "请填写结果",
          },
        ],
        explanation: "依据题目中的条件和相关性质，平行四边形对边相等，所以 CD=7，AD=5。",
        relatedLessonIds: ["lesson-g8x3-property"],
      },
      {
        id: "q4",
        quizId: "quiz-g8-xia-unit-3",
        type: "single-choice",
        difficulty: "advanced",
        stem: "平行四边形 ABCD 中，若 ∠A=70°，则 ∠C 等于多少？",
        options: [
          { id: "a", label: "A", content: "70°" },
          { id: "b", label: "B", content: "110°" },
          { id: "c", label: "C", content: "35°" },
          { id: "d", label: "D", content: "140°" },
        ],
        correctOptionId: "a",
        explanation: "平行四边形对角相等，所以 ∠C=70°。",
        relatedLessonIds: ["lesson-g8x3-property"],
      },
      {
        id: "q5",
        quizId: "quiz-g8-xia-unit-3",
        type: "fill-blank",
        difficulty: "advanced",
        stem: "平行四边形的一条对角线长为 16，两条对角线交于点 O。请填写 O 到这条对角线两个端点的距离关系和具体长度。",
        blanks: [
          {
            id: "relation",
            prompt: "距离关系",
            hint: "对角线互相平分。",
            acceptableAnswers: ["相等"],
            placeholder: "请填写结果",
          },
          {
            id: "length",
            prompt: "各自长度",
            hint: "总长的一半。",
            acceptableAnswers: ["8"],
            placeholder: "请填写结果",
          },
        ],
        explanation: "因为对角线互相平分，所以 O 到两端点距离相等，且都为 8。",
        relatedLessonIds: ["lesson-g8x3-property"],
      },
      {
        id: "q6",
        quizId: "quiz-g8-xia-unit-3",
        type: "single-choice",
        difficulty: "advanced",
        stem: "一个平行四边形有一个角是直角，则这个图形一定是哪个？",
        options: [
          { id: "a", label: "A", content: "菱形" },
          { id: "b", label: "B", content: "矩形" },
          { id: "c", label: "C", content: "正方形" },
          { id: "d", label: "D", content: "梯形" },
        ],
        correctOptionId: "b",
        explanation: "平行四边形中若有一个角是直角，则它是矩形。",
        relatedLessonIds: ["lesson-g8x3-special"],
      },
      {
        id: "q7",
        quizId: "quiz-g8-xia-unit-3",
        type: "fill-blank",
        difficulty: "challenge",
        stem: "一个菱形的边长为 5，两条对角线交于点 O，若 AO=3。请填写另一条半对角线 BO 的长度，并说明你用到的三角形类型。",
        blanks: [
          {
            id: "bo",
            prompt: "BO 的长度",
            hint: "菱形对角线互相垂直平分。",
            acceptableAnswers: ["4"],
            placeholder: "请填写结果",
          },
          {
            id: "triangle",
            prompt: "所用三角形类型",
            hint: "AO、BO、边长构成勾股关系。",
            acceptableAnswers: ["直角三角形"],
            placeholder: "请填写结果",
          },
        ],
        explanation: "在直角三角形 AOB 中，AB=5，AO=3，所以 BO=4。",
        relatedLessonIds: ["lesson-g8x3-special"],
      },
      {
        id: "q8",
        quizId: "quiz-g8-xia-unit-3",
        type: "single-choice",
        difficulty: "challenge",
        stem: "下列条件中，最能直接判定一个平行四边形是正方形的是哪个？",
        options: [
          { id: "a", label: "A", content: "对角线互相平分" },
          { id: "b", label: "B", content: "一组邻边相等且有一个角是直角" },
          { id: "c", label: "C", content: "对边平行" },
          { id: "d", label: "D", content: "对角相等" },
        ],
        correctOptionId: "b",
        explanation: "平行四边形若一组邻边相等可判为菱形，再加一个直角即可判为正方形。",
        relatedLessonIds: ["lesson-g8x3-property", "lesson-g8x3-special"],
      },
      {
        id: "q9",
        quizId: "quiz-g8-xia-unit-3",
        type: "fill-blank",
        difficulty: "challenge",
        stem: "已知四边形 ABCD 中，AB∥CD，且 AB=CD。请填写它能判定成什么图形，并说明使用的是哪类判定思路。",
        blanks: [
          {
            id: "shape",
            prompt: "图形类型",
            hint: "一组对边平行且相等。",
            acceptableAnswers: ["平行四边形"],
            placeholder: "请填写结果",
          },
          {
            id: "idea",
            prompt: "判定思路",
            hint: "从边的关系出发。",
            acceptableAnswers: ["一组对边平行且相等判定", "边的判定"],
            placeholder: "请填写结果",
          },
        ],
        explanation: "一组对边平行且相等的四边形是平行四边形。",
        relatedLessonIds: ["lesson-g8x3-property"],
      },
      {
        id: "q10",
        quizId: "quiz-g8-xia-unit-3",
        type: "fill-blank",
        difficulty: "challenge",
        stem: "矩形的一条对角线长为 10，一边长为 6。请填写另一边长度，并说明为什么这里可以转化为直角三角形问题。",
        blanks: [
          {
            id: "side",
            prompt: "另一边长度",
            hint: "矩形的一个角是直角。",
            acceptableAnswers: ["8"],
            placeholder: "请填写结果",
          },
          {
            id: "reason",
            prompt: "转化原因",
            hint: "矩形边与对角线构成直角三角形。",
            acceptableAnswers: ["矩形的边和对角线构成直角三角形", "有直角三角形"],
            placeholder: "请填写原因",
          },
        ],
        explanation: "矩形边与对角线构成直角三角形，所以另一边长为 8。",
        relatedLessonIds: ["lesson-g8x3-special"],
      },
    ],
  },
};
