import type { CurriculumSlice } from "@/types/content";

export const g8XiaUnit2Slice: CurriculumSlice = {
  grade: {
    id: "g8",
    label: "八年级",
    shortLabel: "八下",
    description: "从图形证明、代数运算与函数关系中提升推理能力。",
  },
  volume: {
    id: "xia",
    gradeId: "g8",
    label: "下册",
    description: "以二次根式、勾股定理、四边形与函数为主要内容的综合提升阶段。",
  },
  chapter: {
    id: "g8-xia-unit-2",
    gradeId: "g8",
    volumeId: "xia",
    slug: "gou-gu-ding-li",
    title: "第二章 勾股定理",
    summary: "理解勾股定理及其逆定理，会在直角三角形和实际情境中求边长与判断形状。",
    order: 2,
    lessonIds: ["lesson-g8x2-theorem", "lesson-g8x2-application"],
    workedExampleIds: ["example-g8x2-calc-side", "example-g8x2-judge-triangle"],
    quizId: "quiz-g8-xia-unit-2",
  },
  lessons: [
    {
      id: "lesson-g8x2-theorem",
      chapterId: "g8-xia-unit-2",
      slug: "gou-gu-ding-li-de-nei-rong",
      title: "勾股定理与逆定理",
      summary: "掌握直角三角形三边关系，会用平方关系判断一个三角形是否为直角三角形。",
      learningObjectives: [
        "会用 a²+b²=c² 求直角三角形未知边。",
        "能区分勾股定理和逆定理的使用场景。",
        "会用三边长度判断是否构成直角三角形。",
      ],
      keyRules: [
        "直角三角形中，两条直角边平方和等于斜边平方。",
        "若三边满足 a²+b²=c²，则这个三角形是直角三角形。",
        "斜边总是直角所对的最长边。",
      ],
      bodyBlocks: [
        {
          type: "richText",
          id: "g8x2-theorem-context",
          title: "先找哪条边是斜边",
          content: [
            "勾股定理题最容易错在把最长边认错，导致代入位置出错。",
            "看见平方关系时，要先确认是在“求边”还是在“判断形状”。",
          ],
        },
      ],
      relatedExampleIds: ["example-g8x2-calc-side"],
      order: 1,
      videoPlaceholder: {
        title: "板书微课：勾股定理和逆定理怎么区分",
        durationLabel: "5 分钟",
        description: "从“已知什么、要求什么”判断该用哪一个。",
      },
    },
    {
      id: "lesson-g8x2-application",
      chapterId: "g8-xia-unit-2",
      slug: "gou-gu-ding-li-de-shi-ji-ying-yong",
      title: "勾股定理的实际应用",
      summary: "会把梯子、航线、最短路径等问题转化为直角三角形求解。",
      learningObjectives: [
        "会在网格和实际情境中构造直角三角形。",
        "会利用勾股定理解决最短路径问题。",
        "能把实际长度关系抽象成数学模型。",
      ],
      keyRules: [
        "实际问题中要先识别或构造直角三角形。",
        "最短路径常常转化为直角边与斜边关系。",
        "单位统一后再代入公式更稳妥。",
      ],
      bodyBlocks: [
        {
          type: "tip",
          id: "g8x2-app-tip",
          title: "易错提醒",
          content: "很多应用题并没有直接给出直角符号，需要自己从水平、竖直或垂直关系中发现直角。",
        },
      ],
      relatedExampleIds: ["example-g8x2-judge-triangle"],
      order: 2,
      videoPlaceholder: {
        title: "板书微课：勾股定理如何落到实际场景",
        durationLabel: "6 分钟",
        description: "把文字信息转成边长与直角关系。",
      },
    },
  ],
  workedExamples: [
    {
      id: "example-g8x2-calc-side",
      chapterId: "g8-xia-unit-2",
      slug: "yi-zhi-liang-bian-qiu-di-san-bian",
      title: "例题 1：已知两边求第三边",
      summary: "在直角三角形中利用勾股定理求未知边。",
      problem: "在直角三角形中，两条直角边分别为 6 和 8，求斜边长度。",
      steps: [
        {
          id: "step-1",
          title: "列式",
          content: "设斜边为 c，则 c²=6²+8²。",
        },
        {
          id: "step-2",
          title: "计算",
          content: "c²=36+64=100，所以 c=10。",
        },
      ],
      answer: "10",
      commonMistakes: ["忘记斜边取正值。"],
      relatedLessonIds: ["lesson-g8x2-theorem"],
      order: 1,
    },
    {
      id: "example-g8x2-judge-triangle",
      chapterId: "g8-xia-unit-2",
      slug: "yong-san-bian-pan-duan-zhi-jiao",
      title: "例题 2：用逆定理判断形状",
      summary: "根据三边长度判断一个三角形是否为直角三角形。",
      problem: "一个三角形三边长分别为 5、12、13，判断它是否是直角三角形。",
      steps: [
        {
          id: "step-1",
          title: "找最长边",
          content: "最长边是 13。",
        },
        {
          id: "step-2",
          title: "验证平方关系",
          content: "5²+12²=25+144=169，13²=169。",
        },
        {
          id: "step-3",
          title: "下结论",
          content: "因为满足勾股定理逆定理，所以它是直角三角形。",
        },
      ],
      answer: "是直角三角形",
      commonMistakes: ["没有先找最长边就随意代入。"],
      relatedLessonIds: ["lesson-g8x2-theorem", "lesson-g8x2-application"],
      order: 2,
    },
  ],
  quiz: {
    id: "quiz-g8-xia-unit-2",
    chapterId: "g8-xia-unit-2",
    title: "第二章单元小测",
    instructions:
      "共 10 题，基础 2 题、进阶 4 题、压轴 4 题，整体难度明显上调，更强调多步推理、信息提取与综合应用。",
    passingScore: 80,
    questions: [
      {
        id: "q1",
        quizId: "quiz-g8-xia-unit-2",
        type: "single-choice",
        difficulty: "basic",
        stem: "在直角三角形中，两条直角边分别为 3 和 4，则斜边长是多少？",
        options: [
          { id: "a", label: "A", content: "5" },
          { id: "b", label: "B", content: "6" },
          { id: "c", label: "C", content: "7" },
          { id: "d", label: "D", content: "8" },
        ],
        correctOptionId: "a",
        explanation: "斜边长为 √(3²+4²)=5。",
        relatedLessonIds: ["lesson-g8x2-theorem"],
      },
      {
        id: "q2",
        quizId: "quiz-g8-xia-unit-2",
        type: "single-choice",
        difficulty: "basic",
        stem: "下列哪组三边长可以构成直角三角形？",
        options: [
          { id: "a", label: "A", content: "2、3、4" },
          { id: "b", label: "B", content: "6、8、10" },
          { id: "c", label: "C", content: "3、3、5" },
          { id: "d", label: "D", content: "5、5、6" },
        ],
        correctOptionId: "b",
        explanation: "6²+8²=10²，所以可以构成直角三角形。",
        relatedLessonIds: ["lesson-g8x2-theorem"],
      },
      {
        id: "q3",
        quizId: "quiz-g8-xia-unit-2",
        type: "fill-blank",
        difficulty: "advanced",
        stem: "一个直角三角形的斜边为 13，一条直角边为 5。请填写另一条直角边的长度，并说明你使用的是定理还是逆定理。",
        blanks: [
          {
            id: "side",
            prompt: "另一条直角边",
            hint: "利用 c²-a²=b²。",
            acceptableAnswers: ["12"],
            placeholder: "请填写结果",
          },
          {
            id: "rule",
            prompt: "依据相关关系，所用结论",
            hint: "先判断所用关系或方法，再这里是在已知直角三角形中求边。",
            acceptableAnswers: ["勾股定理"],
            placeholder: "请填写名称",
          },
        ],
        explanation: "依据题目中的条件和相关性质，另一条直角边为 √(13²-5²)=12，所用的是勾股定理。",
        relatedLessonIds: ["lesson-g8x2-theorem"],
      },
      {
        id: "q4",
        quizId: "quiz-g8-xia-unit-2",
        type: "single-choice",
        difficulty: "advanced",
        stem: "一个三角形三边长为 7、24、25，则这个三角形是哪个类型？",
        options: [
          { id: "a", label: "A", content: "锐角三角形" },
          { id: "b", label: "B", content: "钝角三角形" },
          { id: "c", label: "C", content: "直角三角形" },
          { id: "d", label: "D", content: "等腰三角形" },
        ],
        correctOptionId: "c",
        explanation: "7²+24²=25²，所以它是直角三角形。",
        relatedLessonIds: ["lesson-g8x2-theorem"],
      },
      {
        id: "q5",
        quizId: "quiz-g8-xia-unit-2",
        type: "fill-blank",
        difficulty: "advanced",
        stem: "一架梯子长 10 米，梯脚离墙 6 米。请填写梯顶到地面的高度，并判断这里把哪两个量看作直角边。",
        blanks: [
          {
            id: "height",
            prompt: "梯顶高度",
            hint: "梯子是斜边。",
            acceptableAnswers: ["8"],
            placeholder: "请填写结果",
          },
          {
            id: "legs",
            prompt: "两条直角边",
            hint: "水平距离与竖直高度。",
            acceptableAnswers: ["墙高和离墙距离", "高度和离墙距离"],
            placeholder: "请填写结果",
          },
        ],
        explanation: "高度为 √(10²-6²)=8，两条直角边是墙高和离墙距离。",
        relatedLessonIds: ["lesson-g8x2-application"],
      },
      {
        id: "q6",
        quizId: "quiz-g8-xia-unit-2",
        type: "single-choice",
        difficulty: "advanced",
        stem: "一块长方形草地长 9 米、宽 12 米，对角线长是多少？",
        options: [
          { id: "a", label: "A", content: "13 米" },
          { id: "b", label: "B", content: "14 米" },
          { id: "c", label: "C", content: "15 米" },
          { id: "d", label: "D", content: "16 米" },
        ],
        correctOptionId: "c",
        explanation: "对角线是直角三角形的斜边，长度为 √(9²+12²)=15。",
        relatedLessonIds: ["lesson-g8x2-application"],
      },
      {
        id: "q7",
        quizId: "quiz-g8-xia-unit-2",
        type: "fill-blank",
        difficulty: "challenge",
        stem: "在直角三角形中，两条边长分别为 8 和 17。若 17 是最长边，请填写第三边的长度，并判断这个三角形是否唯一确定。",
        blanks: [
          {
            id: "side",
            prompt: "第三边长度",
            hint: "17 是斜边。",
            acceptableAnswers: ["15"],
            placeholder: "请填写结果",
          },
          {
            id: "unique",
            prompt: "是否唯一确定",
            hint: "已知斜边和一条直角边。",
            acceptableAnswers: ["是"],
            placeholder: "请填写判断",
          },
        ],
        explanation: "第三边为 √(17²-8²)=15；已知斜边与一条直角边后，直角三角形唯一确定。",
        relatedLessonIds: ["lesson-g8x2-theorem"],
      },
      {
        id: "q8",
        quizId: "quiz-g8-xia-unit-2",
        type: "single-choice",
        difficulty: "challenge",
        stem: "若一个三角形三边长分别为 x、15、17，且它是直角三角形，则 x 可能是多少？",
        options: [
          { id: "a", label: "A", content: "6" },
          { id: "b", label: "B", content: "7" },
          { id: "c", label: "C", content: "8" },
          { id: "d", label: "D", content: "9" },
        ],
        correctOptionId: "c",
        explanation: "若 17 为斜边，则 x²+15²=17²，所以 x²=64，x=8。",
        relatedLessonIds: ["lesson-g8x2-theorem"],
      },
      {
        id: "q9",
        quizId: "quiz-g8-xia-unit-2",
        type: "fill-blank",
        difficulty: "challenge",
        stem: "某人从 A 点向东走 6 米，再向北走 8 米到 B 点。请填写 AB 的长度，并说明这道题为什么可以转化为勾股定理问题。",
        blanks: [
          {
            id: "distance",
            prompt: "AB 的长度",
            hint: "向东、向北互相垂直。",
            acceptableAnswers: ["10"],
            placeholder: "请填写结果",
          },
          {
            id: "reason",
            prompt: "转化原因",
            hint: "两段路互相垂直。",
            acceptableAnswers: ["构成直角三角形", "东西方向和南北方向垂直构成直角三角形"],
            placeholder: "请填写原因",
          },
        ],
        explanation: "因为向东和向北互相垂直，所以构成直角三角形，AB=10。",
        relatedLessonIds: ["lesson-g8x2-application"],
      },
      {
        id: "q10",
        quizId: "quiz-g8-xia-unit-2",
        type: "fill-blank",
        difficulty: "challenge",
        stem: "一个三角形三边分别为 9、12、15。请填写它是否为直角三角形，并写出用于判断的平方关系。",
        blanks: [
          {
            id: "judge",
            prompt: "是否为直角三角形",
            hint: "先看最长边。",
            acceptableAnswers: ["是"],
            placeholder: "请填写判断",
          },
          {
            id: "equation",
            prompt: "平方关系",
            hint: "把最短两边平方和与最长边平方比较。",
            acceptableAnswers: ["9²+12²=15²", "81+144=225"],
            placeholder: "请填写关系",
          },
        ],
        explanation: "9²+12²=15²，因此它是直角三角形。",
        relatedLessonIds: ["lesson-g8x2-theorem", "lesson-g8x2-application"],
      },
    ],
  },
};
