import type { CurriculumSlice } from "@/types/content";
import { createExpressionFigure } from "./quiz-figures";

export const g9ShangUnit2Slice: CurriculumSlice = {
  grade: {
    id: "g9",
    label: "九年级",
    shortLabel: "九上",
    description: "围绕方程、函数与几何综合应用，进入中考主干能力训练阶段。",
  },
  volume: {
    id: "shang",
    gradeId: "g9",
    label: "上册",
    description: "以一元二次方程、二次函数和圆的基础应用为主要内容。",
  },
  chapter: {
    id: "g9-shang-unit-2",
    gradeId: "g9",
    volumeId: "shang",
    slug: "er-ci-han-shu",
    title: "第二章 二次函数",
    summary: "理解二次函数图象与解析式的关系，会求顶点、判断增减性并解决基础应用问题。",
    order: 2,
    lessonIds: ["lesson-g9s2-quadratic-image", "lesson-g9s2-parabola-application"],
    workedExampleIds: ["example-g9s2-vertex-form", "example-g9s2-max-area"],
    quizId: "quiz-g9-shang-unit-2",
  },
  lessons: [
    {
      id: "lesson-g9s2-quadratic-image",
      chapterId: "g9-shang-unit-2",
      slug: "er-ci-han-shu-tu-xiang-yu-xing-zhi",
      title: "二次函数图象与性质",
      summary: "会根据解析式判断开口方向、顶点和对称轴，理解增减性与最值。",
      learningObjectives: [
        "能由 a 的符号判断抛物线开口方向。",
        "会由顶点式看出顶点和对称轴。",
        "会结合图象判断函数最值和增减区间。",
      ],
      keyRules: [
        "y = a(x - h)² + k 的顶点是 (h, k)。",
        "a > 0 时开口向上，a < 0 时开口向下。",
        "对称轴是 x = h。",
      ],
      bodyBlocks: [
        {
          type: "richText",
          id: "g9s2-image-context",
          title: "先看顶点式最省力",
          content: [
            "很多二次函数只要整理成顶点式，就能直接读出顶点、对称轴和开口方向。",
            "图象性质题不要只记图形，要把解析式和图形对应起来。",
          ],
        },
        {
          type: "formula",
          id: "g9s2-image-formula",
          title: "顶点式",
          formulas: ["y = a(x - h)² + k", "顶点：(h, k)", "对称轴：x = h"],
          note: "看顶点式时，括号里是减 h，不是直接读成负号。",
        },
        {
          type: "tip",
          id: "g9s2-image-tip",
          title: "易错提醒",
          content: "y = (x + 2)² - 3 的顶点是 (-2, -3)，不是 (2, -3)。",
        },
      ],
      relatedExampleIds: ["example-g9s2-vertex-form"],
      order: 1,
      videoPlaceholder: {
        title: "板书微课：二次函数看图像",
        durationLabel: "5 分钟",
        description: "用顶点式一口气抓住图象三大信息。",
      },
    },
    {
      id: "lesson-g9s2-parabola-application",
      chapterId: "g9-shang-unit-2",
      slug: "er-ci-han-shu-ying-yong",
      title: "二次函数的简单应用",
      summary: "会把面积、利润、距离等问题转化为二次函数，借助最值解决实际问题。",
      learningObjectives: [
        "会建立简单二次函数模型。",
        "能用顶点或配方求最值。",
        "会解释最值在实际问题中的含义。",
      ],
      keyRules: [
        "二次函数的最值出现在顶点处。",
        "开口向上时顶点对应最小值，开口向下时顶点对应最大值。",
        "建模时先明确自变量和函数值分别表示什么。",
      ],
      bodyBlocks: [
        {
          type: "richText",
          id: "g9s2-app-context",
          title: "把实际问题翻译成函数式",
          content: [
            "应用题里先不要急着求值，要先确定哪个量会变化，哪个量由它决定。",
            "一旦得到二次函数解析式，最值问题通常就转化为找顶点。",
          ],
        },
        {
          type: "formula",
          id: "g9s2-app-formula",
          title: "常见思路",
          formulas: ["面积 = 长 × 宽", "利润 = 单件利润 × 销量", "最值看顶点"],
          note: "先列函数关系，再判断定义域，最后解释答案。",
        },
        {
          type: "tip",
          id: "g9s2-app-tip",
          title: "易错提醒",
          content: "顶点给出的极值不一定都符合实际，还要检查题目给出的取值范围。",
        },
      ],
      relatedExampleIds: ["example-g9s2-max-area"],
      order: 2,
      videoPlaceholder: {
        title: "板书微课：二次函数最值应用",
        durationLabel: "6 分钟",
        description: "从函数关系式过渡到实际意义。",
      },
    },
  ],
  workedExamples: [
    {
      id: "example-g9s2-vertex-form",
      chapterId: "g9-shang-unit-2",
      slug: "ding-dian-shi-du-qu-xin-xi",
      title: "例题 1：从顶点式读图象信息",
      summary: "直接根据顶点式判断顶点、对称轴和开口方向。",
      problem: "已知二次函数 y = -2(x - 1)² + 5，写出它的顶点、对称轴，并判断开口方向。",
      steps: [
        { id: "step-1", title: "读顶点", content: "由 y = a(x - h)² + k 可知顶点是 (1, 5)。" },
        { id: "step-2", title: "读对称轴", content: "对称轴是 x = 1。" },
        { id: "step-3", title: "看 a 的符号", content: "a = -2 < 0，所以抛物线开口向下。" },
      ],
      answer: "顶点 (1, 5)，对称轴 x = 1，开口向下",
      commonMistakes: ["把顶点横坐标看成 -1。", "只看顶点不判断开口方向。"],
      relatedLessonIds: ["lesson-g9s2-quadratic-image"],
      order: 1,
    },
    {
      id: "example-g9s2-max-area",
      chapterId: "g9-shang-unit-2",
      slug: "li-yong-ding-dian-qiu-zui-zhi",
      title: "例题 2：利用顶点求最值",
      summary: "把面积问题转化成二次函数，借顶点求最大值。",
      problem: "某矩形一边长为 x，另一边长为 12 - x，面积 S = x(12 - x)。求面积的最大值。",
      steps: [
        { id: "step-1", title: "列函数式", content: "S = x(12 - x) = -x² + 12x。" },
        { id: "step-2", title: "化为顶点式", content: "S = -(x - 6)² + 36。" },
        { id: "step-3", title: "读最值", content: "因为开口向下，所以最大值是 36。" },
      ],
      answer: "最大面积为 36",
      commonMistakes: ["列出函数式后不会转成顶点式。", "没有利用开口方向判断最大值。"],
      relatedLessonIds: ["lesson-g9s2-parabola-application"],
      order: 2,
    },
  ],
  quiz: {
    id: "quiz-g9-shang-unit-2",
    chapterId: "g9-shang-unit-2",
    title: "第二章单元小测",
    instructions:
      "共 10 题，基础 2 题、进阶 4 题、压轴 4 题，整体难度明显上调，更强调多步推理、信息提取与综合应用。",
    passingScore: 80,
    questions: [
      {
        id: "q1",
        quizId: "quiz-g9-shang-unit-2",
        type: "single-choice",
        difficulty: "basic",
        stem: "函数 y = (x - 2)² + 3 的顶点坐标是哪个？",
        options: [
          { id: "a", label: "A", content: "(2, 3)" },
          { id: "b", label: "B", content: "(-2, 3)" },
          { id: "c", label: "C", content: "(2, -3)" },
          { id: "d", label: "D", content: "(-2, -3)" },
        ],
        correctOptionId: "a",
        explanation: "顶点式 y = a(x - h)² + k 的顶点是 (h, k)。",
        relatedLessonIds: ["lesson-g9s2-quadratic-image"],
      },
      {
        id: "q2",
        quizId: "quiz-g9-shang-unit-2",
        type: "single-choice",
        difficulty: "basic",
        stem: "若二次函数 y = -x² + 1，则它的图象开口方向是哪个？",
        options: [
          { id: "a", label: "A", content: "向上" },
          { id: "b", label: "B", content: "向下" },
          { id: "c", label: "C", content: "先上后下" },
          { id: "d", label: "D", content: "无法判断" },
        ],
        correctOptionId: "b",
        explanation: "二次项系数 a < 0，所以抛物线开口向下。",
        relatedLessonIds: ["lesson-g9s2-quadratic-image"],
      },
      {
        id: "q3",
        quizId: "quiz-g9-shang-unit-2",
        type: "fill-blank",
        difficulty: "advanced",
        stem: "已知函数 y = 2(x - 1)² - 5。请填写它的对称轴和最小值。",
        blanks: [
          {
            id: "axis",
            prompt: "对称轴",
            hint: "顶点式里括号中的 h 决定对称轴。",
            acceptableAnswers: ["x=1", "x = 1"],
            placeholder: "请填写结果",
          },
          {
            id: "min",
            prompt: "依据相关关系，最小值",
            hint: "先判断所用关系或方法，再a > 0 时，顶点纵坐标就是最小值。",
            acceptableAnswers: ["-5"],
            placeholder: "请填写结果",
          },
        ],
        explanation: "依据题目中的条件和相关性质，顶点是 (1, -5)，对称轴是 x = 1，且开口向上，所以最小值是 -5。",
        relatedLessonIds: ["lesson-g9s2-quadratic-image"],
      },
      {
        id: "q4",
        quizId: "quiz-g9-shang-unit-2",
        type: "single-choice",
        difficulty: "advanced",
        stem: "函数 y = -x² + 4x - 3 的顶点横坐标是多少？",
        options: [
          { id: "a", label: "A", content: "1" },
          { id: "b", label: "B", content: "2" },
          { id: "c", label: "C", content: "3" },
          { id: "d", label: "D", content: "4" },
        ],
        correctOptionId: "b",
        explanation: "可配方得 y = -(x - 2)² + 1，因此顶点横坐标是 2。",
        relatedLessonIds: ["lesson-g9s2-quadratic-image"],
      },
      {
        id: "q5",
        quizId: "quiz-g9-shang-unit-2",
        type: "fill-blank",
        difficulty: "advanced",
        stem: "把函数 y = x² - 6x + 5 配方成顶点式，并填写顶点坐标。",
        blanks: [
          {
            id: "form",
            prompt: "顶点式",
            hint: "先提出平方项，再补成完全平方。",
            acceptableAnswers: ["y=(x-3)^2-4", "y=(x-3)²-4", "y = (x - 3)^2 - 4", "y = (x - 3)² - 4"],
            placeholder: "请填写结果",
          },
          {
            id: "vertex",
            prompt: "顶点坐标",
            hint: "看顶点式中的 h 和 k。",
            acceptableAnswers: ["(3,-4)", "(3, -4)"],
            placeholder: "请填写坐标",
          },
        ],
        explanation: "x² - 6x + 5 = (x - 3)² - 4，所以顶点是 (3, -4)。",
        relatedLessonIds: ["lesson-g9s2-quadratic-image"],
      },
      {
        id: "q6",
        quizId: "quiz-g9-shang-unit-2",
        type: "single-choice",
        difficulty: "advanced",
        stem: "矩形面积 S = x(10 - x)。当 x 取哪个值时，面积最大？",
        options: [
          { id: "a", label: "A", content: "4" },
          { id: "b", label: "B", content: "5" },
          { id: "c", label: "C", content: "6" },
          { id: "d", label: "D", content: "10" },
        ],
        correctOptionId: "b",
        explanation: "S = -x² + 10x = -(x - 5)² + 25，顶点横坐标为 5，因此面积最大时 x = 5。",
        relatedLessonIds: ["lesson-g9s2-parabola-application"],
      },
      {
        id: "q7",
        quizId: "quiz-g9-shang-unit-2",
        type: "fill-blank",
        difficulty: "challenge",
        stem: "若二次函数 y = a(x - 2)² + 7 的图象经过点 (3, 5)，请先求 a，再写出函数开口方向。",
        blanks: [
          {
            id: "a",
            prompt: "a 的值",
            hint: "把点 (3, 5) 代入解析式。",
            acceptableAnswers: ["-2"],
            placeholder: "请填写结果",
          },
          {
            id: "direction",
            prompt: "开口方向",
            hint: "看 a 的符号。",
            acceptableAnswers: ["向下", "开口向下"],
            placeholder: "请填写结果",
          },
        ],
        explanation: "代入得 5 = a(3 - 2)² + 7，所以 a = -2；a < 0，图象开口向下。",
        relatedLessonIds: ["lesson-g9s2-quadratic-image"],
      },
      {
        id: "q8",
        quizId: "quiz-g9-shang-unit-2",
        type: "single-choice",
        difficulty: "challenge",
        stem: "已知抛物线 y = -(x - 1)² + 4 上有两点 A、B，它们的横坐标分别为 -1 和 3，则 A、B 两点纵坐标有什么关系？",
        options: [
          { id: "a", label: "A", content: "A 点纵坐标大" },
          { id: "b", label: "B", content: "B 点纵坐标大" },
          { id: "c", label: "C", content: "纵坐标相等" },
          { id: "d", label: "D", content: "无法判断" },
        ],
        correctOptionId: "c",
        explanation: "-1 和 3 关于对称轴 x = 1 对称，所以对应的函数值相等。",
        relatedLessonIds: ["lesson-g9s2-quadratic-image"],
      },
      {
        id: "q9",
        quizId: "quiz-g9-shang-unit-2",
        type: "fill-blank",
        difficulty: "challenge",
        stem: "如图，整式结构图表示二次函数 y = x² - 4x + 3 的三个部分。请先写出配方后的顶点式，再写出它的最小值。",
        figure: createExpressionFigure("二次函数 x² - 4x + 3 的结构示意图。", "x²-4x+3", "x²", "-4x", "3"),
        blanks: [
          {
            id: "vertex-form",
            prompt: "顶点式",
            hint: "先补成完全平方。",
            acceptableAnswers: ["y=(x-2)^2-1", "y=(x-2)²-1", "y = (x - 2)^2 - 1", "y = (x - 2)² - 1"],
            placeholder: "请填写结果",
          },
          {
            id: "min",
            prompt: "最小值",
            hint: "开口向上时，最小值看顶点纵坐标。",
            acceptableAnswers: ["-1"],
            placeholder: "请填写结果",
          },
        ],
        explanation: "x² - 4x + 3 = (x - 2)² - 1，所以最小值是 -1。",
        relatedLessonIds: ["lesson-g9s2-quadratic-image", "lesson-g9s2-parabola-application"],
      },
      {
        id: "q10",
        quizId: "quiz-g9-shang-unit-2",
        type: "fill-blank",
        difficulty: "challenge",
        stem: "某商品每件利润与降价幅度 x（元）满足 P = -x² + 8x + 9。请填写利润的最大值，以及取得最大值时的 x。",
        blanks: [
          {
            id: "max-profit",
            prompt: "最大利润",
            hint: "先把函数配方成顶点式。",
            acceptableAnswers: ["25"],
            placeholder: "请填写结果",
          },
          {
            id: "x-value",
            prompt: "对应的 x",
            hint: "最大值出现在顶点横坐标。",
            acceptableAnswers: ["4"],
            placeholder: "请填写结果",
          },
        ],
        explanation: "-x² + 8x + 9 = -(x - 4)² + 25，所以最大利润是 25，在 x = 4 时取得。",
        relatedLessonIds: ["lesson-g9s2-parabola-application"],
      },
    ],
  },
};
