import type { CurriculumSlice } from "@/types/content";

export const g9ShangUnit3Slice: CurriculumSlice = {
  grade: {
    id: "g9",
    label: "九年级",
    shortLabel: "九上",
    description: "围绕方程、函数与几何综合应用，进入中考主干能力训练阶段。",
  },
  volume: {
    id: "shang",
    gradeId: "g9",
    label: "上册",
    description: "以一元二次方程、函数与几何变换为主要内容。",
  },
  chapter: {
    id: "g9-shang-unit-3",
    gradeId: "g9",
    volumeId: "shang",
    slug: "xuan-zhuan",
    title: "第三章 旋转",
    summary: "理解旋转的基本性质，会判断对应点、对应线段与对应角，并能解决简单的图形变换问题。",
    order: 3,
    lessonIds: ["lesson-g9s3-rotation-concept", "lesson-g9s3-rotation-application"],
    workedExampleIds: ["example-g9s3-identify", "example-g9s3-coordinate"],
    quizId: "quiz-g9-shang-unit-3",
  },
  lessons: [
    {
      id: "lesson-g9s3-rotation-concept",
      chapterId: "g9-shang-unit-3",
      slug: "xuan-zhuan-de-ji-ben-xing-zhi",
      title: "旋转的基本性质",
      summary: "掌握旋转中心、旋转角和对应点关系，理解旋转前后图形全等。",
      learningObjectives: ["能识别旋转中心和旋转角。", "知道旋转前后对应线段、对应角分别相等。", "理解旋转是一种全等变换。"],
      keyRules: ["旋转不改变图形的形状和大小。", "对应点到旋转中心距离相等。", "对应线段夹角等于旋转角。"],
      bodyBlocks: [{ type: "richText", id: "g9s3-rot-context", title: "先抓中心再抓角", content: ["判断旋转时，最关键的信息是：绕哪个点转、转了多少度。", "只看“像不像”不够，要结合中心和角度去确认。"] }],
      relatedExampleIds: ["example-g9s3-identify"],
      order: 1,
      videoPlaceholder: { title: "板书微课：旋转题先看哪两个量", durationLabel: "5 分钟", description: "用旋转中心和旋转角串起整章核心。" },
    },
    {
      id: "lesson-g9s3-rotation-application",
      chapterId: "g9-shang-unit-3",
      slug: "xuan-zhuan-zuo-tu-yu-zuo-biao",
      title: "旋转作图与坐标应用",
      summary: "会处理简单的旋转作图和坐标变化问题，理解特殊角旋转后的常见结果。",
      learningObjectives: ["会处理 90°、180° 旋转的常见情形。", "能根据坐标判断旋转后的点位变化。", "会利用旋转关系求角或线段。"],
      keyRules: ["绕原点旋转 180°： (x, y) → (-x, -y)。", "特殊角旋转常与垂直、平行、对称相联系。", "旋转问题常可转化为全等或等长关系。"],
      bodyBlocks: [{ type: "richText", id: "g9s3-rot-app", title: "特殊角最值得熟练", content: ["90° 和 180° 旋转是最常见的考法。", "遇到坐标题时，先用图形变换关系判断方向，再写坐标。"] }],
      relatedExampleIds: ["example-g9s3-coordinate"],
      order: 2,
      videoPlaceholder: { title: "板书微课：坐标中的旋转怎么想", durationLabel: "6 分钟", description: "把特殊角旋转变成坐标变化规律。" },
    },
  ],
  workedExamples: [
    { id: "example-g9s3-identify", chapterId: "g9-shang-unit-3", slug: "pan-duan-dui-ying-guan-xi", title: "例题 1：判断旋转对应关系", summary: "利用旋转中心和角度判断对应边角。", problem: "△ABC 绕点 O 旋转后得到 △A'B'C'。若旋转角为 60°，写出与边 AB 对应的边，并说明 ∠AOB 与 ∠A'OB' 的关系。", steps: [{ id: "step-1", title: "找对应边", content: "由点的对应关系可知 AB 对应 A'B'。" }, { id: "step-2", title: "看中心角", content: "对应点与旋转中心构成的角等于旋转角。" }, { id: "step-3", title: "写结论", content: "所以 ∠AOB = ∠A'OB' = 60°。" }], answer: "对应边是 A'B'，两个中心角都等于 60°", commonMistakes: ["只写对应边，不说明角度关系。"], relatedLessonIds: ["lesson-g9s3-rotation-concept"], order: 1 },
    { id: "example-g9s3-coordinate", chapterId: "g9-shang-unit-3", slug: "te-shu-jiao-xuan-zhuan", title: "例题 2：坐标中的旋转", summary: "处理绕原点旋转 180° 的点坐标变化。", problem: "点 P(2, -3) 绕原点旋转 180° 后到达点 P'，求 P' 坐标。", steps: [{ id: "step-1", title: "识别特殊角", content: "绕原点旋转 180° 时，横纵坐标同时变成相反数。" }, { id: "step-2", title: "写出新坐标", content: "因此 P'( -2, 3 )。" }], answer: "(-2, 3)", commonMistakes: ["只改一个坐标符号。"], relatedLessonIds: ["lesson-g9s3-rotation-application"], order: 2 },
  ],
  quiz: {
    id: "quiz-g9-shang-unit-3",
    chapterId: "g9-shang-unit-3",
    title: "第三章单元小测",
    instructions: "共 10 题，基础 2 题、进阶 4 题、压轴 4 题，整体难度明显上调，更强调多步推理、信息提取与综合应用。",
    passingScore: 80,
    questions: [
      { id: "q1", quizId: "quiz-g9-shang-unit-3", type: "single-choice", difficulty: "basic", stem: "旋转前后图形的哪一项不变？", options: [{ id: "a", label: "A", content: "形状和大小" }, { id: "b", label: "B", content: "位置" }, { id: "c", label: "C", content: "方向一定不变" }, { id: "d", label: "D", content: "坐标一定不变" }], correctOptionId: "a", explanation: "旋转是全等变换，形状和大小不变。", relatedLessonIds: ["lesson-g9s3-rotation-concept"] },
      { id: "q2", quizId: "quiz-g9-shang-unit-3", type: "single-choice", difficulty: "basic", stem: "点 P(1,2) 绕原点旋转 180° 后的对应点是哪个？", options: [{ id: "a", label: "A", content: "(1,-2)" }, { id: "b", label: "B", content: "(-1,-2)" }, { id: "c", label: "C", content: "(-1,2)" }, { id: "d", label: "D", content: "(2,1)" }], correctOptionId: "b", explanation: "绕原点旋转 180°，坐标变为相反数。", relatedLessonIds: ["lesson-g9s3-rotation-application"] },
      { id: "q3", quizId: "quiz-g9-shang-unit-3", type: "fill-blank", difficulty: "advanced", stem: "若线段 OA 绕点 O 旋转 90° 到 OA'，且 OA=5，请填写 OA' 的长度，并写出 ∠AOA' 的大小。", blanks: [{ id: "len", prompt: "OA' 的长度", hint: "旋转不改变长度。", acceptableAnswers: ["5"], placeholder: "请填写结果" }, { id: "angle", prompt: "依据相关关系，∠AOA' 的大小", hint: "先判断所用关系或方法，再中心角等于旋转角。", acceptableAnswers: ["90°", "90"], placeholder: "请填写结果" }], explanation: "依据题目中的条件和相关性质，旋转前后对应线段相等，中心角等于旋转角。", relatedLessonIds: ["lesson-g9s3-rotation-concept"] },
      { id: "q4", quizId: "quiz-g9-shang-unit-3", type: "single-choice", difficulty: "advanced", stem: "△ABC 旋转后得到 △DEF，若 B 对应 E，C 对应 F，则边 AC 对应哪条边？", options: [{ id: "a", label: "A", content: "DE" }, { id: "b", label: "B", content: "DF" }, { id: "c", label: "C", content: "EF" }, { id: "d", label: "D", content: "无法判断" }], correctOptionId: "b", explanation: "A 对应 D，C 对应 F，所以 AC 对应 DF。", relatedLessonIds: ["lesson-g9s3-rotation-concept"] },
      { id: "q5", quizId: "quiz-g9-shang-unit-3", type: "fill-blank", difficulty: "advanced", stem: "点 M(3,-1) 绕原点旋转 180° 后到点 N。请写出 N 的坐标，并判断 N 在第几象限。", blanks: [{ id: "coord", prompt: "N 的坐标", hint: "横纵坐标都变成相反数。", acceptableAnswers: ["(-3,1)", "(-3, 1)"], placeholder: "请填写坐标" }, { id: "quadrant", prompt: "所在象限", hint: "横负纵正。", acceptableAnswers: ["第二象限"], placeholder: "请填写结果" }], explanation: "旋转后坐标为 (-3,1)，位于第二象限。", relatedLessonIds: ["lesson-g9s3-rotation-application"] },
      { id: "q6", quizId: "quiz-g9-shang-unit-3", type: "single-choice", difficulty: "advanced", stem: "一个图形绕某点旋转后与原图形重合，下列说法正确的是哪个？", options: [{ id: "a", label: "A", content: "一定旋转了 0°" }, { id: "b", label: "B", content: "可能旋转了某个特殊角度" }, { id: "c", label: "C", content: "图形一定是圆" }, { id: "d", label: "D", content: "图形大小发生改变" }], correctOptionId: "b", explanation: "一些有旋转对称性的图形绕特殊角度旋转后也会与原图形重合。", relatedLessonIds: ["lesson-g9s3-rotation-concept"] },
      { id: "q7", quizId: "quiz-g9-shang-unit-3", type: "fill-blank", difficulty: "challenge", stem: "已知点 A(1,0) 绕原点逆时针旋转 180° 到点 B，再将点 B 向上平移 2 个单位到点 C。请写出 C 的坐标，并判断 BC 是否平行于 y 轴。", blanks: [{ id: "coord", prompt: "C 的坐标", hint: "先旋转，再平移。", acceptableAnswers: ["(-1,2)", "(-1, 2)"], placeholder: "请填写坐标" }, { id: "parallel", prompt: "BC 是否平行于 y 轴", hint: "看横坐标是否相同。", acceptableAnswers: ["是"], placeholder: "请填写判断" }], explanation: "A 旋转后到 B(-1,0)，再上移 2 到 C(-1,2)，BC 平行于 y 轴。", relatedLessonIds: ["lesson-g9s3-rotation-application"] },
      { id: "q8", quizId: "quiz-g9-shang-unit-3", type: "single-choice", difficulty: "challenge", stem: "若线段 AB 绕点 O 旋转 60° 到 A'B'，则下列结论一定成立的是哪个？", options: [{ id: "a", label: "A", content: "AB ∥ A'B'" }, { id: "b", label: "B", content: "AB = A'B'" }, { id: "c", label: "C", content: "∠BAB' = 60°" }, { id: "d", label: "D", content: "点 A 在点 B 上" }], correctOptionId: "b", explanation: "旋转保持长度不变，所以对应线段相等。", relatedLessonIds: ["lesson-g9s3-rotation-concept"] },
      { id: "q9", quizId: "quiz-g9-shang-unit-3", type: "fill-blank", difficulty: "challenge", stem: "在正方形中，一个顶点绕中心旋转 90° 到另一个顶点。请填写旋转后距离中心的长度关系，并写出图形面积是否改变。", blanks: [{ id: "relation", prompt: "距离中心的长度关系", hint: "对应点到旋转中心距离相等。", acceptableAnswers: ["相等"], placeholder: "请填写结果" }, { id: "area", prompt: "面积是否改变", hint: "旋转是全等变换。", acceptableAnswers: ["不变"], placeholder: "请填写结果" }], explanation: "旋转前后对应点到中心距离相等，图形面积也不变。", relatedLessonIds: ["lesson-g9s3-rotation-concept"] },
      { id: "q10", quizId: "quiz-g9-shang-unit-3", type: "fill-blank", difficulty: "challenge", stem: "点 P(a,b) 绕原点旋转 180° 后到点 Q，且 Q 的坐标为 (-4,3)。请求 a、b 的值。", blanks: [{ id: "a", prompt: "a 的值", hint: "旋转 180° 前后横坐标互为相反数。", acceptableAnswers: ["4"], placeholder: "请填写结果" }, { id: "b", prompt: "b 的值", hint: "纵坐标也互为相反数。", acceptableAnswers: ["-3"], placeholder: "请填写结果" }], explanation: "旋转 180° 后 (a,b) 变为 (-a,-b)=(-4,3)，所以 a=4，b=-3。", relatedLessonIds: ["lesson-g9s3-rotation-application"] },
    ],
  },
};
