import type { CurriculumSlice } from "@/types/content";

export const g9ShangUnit5Slice: CurriculumSlice = {
  grade: {
    id: "g9",
    label: "九年级",
    shortLabel: "九上",
    description: "围绕方程、函数与几何综合应用，进入中考主干能力训练阶段。",
  },
  volume: {
    id: "shang",
    gradeId: "g9",
    label: "上册",
    description: "以一元二次方程、函数、圆与概率建模为主要内容。",
  },
  chapter: {
    id: "g9-shang-unit-5",
    gradeId: "g9",
    volumeId: "shang",
    slug: "gai-lu-chu-bu",
    title: "第五章 概率初步",
    summary:
      "理解随机事件、频率与概率的关系，会用列举法和树状图法求简单事件概率，并进行基础判断。",
    order: 5,
    lessonIds: ["lesson-g9s5-random-event", "lesson-g9s5-listing-probability"],
    workedExampleIds: ["example-g9s5-coin-dice", "example-g9s5-tree-diagram"],
    quizId: "quiz-g9-shang-unit-5",
  },
  lessons: [
    {
      id: "lesson-g9s5-random-event",
      chapterId: "g9-shang-unit-5",
      slug: "sui-ji-shi-jian-yu-gai-lu",
      title: "随机事件与概率",
      summary: "理解必然事件、不可能事件和随机事件，会根据等可能结果求简单概率。",
      learningObjectives: [
        "会区分必然事件、不可能事件和随机事件。",
        "知道概率的取值范围在 0 到 1 之间。",
        "会在等可能情形下用结果数求概率。",
      ],
      keyRules: [
        "概率 = 有利结果数 / 全部等可能结果数。",
        "必然事件的概率是 1，不可能事件的概率是 0。",
        "频率随试验次数增大，通常会稳定在概率附近。",
      ],
      bodyBlocks: [
        {
          type: "richText",
          id: "g9s5-random-context",
          title: "先判断是不是等可能",
          content: [
            "概率题最容易错在把“不等可能”当成“等可能”处理。",
            "在套公式之前，要先确认每个基本结果出现的机会是否一样。",
          ],
        },
        {
          type: "formula",
          id: "g9s5-random-formula",
          title: "核心表达",
          formulas: ["P(A)=m/n", "0≤P(A)≤1", "频率≈概率"],
          note: "只有在结果等可能时，才能直接用有利结果数除以总结果数。",
        },
      ],
      relatedExampleIds: ["example-g9s5-coin-dice"],
      order: 1,
      videoPlaceholder: {
        title: "板书微课：概率公式什么时候能直接用",
        durationLabel: "5 分钟",
        description: "从等可能前提出发理解概率。",
      },
    },
    {
      id: "lesson-g9s5-listing-probability",
      chapterId: "g9-shang-unit-5",
      slug: "lie-ju-fa-yu-shu-zhuang-tu",
      title: "列举法与树状图法",
      summary: "会用列表法、树状图法分析两步试验中的所有结果，并求复合事件概率。",
      learningObjectives: [
        "会用列表法整理两次试验的全部结果。",
        "会用树状图法避免漏写和重复计数。",
        "会求“和”“积”“至少”等常见事件的概率。",
      ],
      keyRules: [
        "两步试验常用列表法或树状图法列出全部结果。",
        "列举完成后再统计有利结果，能有效避免漏算。",
        "求“至少一次”时，可以转化为“1 减去一次也没有”。",
      ],
      bodyBlocks: [
        {
          type: "richText",
          id: "g9s5-list-context",
          title: "复合事件先把样本空间写全",
          content: [
            "两次摸球、两次掷骰子这类题，难点往往不是计算，而是是否把情况列全。",
            "一旦样本空间完整，后面的概率统计就会稳定很多。",
          ],
        },
        {
          type: "tip",
          id: "g9s5-list-tip",
          title: "易错提醒",
          content: "“先后顺序有关”时，(红,白) 和 (白,红) 不是同一种结果。",
        },
      ],
      relatedExampleIds: ["example-g9s5-tree-diagram"],
      order: 2,
      videoPlaceholder: {
        title: "板书微课：两步试验怎样列举不漏不重",
        durationLabel: "6 分钟",
        description: "用列表法和树状图法锁定全部结果。",
      },
    },
  ],
  workedExamples: [
    {
      id: "example-g9s5-coin-dice",
      chapterId: "g9-shang-unit-5",
      slug: "ying-bi-yu-tou-zi",
      title: "例题 1：硬币与骰子",
      summary: "用等可能结果模型求简单概率。",
      problem: "抛一枚硬币并掷一次骰子，求“硬币正面朝上且骰子点数大于 4”的概率。",
      steps: [
        {
          id: "step-1",
          title: "确定总结果数",
          content: "硬币有 2 种结果，骰子有 6 种结果，共有 2×6=12 种等可能结果。",
        },
        {
          id: "step-2",
          title: "统计有利结果",
          content: "硬币正面朝上且骰子点数大于 4，对应骰子为 5 或 6，共 2 种。",
        },
        {
          id: "step-3",
          title: "求概率",
          content: "所以所求概率为 2/12=1/6。",
        },
      ],
      answer: "1/6",
      commonMistakes: ["只统计骰子的结果，忽略硬币也会带来分类。"],
      relatedLessonIds: ["lesson-g9s5-random-event"],
      order: 1,
    },
    {
      id: "example-g9s5-tree-diagram",
      chapterId: "g9-shang-unit-5",
      slug: "shu-zhuang-tu-qiu-gai-lu",
      title: "例题 2：树状图分析两步试验",
      summary: "用树状图法求两次转盘试验的复合事件概率。",
      problem: "一个转盘被平均分成 3 个区域，分别标有 1、2、3。连续转动两次，求两次所得数字之和为 4 的概率。",
      steps: [
        {
          id: "step-1",
          title: "列出全部结果",
          content: "两次转动共有 3×3=9 种等可能结果，可用树状图写成有序数对。",
        },
        {
          id: "step-2",
          title: "找出有利结果",
          content: "和为 4 的结果有 (1,3)、(2,2)、(3,1)，共 3 种。",
        },
        {
          id: "step-3",
          title: "写出概率",
          content: "所求概率为 3/9=1/3。",
        },
      ],
      answer: "1/3",
      commonMistakes: ["把 (1,3) 和 (3,1) 当成同一个结果。"],
      relatedLessonIds: ["lesson-g9s5-listing-probability"],
      order: 2,
    },
  ],
  quiz: {
    id: "quiz-g9-shang-unit-5",
    chapterId: "g9-shang-unit-5",
    title: "第五章单元小测",
    instructions:
      "共 10 题，基础 2 题、进阶 4 题、压轴 4 题，整体难度明显上调，更强调多步推理、信息提取与综合应用。",
    passingScore: 80,
    questions: [
      {
        id: "q1",
        quizId: "quiz-g9-shang-unit-5",
        type: "single-choice",
        difficulty: "basic",
        stem: "下列事件中，属于必然事件的是哪一个？",
        options: [
          { id: "a", label: "A", content: "掷一枚骰子，点数是 7" },
          { id: "b", label: "B", content: "今天下雨" },
          { id: "c", label: "C", content: "任取实数 a，都有 a²≥0" },
          { id: "d", label: "D", content: "抛一枚硬币，正面朝上" },
        ],
        correctOptionId: "c",
        explanation: "任意实数的平方都不小于 0，所以这是必然事件。",
        relatedLessonIds: ["lesson-g9s5-random-event"],
      },
      {
        id: "q2",
        quizId: "quiz-g9-shang-unit-5",
        type: "single-choice",
        difficulty: "basic",
        stem: "一个均匀骰子掷一次，出现偶数点的概率是多少？",
        options: [
          { id: "a", label: "A", content: "1/6" },
          { id: "b", label: "B", content: "1/3" },
          { id: "c", label: "C", content: "1/2" },
          { id: "d", label: "D", content: "2/3" },
        ],
        correctOptionId: "c",
        explanation: "偶数点有 2、4、6 共 3 个，有利结果数 3，总结果数 6，所以概率是 1/2。",
        relatedLessonIds: ["lesson-g9s5-random-event"],
      },
      {
        id: "q3",
        quizId: "quiz-g9-shang-unit-5",
        type: "fill-blank",
        difficulty: "advanced",
        stem: "连续抛两枚硬币，请写出全部等可能结果数，并求“恰有一枚正面朝上”的概率。",
        blanks: [
          {
            id: "total",
            prompt: "等可能结果数",
            hint: "可列出 (正,正)、(正,反)、(反,正)、(反,反)。",
            acceptableAnswers: ["4"],
            placeholder: "请填写结果",
          },
          {
            id: "probability",
            prompt: "依据相关关系，所求概率",
            hint: "先判断所用关系或方法，再恰有一枚正面朝上有 2 种情况。",
            acceptableAnswers: ["1/2", "2/4"],
            placeholder: "请填写结果",
          },
        ],
        explanation: "依据题目中的条件和相关性质，共有 4 种等可能结果，其中恰有一枚正面朝上的有 2 种，所以概率为 1/2。",
        relatedLessonIds: ["lesson-g9s5-listing-probability"],
      },
      {
        id: "q4",
        quizId: "quiz-g9-shang-unit-5",
        type: "single-choice",
        difficulty: "advanced",
        stem: "袋中有编号 1、2、3 的三个小球，任意摸出一个后放回，再摸一次。记两次号码之和为 S，则 P(S=4) 等于多少？",
        options: [
          { id: "a", label: "A", content: "1/9" },
          { id: "b", label: "B", content: "2/9" },
          { id: "c", label: "C", content: "1/3" },
          { id: "d", label: "D", content: "4/9" },
        ],
        correctOptionId: "c",
        explanation:
          "两次摸球共有 9 种等可能结果，和为 4 的有 (1,3)、(2,2)、(3,1) 共 3 种，所以概率是 1/3。",
        relatedLessonIds: ["lesson-g9s5-listing-probability"],
      },
      {
        id: "q5",
        quizId: "quiz-g9-shang-unit-5",
        type: "fill-blank",
        difficulty: "advanced",
        stem: "某个不透明袋中只有红球和白球，随机摸球大量重复试验后，摸到红球的频率稳定在 0.62 附近。请填写红球概率的大致值，并说明频率与概率的关系。",
        blanks: [
          {
            id: "approximation",
            prompt: "红球概率的大致值",
            hint: "大量重复试验时，频率会稳定在概率附近。",
            acceptableAnswers: ["0.62", "62%"],
            placeholder: "请填写结果",
          },
          {
            id: "relation",
            prompt: "频率与概率的关系",
            hint: "用“接近”或“稳定在附近”描述。",
            acceptableAnswers: ["频率在大量试验时接近概率", "大量试验时频率接近概率"],
            placeholder: "请填写结论",
          },
        ],
        explanation: "大量重复试验时，频率通常会稳定在概率附近，所以红球概率约为 0.62。",
        relatedLessonIds: ["lesson-g9s5-random-event"],
      },
      {
        id: "q6",
        quizId: "quiz-g9-shang-unit-5",
        type: "single-choice",
        difficulty: "advanced",
        stem: "甲、乙两人各掷一次均匀骰子，记事件 A 为“甲的点数大于乙的点数”。则 P(A) 是多少？",
        options: [
          { id: "a", label: "A", content: "5/12" },
          { id: "b", label: "B", content: "1/2" },
          { id: "c", label: "C", content: "7/12" },
          { id: "d", label: "D", content: "1/3" },
        ],
        correctOptionId: "a",
        explanation:
          "共有 36 种等可能结果，相同点数有 6 种，剩余 30 种中甲大于乙与甲小于乙对称，各占 15 种，所以概率为 15/36=5/12。",
        relatedLessonIds: ["lesson-g9s5-listing-probability"],
      },
      {
        id: "q7",
        quizId: "quiz-g9-shang-unit-5",
        type: "fill-blank",
        difficulty: "challenge",
        stem: "一个转盘被平均分成 4 个区域，分别标有 1、2、3、4。转动两次，求“至少有一次转到 4”的概率，并写出你用到的转化思路。",
        blanks: [
          {
            id: "probability",
            prompt: "所求概率",
            hint: "先求一次也没有转到 4 的概率。",
            acceptableAnswers: ["7/16"],
            placeholder: "请填写结果",
          },
          {
            id: "strategy",
            prompt: "转化思路",
            hint: "用反面事件。",
            acceptableAnswers: ["反面事件", "1减去一次也没有转到4的概率", "先求反面事件"],
            placeholder: "请填写思路",
          },
        ],
        explanation:
          "一次不转到 4 的概率是 3/4，两次都不转到 4 的概率是 9/16，所以至少一次转到 4 的概率是 1-9/16=7/16。",
        relatedLessonIds: ["lesson-g9s5-listing-probability"],
      },
      {
        id: "q8",
        quizId: "quiz-g9-shang-unit-5",
        type: "single-choice",
        difficulty: "challenge",
        stem: "袋中有 2 个红球、1 个白球，先后摸出两个球且不放回。事件 B 为“两个球颜色不同”。则 P(B) 等于多少？",
        options: [
          { id: "a", label: "A", content: "1/3" },
          { id: "b", label: "B", content: "2/3" },
          { id: "c", label: "C", content: "1/2" },
          { id: "d", label: "D", content: "3/4" },
        ],
        correctOptionId: "b",
        explanation:
          "有序摸球结果可记为 红红、红白、白红，其中颜色不同的有 红白、白红 两种，占 2/3。",
        relatedLessonIds: ["lesson-g9s5-listing-probability"],
      },
      {
        id: "q9",
        quizId: "quiz-g9-shang-unit-5",
        type: "fill-blank",
        difficulty: "challenge",
        stem: "从数字 1、2、3、4 中任取两个不同数字组成一个两位数。请写出所有等可能结果数，并求组成的两位数是偶数的概率。",
        blanks: [
          {
            id: "total",
            prompt: "等可能结果数",
            hint: "十位有 4 种选法，个位有 3 种选法。",
            acceptableAnswers: ["12"],
            placeholder: "请填写结果",
          },
          {
            id: "probability",
            prompt: "组成偶数的概率",
            hint: "个位必须是 2 或 4。",
            acceptableAnswers: ["1/2", "6/12"],
            placeholder: "请填写结果",
          },
        ],
        explanation:
          "共有 4×3=12 个两位数。若为偶数，个位只能是 2 或 4，各有 3 种十位选法，共 6 个，所以概率为 1/2。",
        relatedLessonIds: ["lesson-g9s5-listing-probability"],
      },
      {
        id: "q10",
        quizId: "quiz-g9-shang-unit-5",
        type: "fill-blank",
        difficulty: "challenge",
        stem: "盒中有 3 张卡片，分别写着 1、2、3。先随机抽一张记下数字后放回，再抽一张。若两次数字之积是偶数，请写出该事件的概率，并判断它是否大于“两次数字之和是 4”的概率。",
        blanks: [
          {
            id: "productEven",
            prompt: "积是偶数的概率",
            hint: "用反面事件：只有两个数字都为奇数时积才是奇数。",
            acceptableAnswers: ["5/9"],
            placeholder: "请填写结果",
          },
          {
            id: "comparison",
            prompt: "是否更大",
            hint: "和为 4 的概率在同一题型中容易直接列举。",
            acceptableAnswers: ["是", "大于"],
            placeholder: "请填写判断",
          },
        ],
        explanation:
          "两次都抽到奇数的概率是 4/9，所以积为偶数的概率是 1-4/9=5/9。和为 4 的概率是 3/9=1/3，因此 5/9 更大。",
        relatedLessonIds: ["lesson-g9s5-listing-probability", "lesson-g9s5-random-event"],
      },
    ],
  },
};
