import type { CurriculumSlice } from "@/types/content";
import { createExpressionFigure, createRectangleFigure } from "./quiz-figures";

export const g9ShangUnit1Slice: CurriculumSlice = {
  grade: {
    id: "g9",
    label: "九年级",
    shortLabel: "九上",
    description: "围绕方程、函数与几何综合应用，进入中考主干能力训练阶段。",
  },
  volume: {
    id: "shang",
    gradeId: "g9",
    label: "上册",
    description: "以一元二次方程、二次函数和圆的基础应用为主要内容。",
  },
  chapter: {
    id: "g9-shang-unit-1",
    gradeId: "g9",
    volumeId: "shang",
    slug: "yi-yuan-er-ci-fang-cheng",
    title: "第一章 一元二次方程",
    summary:
      "理解一元二次方程的特征，会用直接开平方法、因式分解法求解简单方程，并能处理基础应用题。",
    order: 1,
    lessonIds: [
      "lesson-g9s-quadratic-concept",
      "lesson-g9s-solve-quadratic",
    ],
    workedExampleIds: [
      "example-g9s-square-root-method",
      "example-g9s-factorization-method",
    ],
    quizId: "quiz-g9-shang-unit-1",
    coverImage: {
      src: "/images/content/g9-shang-unit-1-cover.svg",
      alt: "第一章一元二次方程封面示意图",
    },
  },
  lessons: [
    {
      id: "lesson-g9s-quadratic-concept",
      chapterId: "g9-shang-unit-1",
      slug: "yi-yuan-er-ci-fang-cheng-de-gai-nian",
      title: "一元二次方程的概念",
      summary: "认识一元二次方程的一般形式，能判断一个方程是否属于这一类。",
      learningObjectives: [
        "知道一元二次方程只含一个未知数且未知数最高次数为 2。",
        "会把简单方程整理成一般形式 ax² + bx + c = 0。",
        "能区分一元一次方程与一元二次方程。",
      ],
      keyRules: [
        "一元二次方程的一般形式是 ax² + bx + c = 0，其中 a ≠ 0。",
        "判断前要先把方程整理到一边为 0 的形式。",
        "未知数最高次数是 2，才是一元二次方程。",
      ],
      bodyBlocks: [
        {
          type: "richText",
          id: "g9s-context-1",
          title: "先整理，再判断",
          content: [
            "很多题目给出的方程不是标准形式，这时要先移项、合并同类项，把它写成 ax² + bx + c = 0。",
            "整理完成后，再看未知数个数和最高次数，就能判断它是不是一元二次方程。",
          ],
        },
        {
          type: "formula",
          id: "g9s-formula-1",
          title: "典型形式",
          formulas: ["x² - 5x + 6 = 0", "2x² = 18", "x(x - 3) = 4"],
          note: "像 2x² = 18 这类题，也要先整理成 2x² - 18 = 0。",
        },
        {
          type: "tip",
          id: "g9s-tip-1",
          title: "易错提醒",
          content: "若最高次数是 2 但有两个未知数，就不是一元二次方程。",
        },
      ],
      relatedExampleIds: ["example-g9s-square-root-method"],
      order: 1,
      videoPlaceholder: {
        title: "板书微课：一元二次方程长什么样",
        durationLabel: "4 分钟",
        description: "从一般形式出发，快速判断题型。",
      },
    },
    {
      id: "lesson-g9s-solve-quadratic",
      chapterId: "g9-shang-unit-1",
      slug: "jie-yi-yuan-er-ci-fang-cheng",
      title: "解一元二次方程",
      summary: "掌握直接开平方法和因式分解法，能求出简单方程的根。",
      learningObjectives: [
        "会把形如 x² = a 的方程转化为两个根。",
        "会把方程化为乘积等于 0 的形式后分步求解。",
        "知道验根时要把每个根都代回原方程检查。",
      ],
      keyRules: [
        "若 x² = a（a ≥ 0），则 x = ±√a。",
        "若 (x - m)(x - n) = 0，则 x = m 或 x = n。",
        "解方程后要写出两个根，不能漏掉负根或第二个根。",
      ],
      bodyBlocks: [
        {
          type: "richText",
          id: "g9s-context-2",
          title: "方法选择要看结构",
          content: [
            "如果方程中只有平方项和常数项，往往适合直接开平方法。",
            "如果能整理成两个一次因式相乘等于 0，就优先考虑因式分解法，步骤更短。",
          ],
        },
        {
          type: "formula",
          id: "g9s-formula-2",
          title: "常见转化",
          formulas: ["x² = 25 → x = ±5", "x² - 5x + 6 = 0 → (x - 2)(x - 3) = 0"],
          note: "写根时常用 x₁、x₂ 表示，答案要完整。",
        },
        {
          type: "tip",
          id: "g9s-tip-2",
          title: "易错提醒",
          content: "看到 x² = 16 时，答案不是只有 4，还要写 -4。",
        },
      ],
      relatedExampleIds: ["example-g9s-square-root-method", "example-g9s-factorization-method"],
      order: 2,
      videoPlaceholder: {
        title: "板书微课：开平方法与因式分解法",
        durationLabel: "6 分钟",
        description: "用题型特征决定解法，避免方法乱选。",
      },
    },
  ],
  workedExamples: [
    {
      id: "example-g9s-square-root-method",
      chapterId: "g9-shang-unit-1",
      slug: "zhi-jie-kai-ping-fang-fa",
      title: "例题 1：直接开平方法",
      summary: "把方程化成 x² = a，再写出两个根。",
      problem: "解方程：x² = 49。",
      steps: [
        {
          id: "step-1",
          title: "判断结构",
          content: "方程已经是 x² = a 的形式，可以直接开平方。",
        },
        {
          id: "step-2",
          title: "求两个根",
          content: "x = ±7，所以 x₁ = 7，x₂ = -7。",
        },
        {
          id: "step-3",
          title: "写出结果",
          content: "原方程的两个根是 7 和 -7。",
        },
      ],
      answer: "x₁ = 7，x₂ = -7",
      commonMistakes: [
        "只写出一个正根。",
        "把 ±7 写成 7 ±。",
      ],
      relatedLessonIds: ["lesson-g9s-quadratic-concept", "lesson-g9s-solve-quadratic"],
      order: 1,
    },
    {
      id: "example-g9s-factorization-method",
      chapterId: "g9-shang-unit-1",
      slug: "yin-shi-fen-jie-fa",
      title: "例题 2：因式分解法",
      summary: "先分解因式，再利用零积定理求根。",
      problem: "解方程：x² - 5x + 6 = 0。",
      steps: [
        {
          id: "step-1",
          title: "尝试分解",
          content: "寻找两个数，它们的积为 6，和为 5，可取 2 和 3。",
        },
        {
          id: "step-2",
          title: "写成乘积形式",
          content: "原方程可化为 (x - 2)(x - 3) = 0。",
        },
        {
          id: "step-3",
          title: "分别求根",
          content: "由零积定理得 x - 2 = 0 或 x - 3 = 0，所以 x₁ = 2，x₂ = 3。",
        },
      ],
      answer: "x₁ = 2，x₂ = 3",
      commonMistakes: [
        "因式分解后只解出一个根。",
        "把和积关系找反，写成 (x + 2)(x + 3)。",
      ],
      relatedLessonIds: ["lesson-g9s-solve-quadratic"],
      order: 2,
    },
  ],
  quiz: {
    id: "quiz-g9-shang-unit-1",
    chapterId: "g9-shang-unit-1",
    title: "第一章单元小测",
    instructions:
      "共 10 题，基础 2 题、进阶 4 题、压轴 4 题，整体难度明显上调，更强调多步推理、信息提取与综合应用。",
    passingScore: 80,
    questions: [
      {
        id: "q1",
        quizId: "quiz-g9-shang-unit-1",
        type: "single-choice",
        difficulty: "basic",
        stem: "下列方程中，哪个是一元二次方程？",
        options: [
          { id: "a", label: "A", content: "2x + 1 = 0" },
          { id: "b", label: "B", content: "x² - 3x + 2 = 0" },
          { id: "c", label: "C", content: "x + y = 5" },
          { id: "d", label: "D", content: "1/x = 2" },
        ],
        correctOptionId: "b",
        explanation: "只含一个未知数且未知数最高次数为 2，整理后等号一边为 0，才是一元二次方程。",
        relatedLessonIds: ["lesson-g9s-quadratic-concept"],
        relatedExampleIds: ["example-g9s-square-root-method"],
      },
      {
        id: "q2",
        quizId: "quiz-g9-shang-unit-1",
        type: "single-choice",
        difficulty: "basic",
        stem: "方程 x² = 36 的解是哪个？",
        options: [
          { id: "a", label: "A", content: "x = 6" },
          { id: "b", label: "B", content: "x = -6" },
          { id: "c", label: "C", content: "x = ±6" },
          { id: "d", label: "D", content: "x = 18" },
        ],
        correctOptionId: "c",
        explanation: "直接开平方可得 x = ±6，要写出两个根。",
        relatedLessonIds: ["lesson-g9s-solve-quadratic"],
        relatedExampleIds: ["example-g9s-square-root-method"],
      },
      {
        id: "q3",
        quizId: "quiz-g9-shang-unit-1",
        type: "fill-blank",
        difficulty: "advanced",
        stem: "方程 x(x - 2) = 8 的一个根是 4。请先填写另一个根，再说明你把原方程转化成了哪种更易求根的形式。",
        blanks: [
          {
            id: "other-root",
            prompt: "另一个根",
            hint: "先移项整理，再因式分解。",
            acceptableAnswers: ["-2"],
            placeholder: "请填写结果",
          },
          {
            id: "form",
            prompt: "转化后的形式",
            hint: "把方程整理成因式乘积等于 0 的形式。",
            acceptableAnswers: ["(x-4)(x+2)=0", "(x - 4)(x + 2) = 0"],
            placeholder: "请填写形式",
          },
        ],
        explanation: "依据一元二次方程求根的转化思路，可先整理为 x² - 2x - 8 = 0，再因式分解成 (x - 4)(x + 2) = 0，所以另一个根是 -2。",
        relatedLessonIds: ["lesson-g9s-quadratic-concept"],
        relatedExampleIds: ["example-g9s-square-root-method"],
      },
      {
        id: "q4",
        quizId: "quiz-g9-shang-unit-1",
        type: "single-choice",
        difficulty: "advanced",
        stem: "解方程 x² - 9 = 0，正确结果是哪个？",
        options: [
          { id: "a", label: "A", content: "x = 3" },
          { id: "b", label: "B", content: "x = -3" },
          { id: "c", label: "C", content: "x = ±3" },
          { id: "d", label: "D", content: "x = 9" },
        ],
        correctOptionId: "c",
        explanation: "移项后 x² = 9，所以 x = ±3。",
        relatedLessonIds: ["lesson-g9s-solve-quadratic"],
        relatedExampleIds: ["example-g9s-square-root-method"],
      },
      {
        id: "q5",
        quizId: "quiz-g9-shang-unit-1",
        type: "fill-blank",
        difficulty: "advanced",
        stem: "观察图中的因式结构，请分别填写这两个一次因式对应的两个根。",
        figure: createExpressionFigure(
          "一元二次方程 x²-5x+6=0 的因式分解结构图。",
          "(x - 2)(x - 3) = 0",
          "x - 2",
          "x - 3",
          "0",
        ),
        blanks: [
          {
            id: "root-1",
            prompt: "由 x - 2 = 0 得到的根",
            hint: "把因式 x - 2 = 0 单独解出来，只填写根的数值。",
            acceptableAnswers: ["2"],
            placeholder: "请填写整数",
          },
          {
            id: "root-2",
            prompt: "由 x - 3 = 0 得到的根",
            hint: "把因式 x - 3 = 0 单独解出来，只填写根的数值。",
            acceptableAnswers: ["3"],
            placeholder: "请填写整数",
          },
        ],
        explanation: "方程分解为 (x - 2)(x - 3) = 0，所以分别有 x - 2 = 0 和 x - 3 = 0，得到两个根 2 和 3。",
        relatedLessonIds: ["lesson-g9s-solve-quadratic"],
        relatedExampleIds: ["example-g9s-factorization-method"],
      },
      {
        id: "q6",
        quizId: "quiz-g9-shang-unit-1",
        type: "single-choice",
        difficulty: "advanced",
        stem: "若方程 x² + kx + 6 = 0 可以分解成 (x + 2)(x + 3) = 0，则 k 等于多少？",
        options: [
          { id: "a", label: "A", content: "1" },
          { id: "b", label: "B", content: "5" },
          { id: "c", label: "C", content: "-5" },
          { id: "d", label: "D", content: "-6" },
        ],
        correctOptionId: "b",
        explanation: "展开 (x + 2)(x + 3) 得 x² + 5x + 6，所以 k = 5。",
        relatedLessonIds: ["lesson-g9s-solve-quadratic"],
        relatedExampleIds: ["example-g9s-factorization-method"],
      },
      {
        id: "q7",
        quizId: "quiz-g9-shang-unit-1",
        type: "single-choice",
        difficulty: "challenge",
        stem: "若方程 (x - 4)(x + 1) = 0，则它的两个根是哪个？",
        options: [
          { id: "a", label: "A", content: "4 和 1" },
          { id: "b", label: "B", content: "-4 和 1" },
          { id: "c", label: "C", content: "4 和 -1" },
          { id: "d", label: "D", content: "-4 和 -1" },
        ],
        correctOptionId: "c",
        explanation: "由零积定理得 x - 4 = 0 或 x + 1 = 0，所以 x = 4 或 x = -1。",
        relatedLessonIds: ["lesson-g9s-solve-quadratic"],
        relatedExampleIds: ["example-g9s-factorization-method"],
      },
      {
        id: "q8",
        quizId: "quiz-g9-shang-unit-1",
        type: "single-choice",
        difficulty: "challenge",
        stem: "把方程 2x² = 18 化成一般形式后，正确的是哪个？",
        options: [
          { id: "a", label: "A", content: "2x² + 18 = 0" },
          { id: "b", label: "B", content: "2x² - 18 = 0" },
          { id: "c", label: "C", content: "x² - 9 = 18" },
          { id: "d", label: "D", content: "2x² = 0" },
        ],
        correctOptionId: "b",
        explanation: "把右边的 18 移到左边，应写成 2x² - 18 = 0。",
        relatedLessonIds: ["lesson-g9s-quadratic-concept", "lesson-g9s-solve-quadratic"],
        relatedExampleIds: ["example-g9s-square-root-method"],
      },
      {
        id: "q9",
        quizId: "quiz-g9-shang-unit-1",
        type: "single-choice",
        difficulty: "challenge",
        stem: "若 2 是方程 x² - 5x + m = 0 的一个根，则 m 的值是多少？",
        options: [
          { id: "a", label: "A", content: "3" },
          { id: "b", label: "B", content: "4" },
          { id: "c", label: "C", content: "6" },
          { id: "d", label: "D", content: "10" },
        ],
        correctOptionId: "c",
        explanation: "把 x = 2 代入得 4 - 10 + m = 0，所以 m = 6。",
        relatedLessonIds: ["lesson-g9s-quadratic-concept", "lesson-g9s-solve-quadratic"],
        relatedExampleIds: ["example-g9s-factorization-method"],
      },
      {
        id: "q10",
        quizId: "quiz-g9-shang-unit-1",
        type: "fill-blank",
        difficulty: "challenge",
        stem: "观察图中的长方形面积模型，请先写出长，再写出正确方程。",
        figure: createRectangleFigure(
          "长方形面积为 48，宽为 x，长为 x+2 的面积模型图。",
          "x + 2",
          "x",
        ),
        blanks: [
          {
            id: "length",
            prompt: "长的代数式",
            hint: "图中宽是 x，长比宽多 2，所以先写出长对应的代数式。",
            acceptableAnswers: ["x+2"],
            placeholder: "请填写代数式",
          },
          {
            id: "equation",
            prompt: "列出的方程",
            hint: "用“面积 = 长 × 宽 = 48”列式，方程中要同时出现 x 和长的代数式。",
            acceptableAnswers: ["x(x+2)=48", "(x+2)x=48"],
            placeholder: "请填写方程",
          },
        ],
        explanation: "宽为 x，长比宽多 2，所以长是 x + 2；面积 = 长 × 宽，所以应列方程 x(x + 2) = 48。",
        relatedLessonIds: ["lesson-g9s-quadratic-concept", "lesson-g9s-solve-quadratic"],
        relatedExampleIds: ["example-g9s-square-root-method", "example-g9s-factorization-method"],
      },
    ],
  },
};
