import type { CurriculumSlice } from "@/types/content";

export const g9XiaUnit2Slice: CurriculumSlice = {
  grade: {
    id: "g9",
    label: "九年级",
    shortLabel: "九下",
    description: "围绕方程、函数与几何综合应用，进入中考主干能力训练阶段。",
  },
  volume: {
    id: "xia",
    gradeId: "g9",
    label: "下册",
    description: "以反比例函数、相似、三角函数和空间视图为主要内容。",
  },
  chapter: {
    id: "g9-xia-unit-2",
    gradeId: "g9",
    volumeId: "xia",
    slug: "xiang-si",
    title: "第二章 相似",
    summary: "理解相似图形与相似三角形的概念，会利用对应边成比例和对应角相等解决问题。",
    order: 2,
    lessonIds: ["lesson-g9x2-similar-triangle", "lesson-g9x2-application"],
    workedExampleIds: ["example-g9x2-ratio", "example-g9x2-height"],
    quizId: "quiz-g9-xia-unit-2",
  },
  lessons: [
    {
      id: "lesson-g9x2-similar-triangle",
      chapterId: "g9-xia-unit-2",
      slug: "xiang-si-san-jiao-xing-pan-ding",
      title: "相似三角形的判定与性质",
      summary: "掌握相似三角形常见判定方法，会用对应边比和对应角求未知量。",
      learningObjectives: [
        "会用 AA、SAS、SSS 等方法判定相似。",
        "知道相似三角形对应边成比例、对应角相等。",
        "会利用相似比求线段和面积关系。",
      ],
      keyRules: [
        "相似三角形对应角相等，对应边成比例。",
        "相似比为 k 时，面积比为 k²。",
        "判定相似先找对应关系，再列比例式。",
      ],
      bodyBlocks: [
        {
          type: "richText",
          id: "g9x2-similar-context",
          title: "相似题最先要对准对应",
          content: [
            "相似问题里比例式列错，往往不是算错，而是对应关系先对错了。",
            "先写出哪个角对应哪个角，再写边的比例，更稳。",
          ],
        },
      ],
      relatedExampleIds: ["example-g9x2-ratio"],
      order: 1,
      videoPlaceholder: {
        title: "板书微课：相似三角形比例式怎么列不乱",
        durationLabel: "5 分钟",
        description: "先对角，再对边，再列比例。",
      },
    },
    {
      id: "lesson-g9x2-application",
      chapterId: "g9-xia-unit-2",
      slug: "xiang-si-de-shi-ji-ying-yong",
      title: "相似的实际应用",
      summary: "会把测高、影长、放大缩小等问题转化为相似模型。",
      learningObjectives: [
        "会利用平行关系构造相似三角形。",
        "会在测高和影长问题中使用相似。",
        "能综合相似比解释实际尺寸变化。",
      ],
      keyRules: [
        "平行线常常带来对应角相等，从而构造相似。",
        "测高问题里常通过太阳光线平行构造相似三角形。",
        "缩放前后长度按相似比变化。",
      ],
      bodyBlocks: [
        {
          type: "tip",
          id: "g9x2-app-tip",
          title: "易错提醒",
          content: "测高题里要先把“光线平行”转化成角相等，再谈相似，不能直接套比例。",
        },
      ],
      relatedExampleIds: ["example-g9x2-height"],
      order: 2,
      videoPlaceholder: {
        title: "板书微课：测高题为什么常用相似",
        durationLabel: "6 分钟",
        description: "从平行光线构造相似三角形。",
      },
    },
  ],
  workedExamples: [
    {
      id: "example-g9x2-ratio",
      chapterId: "g9-xia-unit-2",
      slug: "xiang-si-bi-qiu-bian",
      title: "例题 1：由相似比求边长",
      summary: "利用对应边成比例求未知边。",
      problem: "△ABC∽△DEF，若 AB=4，DE=6，BC=8，求 EF。",
      steps: [
        { id: "step-1", title: "确定相似比", content: "AB:DE=4:6=2:3。" },
        { id: "step-2", title: "列比例式", content: "BC:EF=2:3，所以 8:EF=2:3。" },
        { id: "step-3", title: "解得结果", content: "EF=12。" },
      ],
      answer: "12",
      commonMistakes: ["把对应边顺序写反。"],
      relatedLessonIds: ["lesson-g9x2-similar-triangle"],
      order: 1,
    },
    {
      id: "example-g9x2-height",
      chapterId: "g9-xia-unit-2",
      slug: "ying-zi-ce-gao",
      title: "例题 2：利用影长测高",
      summary: "借助平行光线构造相似三角形测量高度。",
      problem: "一根 1.5 米高的测杆影长为 2 米，同时一棵树影长为 8 米，求树高。",
      steps: [
        { id: "step-1", title: "构造相似", content: "阳光平行，所以测杆与树形成的两个直角三角形相似。" },
        { id: "step-2", title: "列比例式", content: "1.5:2=h:8。" },
        { id: "step-3", title: "求树高", content: "h=6。" },
      ],
      answer: "6 米",
      commonMistakes: ["把影长和高度对应错位。"],
      relatedLessonIds: ["lesson-g9x2-application"],
      order: 2,
    },
  ],
  quiz: {
    id: "quiz-g9-xia-unit-2",
    chapterId: "g9-xia-unit-2",
    title: "第二章单元小测",
    instructions:
      "共 10 题，基础 2 题、进阶 4 题、压轴 4 题，整体难度明显上调，更强调多步推理、信息提取与综合应用。",
    passingScore: 80,
    questions: [
      {
        id: "q1",
        quizId: "quiz-g9-xia-unit-2",
        type: "single-choice",
        difficulty: "basic",
        stem: "相似三角形中，对应角之间是什么关系？",
        options: [
          { id: "a", label: "A", content: "互补" },
          { id: "b", label: "B", content: "相等" },
          { id: "c", label: "C", content: "垂直" },
          { id: "d", label: "D", content: "无法确定" },
        ],
        correctOptionId: "b",
        explanation: "相似三角形的对应角相等。",
        relatedLessonIds: ["lesson-g9x2-similar-triangle"],
      },
      {
        id: "q2",
        quizId: "quiz-g9-xia-unit-2",
        type: "single-choice",
        difficulty: "basic",
        stem: "若两个相似三角形的相似比是 1:3，则面积比是多少？",
        options: [
          { id: "a", label: "A", content: "1:3" },
          { id: "b", label: "B", content: "1:6" },
          { id: "c", label: "C", content: "1:9" },
          { id: "d", label: "D", content: "3:1" },
        ],
        correctOptionId: "c",
        explanation: "面积比等于相似比的平方，即 1:9。",
        relatedLessonIds: ["lesson-g9x2-similar-triangle"],
      },
      {
        id: "q3",
        quizId: "quiz-g9-xia-unit-2",
        type: "fill-blank",
        difficulty: "advanced",
        stem: "若 △ABC∽△DEF，且 AB=6，DE=9，BC=8。请填写 EF 的长度，并写出你用到的对应边比例。",
        blanks: [
          {
            id: "ef",
            prompt: "EF 的长度",
            hint: "AB:DE=BC:EF。",
            acceptableAnswers: ["12"],
            placeholder: "请填写结果",
          },
          {
            id: "ratio",
            prompt: "依据相关关系，对应边比例",
            hint: "先判断所用关系或方法，再先写出相似比。",
            acceptableAnswers: ["6:9=8:EF", "AB:DE=BC:EF"],
            placeholder: "请填写结果",
          },
        ],
        explanation: "依据题目中的条件和相关性质，相似比为 2:3，所以 EF=12。",
        relatedLessonIds: ["lesson-g9x2-similar-triangle"],
      },
      {
        id: "q4",
        quizId: "quiz-g9-xia-unit-2",
        type: "single-choice",
        difficulty: "advanced",
        stem: "两个三角形中有两个角分别相等，则这两个三角形满足哪种关系？",
        options: [
          { id: "a", label: "A", content: "全等" },
          { id: "b", label: "B", content: "相似" },
          { id: "c", label: "C", content: "直角" },
          { id: "d", label: "D", content: "面积相等" },
        ],
        correctOptionId: "b",
        explanation: "两个角分别相等即可用 AA 判定三角形相似。",
        relatedLessonIds: ["lesson-g9x2-similar-triangle"],
      },
      {
        id: "q5",
        quizId: "quiz-g9-xia-unit-2",
        type: "fill-blank",
        difficulty: "advanced",
        stem: "一张照片放大后，宽从 12cm 变成 18cm。请填写放大倍数，并求原来高为 8cm 时放大后的高。",
        blanks: [
          {
            id: "ratio",
            prompt: "放大倍数",
            hint: "18÷12。",
            acceptableAnswers: ["1.5", "3/2"],
            placeholder: "请填写结果",
          },
          {
            id: "height",
            prompt: "放大后的高",
            hint: "按同一相似比变化。",
            acceptableAnswers: ["12"],
            placeholder: "请填写结果",
          },
        ],
        explanation: "相似比为 1.5，所以高也放大到 12cm。",
        relatedLessonIds: ["lesson-g9x2-application"],
      },
      {
        id: "q6",
        quizId: "quiz-g9-xia-unit-2",
        type: "single-choice",
        difficulty: "advanced",
        stem: "测杆高 1.2 米，影长 1.5 米；树影长 7.5 米。树高是多少？",
        options: [
          { id: "a", label: "A", content: "4 米" },
          { id: "b", label: "B", content: "5 米" },
          { id: "c", label: "C", content: "6 米" },
          { id: "d", label: "D", content: "7 米" },
        ],
        correctOptionId: "c",
        explanation: "由相似得 1.2:1.5=h:7.5，解得 h=6。",
        relatedLessonIds: ["lesson-g9x2-application"],
      },
      {
        id: "q7",
        quizId: "quiz-g9-xia-unit-2",
        type: "fill-blank",
        difficulty: "challenge",
        stem: "若两个相似三角形面积比是 4:9。请填写它们的相似比，并说明对应边长度是扩大还是缩小了。",
        blanks: [
          {
            id: "ratio",
            prompt: "相似比",
            hint: "面积比开平方。",
            acceptableAnswers: ["2:3"],
            placeholder: "请填写结果",
          },
          {
            id: "change",
            prompt: "长度变化",
            hint: "看比值是否大于 1。",
            acceptableAnswers: ["扩大到原来的3/2倍", "较小图到较大图扩大到3/2倍"],
            placeholder: "请填写结果",
          },
        ],
        explanation: "面积比 4:9 对应相似比 2:3，较小图到较大图的边长扩大到原来的 3/2 倍。",
        relatedLessonIds: ["lesson-g9x2-similar-triangle"],
      },
      {
        id: "q8",
        quizId: "quiz-g9-xia-unit-2",
        type: "single-choice",
        difficulty: "challenge",
        stem: "在 △ABC 中，DE∥BC，且 D、E 分别在 AB、AC 上。若 AD:AB=2:5，则 AE:AC 等于多少？",
        options: [
          { id: "a", label: "A", content: "2:5" },
          { id: "b", label: "B", content: "3:5" },
          { id: "c", label: "C", content: "2:3" },
          { id: "d", label: "D", content: "5:2" },
        ],
        correctOptionId: "a",
        explanation: "因为 DE∥BC，所以 △ADE∽△ABC，对应边比相等。",
        relatedLessonIds: ["lesson-g9x2-application"],
      },
      {
        id: "q9",
        quizId: "quiz-g9-xia-unit-2",
        type: "fill-blank",
        difficulty: "challenge",
        stem: "相似三角形两条对应边长分别为 6 和 15。若较小三角形周长为 20，请填写较大三角形周长，并说明理由。",
        blanks: [
          {
            id: "perimeter",
            prompt: "较大三角形周长",
            hint: "周长按相似比变化。",
            acceptableAnswers: ["50"],
            placeholder: "请填写结果",
          },
          {
            id: "reason",
            prompt: "理由",
            hint: "周长与边长同倍变化。",
            acceptableAnswers: ["周长按相似比变化", "相似比是5:2，所以周长也乘5/2"],
            placeholder: "请填写结果",
          },
        ],
        explanation: "相似比为 15:6=5:2，所以较大三角形周长为 20×5/2=50。",
        relatedLessonIds: ["lesson-g9x2-similar-triangle"],
      },
      {
        id: "q10",
        quizId: "quiz-g9-xia-unit-2",
        type: "fill-blank",
        difficulty: "challenge",
        stem: "一幅图缩小后面积变为原来的 1/4。请填写对应边长变为原来的多少，并判断这是否属于相似变换。",
        blanks: [
          {
            id: "length",
            prompt: "边长变化",
            hint: "面积比开平方。",
            acceptableAnswers: ["1/2"],
            placeholder: "请填写结果",
          },
          {
            id: "judge",
            prompt: "是否属于相似变换",
            hint: "图形形状不变，只做等比缩放。",
            acceptableAnswers: ["是"],
            placeholder: "请填写结果",
          },
        ],
        explanation: "面积变为 1/4，则边长变为 1/2，这正是相似变换。",
        relatedLessonIds: ["lesson-g9x2-similar-triangle", "lesson-g9x2-application"],
      },
    ],
  },
};
