import type { CurriculumSlice } from "@/types/content";

export const g9XiaUnit1Slice: CurriculumSlice = {
  grade: {
    id: "g9",
    label: "九年级",
    shortLabel: "九下",
    description: "围绕方程、函数与几何综合应用，进入中考主干能力训练阶段。",
  },
  volume: {
    id: "xia",
    gradeId: "g9",
    label: "下册",
    description: "以反比例函数、相似、三角函数和空间视图为主要内容。",
  },
  chapter: {
    id: "g9-xia-unit-1",
    gradeId: "g9",
    volumeId: "xia",
    slug: "fan-bi-li-han-shu",
    title: "第一章 反比例函数",
    summary: "理解反比例函数的表达式、图象和性质，会在实际问题中建立反比例模型。",
    order: 1,
    lessonIds: ["lesson-g9x1-expression", "lesson-g9x1-application"],
    workedExampleIds: ["example-g9x1-point", "example-g9x1-model"],
    quizId: "quiz-g9-xia-unit-1",
  },
  lessons: [
    {
      id: "lesson-g9x1-expression",
      chapterId: "g9-xia-unit-1",
      slug: "fan-bi-li-han-shu-jie-xi-shi",
      title: "反比例函数的表达式与图象",
      summary: "掌握 y=k/x 的基本形式，会根据点坐标求比例系数并判断图象所在象限。",
      learningObjectives: [
        "会判断一个式子是否为反比例函数。",
        "会由点坐标求 k 的值。",
        "会根据 k 的正负判断双曲线所在象限。",
      ],
      keyRules: [
        "反比例函数的一般形式是 y=k/x（k≠0）。",
        "k>0 时图象在第一、三象限；k<0 时在第二、四象限。",
        "点在图象上就满足 xy=k。",
      ],
      bodyBlocks: [
        {
          type: "richText",
          id: "g9x1-expression-context",
          title: "反比例函数最关键的是乘积不变",
          content: [
            "一次函数看加法关系，反比例函数看乘积关系。",
            "只要点在同一反比例函数图象上，就能用 x 与 y 的乘积建立联系。",
          ],
        },
      ],
      relatedExampleIds: ["example-g9x1-point"],
      order: 1,
      videoPlaceholder: {
        title: "板书微课：反比例函数先抓哪一条关系",
        durationLabel: "5 分钟",
        description: "用 xy=k 串起图象与解析式。",
      },
    },
    {
      id: "lesson-g9x1-application",
      chapterId: "g9-xia-unit-1",
      slug: "fan-bi-li-han-shu-shi-ji-ying-yong",
      title: "反比例函数的实际应用",
      summary: "会在速度、时间、面积等情境中识别反比例关系并建立模型。",
      learningObjectives: [
        "会识别“一个量增大，另一个量按乘积不变减小”的情境。",
        "会建立简单的反比例函数模型。",
        "能结合实际意义判断自变量取值范围。",
      ],
      keyRules: [
        "当两个量乘积为定值时，常可建立反比例函数模型。",
        "实际问题中自变量往往有取值范围限制。",
        "解题时既要算数值，也要解释量的实际意义。",
      ],
      bodyBlocks: [
        {
          type: "tip",
          id: "g9x1-app-tip",
          title: "易错提醒",
          content: "实际题里不是所有自变量都能取负数，列出函数式后还要回到情境中检查范围。",
        },
      ],
      relatedExampleIds: ["example-g9x1-model"],
      order: 2,
      videoPlaceholder: {
        title: "板书微课：反比例模型怎样从文字里读出来",
        durationLabel: "6 分钟",
        description: "抓住“乘积不变”的隐含条件。",
      },
    },
  ],
  workedExamples: [
    {
      id: "example-g9x1-point",
      chapterId: "g9-xia-unit-1",
      slug: "yong-dian-qiu-bi-li-xi-shu",
      title: "例题 1：由点坐标求 k",
      summary: "利用图象经过点的条件求反比例函数解析式。",
      problem: "反比例函数 y=k/x 的图象经过点 (2,6)，求 k 的值和解析式。",
      steps: [
        { id: "step-1", title: "代入坐标", content: "因为点在图象上，所以 6=k/2。" },
        { id: "step-2", title: "求出 k", content: "解得 k=12。" },
        { id: "step-3", title: "写解析式", content: "所以 y=12/x。" },
      ],
      answer: "k=12，解析式为 y=12/x",
      commonMistakes: ["把 k 误算成 3。"],
      relatedLessonIds: ["lesson-g9x1-expression"],
      order: 1,
    },
    {
      id: "example-g9x1-model",
      chapterId: "g9-xia-unit-1",
      slug: "gong-zuo-lv-yu-shi-jian",
      title: "例题 2：工作率与时间模型",
      summary: "用反比例函数刻画工作效率与完成时间的关系。",
      problem: "一项工作总量固定为 120，若每小时完成 x 单位，完成时间为 y 小时，写出 y 与 x 的关系。",
      steps: [
        { id: "step-1", title: "找乘积不变", content: "工作总量固定，所以 xy=120。" },
        { id: "step-2", title: "变形成函数式", content: "所以 y=120/x。" },
      ],
      answer: "y=120/x",
      commonMistakes: ["把关系错写成 y=120x。"],
      relatedLessonIds: ["lesson-g9x1-application"],
      order: 2,
    },
  ],
  quiz: {
    id: "quiz-g9-xia-unit-1",
    chapterId: "g9-xia-unit-1",
    title: "第一章单元小测",
    instructions:
      "共 10 题，基础 2 题、进阶 4 题、压轴 4 题，整体难度明显上调，更强调多步推理、信息提取与综合应用。",
    passingScore: 80,
    questions: [
      {
        id: "q1",
        quizId: "quiz-g9-xia-unit-1",
        type: "single-choice",
        difficulty: "basic",
        stem: "下列哪个式子表示反比例函数？",
        options: [
          { id: "a", label: "A", content: "y=3x" },
          { id: "b", label: "B", content: "y=3/x" },
          { id: "c", label: "C", content: "y=x+3" },
          { id: "d", label: "D", content: "y=x²" },
        ],
        correctOptionId: "b",
        explanation: "只有 y=3/x 符合 y=k/x 的形式。",
        relatedLessonIds: ["lesson-g9x1-expression"],
      },
      {
        id: "q2",
        quizId: "quiz-g9-xia-unit-1",
        type: "single-choice",
        difficulty: "basic",
        stem: "反比例函数 y=5/x 的图象位于哪两个象限？",
        options: [
          { id: "a", label: "A", content: "第一、三象限" },
          { id: "b", label: "B", content: "第二、四象限" },
          { id: "c", label: "C", content: "第一、二象限" },
          { id: "d", label: "D", content: "第三、四象限" },
        ],
        correctOptionId: "a",
        explanation: "k=5>0，所以图象在第一、三象限。",
        relatedLessonIds: ["lesson-g9x1-expression"],
      },
      {
        id: "q3",
        quizId: "quiz-g9-xia-unit-1",
        type: "fill-blank",
        difficulty: "advanced",
        stem: "若反比例函数 y=k/x 经过点 (4,3)，请填写 k 的值，并写出解析式。",
        blanks: [
          {
            id: "k",
            prompt: "k 的值",
            hint: "用 xy=k。",
            acceptableAnswers: ["12"],
            placeholder: "请填写结果",
          },
          {
            id: "expression",
            prompt: "依据相关关系，解析式",
            hint: "先判断所用关系或方法，再代回 y=k/x。",
            acceptableAnswers: ["y=12/x", "y = 12/x"],
            placeholder: "请填写结果",
          },
        ],
        explanation: "依据题目中的条件和相关性质，k=4×3=12，所以解析式是 y=12/x。",
        relatedLessonIds: ["lesson-g9x1-expression"],
      },
      {
        id: "q4",
        quizId: "quiz-g9-xia-unit-1",
        type: "single-choice",
        difficulty: "advanced",
        stem: "若点 A(2,m) 在反比例函数 y=-6/x 的图象上，则 m 等于多少？",
        options: [
          { id: "a", label: "A", content: "-3" },
          { id: "b", label: "B", content: "3" },
          { id: "c", label: "C", content: "-12" },
          { id: "d", label: "D", content: "12" },
        ],
        correctOptionId: "a",
        explanation: "m=-6/2=-3。",
        relatedLessonIds: ["lesson-g9x1-expression"],
      },
      {
        id: "q5",
        quizId: "quiz-g9-xia-unit-1",
        type: "fill-blank",
        difficulty: "advanced",
        stem: "若矩形面积恒为 24，长为 x，宽为 y。请填写 y 与 x 的函数关系，并说明这是哪类函数。",
        blanks: [
          {
            id: "expression",
            prompt: "函数关系",
            hint: "面积=长×宽。",
            acceptableAnswers: ["y=24/x", "y = 24/x"],
            placeholder: "请填写结果",
          },
          {
            id: "type",
            prompt: "函数类型",
            hint: "乘积为定值。",
            acceptableAnswers: ["反比例函数"],
            placeholder: "请填写结果",
          },
        ],
        explanation: "xy=24，所以 y=24/x，这是反比例函数。",
        relatedLessonIds: ["lesson-g9x1-application"],
      },
      {
        id: "q6",
        quizId: "quiz-g9-xia-unit-1",
        type: "single-choice",
        difficulty: "advanced",
        stem: "关于反比例函数 y=k/x，下列说法正确的是哪个？",
        options: [
          { id: "a", label: "A", content: "图象经过原点" },
          { id: "b", label: "B", content: "x 不能取 0" },
          { id: "c", label: "C", content: "图象是一条直线" },
          { id: "d", label: "D", content: "k 可以等于 0" },
        ],
        correctOptionId: "b",
        explanation: "反比例函数中分母不能为 0，所以 x 不能取 0。",
        relatedLessonIds: ["lesson-g9x1-expression"],
      },
      {
        id: "q7",
        quizId: "quiz-g9-xia-unit-1",
        type: "fill-blank",
        difficulty: "challenge",
        stem: "若点 A(1,8)、B(2,4) 在同一反比例函数图象上。请填写该函数的 k 值，并判断点 C(-4,-2) 是否也在该图象上。",
        blanks: [
          {
            id: "k",
            prompt: "k 的值",
            hint: "分别计算 xy。",
            acceptableAnswers: ["8"],
            placeholder: "请填写结果",
          },
          {
            id: "judge",
            prompt: "点 C 是否在图象上",
            hint: "检验 x 与 y 的乘积。",
            acceptableAnswers: ["是"],
            placeholder: "请填写判断",
          },
        ],
        explanation: "A、B 两点都满足 xy=8，而 C 也有 (-4)×(-2)=8，所以在同一图象上。",
        relatedLessonIds: ["lesson-g9x1-expression"],
      },
      {
        id: "q8",
        quizId: "quiz-g9-xia-unit-1",
        type: "single-choice",
        difficulty: "challenge",
        stem: "某工程完成时间 y 与每天工作人数 x 成反比例，且 6 人做需 10 天。若 15 人做，则需要多少天？",
        options: [
          { id: "a", label: "A", content: "2 天" },
          { id: "b", label: "B", content: "4 天" },
          { id: "c", label: "C", content: "6 天" },
          { id: "d", label: "D", content: "25 天" },
        ],
        correctOptionId: "b",
        explanation: "xy=60，所以 y=60/15=4。",
        relatedLessonIds: ["lesson-g9x1-application"],
      },
      {
        id: "q9",
        quizId: "quiz-g9-xia-unit-1",
        type: "fill-blank",
        difficulty: "challenge",
        stem: "反比例函数图象经过第一、三象限，且点 (3,n) 在图象上时 n<0。请填写这两个条件是否矛盾，并说明原因。",
        blanks: [
          {
            id: "judge",
            prompt: "是否矛盾",
            hint: "看 k 的正负。",
            acceptableAnswers: ["是"],
            placeholder: "请填写判断",
          },
          {
            id: "reason",
            prompt: "原因",
            hint: "第一、三象限对应 k>0。",
            acceptableAnswers: ["第一三象限说明k>0，此时x>0时y也应大于0", "k>0时x=3对应y应为正"],
            placeholder: "请填写原因",
          },
        ],
        explanation: "图象在第一、三象限说明 k>0，所以当 x=3>0 时，y 也应大于 0，与 n<0 矛盾。",
        relatedLessonIds: ["lesson-g9x1-expression"],
      },
      {
        id: "q10",
        quizId: "quiz-g9-xia-unit-1",
        type: "fill-blank",
        difficulty: "challenge",
        stem: "若反比例函数 y=k/x 中，当 x 从 2 增加到 4 时，y 从 6 变成多少？并说明变化依据。",
        blanks: [
          {
            id: "value",
            prompt: "新的 y 值",
            hint: "先由已知点求 k。",
            acceptableAnswers: ["3"],
            placeholder: "请填写结果",
          },
          {
            id: "basis",
            prompt: "变化依据",
            hint: "利用 xy=k。",
            acceptableAnswers: ["xy保持不变", "乘积不变"],
            placeholder: "请填写结果",
          },
        ],
        explanation: "已知 k=2×6=12，当 x=4 时，y=12/4=3，依据是 xy 保持不变。",
        relatedLessonIds: ["lesson-g9x1-expression", "lesson-g9x1-application"],
      },
    ],
  },
};
