import type { CurriculumSlice } from "@/types/content";

export const g9XiaUnit3Slice: CurriculumSlice = {
  grade: {
    id: "g9",
    label: "九年级",
    shortLabel: "九下",
    description: "围绕方程、函数与几何综合应用，进入中考主干能力训练阶段。",
  },
  volume: {
    id: "xia",
    gradeId: "g9",
    label: "下册",
    description: "以反比例函数、相似、三角函数和空间视图为主要内容。",
  },
  chapter: {
    id: "g9-xia-unit-3",
    gradeId: "g9",
    volumeId: "xia",
    slug: "rui-jiao-san-jiao-han-shu",
    title: "第三章 锐角三角函数",
    summary: "理解正弦、余弦、正切的定义，会在直角三角形和实际测量中应用三角函数。",
    order: 3,
    lessonIds: ["lesson-g9x3-definition", "lesson-g9x3-application"],
    workedExampleIds: ["example-g9x3-trig", "example-g9x3-height"],
    quizId: "quiz-g9-xia-unit-3",
  },
  lessons: [
    {
      id: "lesson-g9x3-definition",
      chapterId: "g9-xia-unit-3",
      slug: "san-jiao-han-shu-ding-yi",
      title: "正弦、余弦与正切",
      summary: "掌握锐角三角函数的定义，会根据已知边求三角函数值。",
      learningObjectives: [
        "会在直角三角形中识别对边、邻边和斜边。",
        "会计算 sin、cos、tan 的值。",
        "能根据角和边的关系选择合适的三角函数。",
      ],
      keyRules: [
        "sinA=对边/斜边。",
        "cosA=邻边/斜边。",
        "tanA=对边/邻边。",
      ],
      bodyBlocks: [
        {
          type: "richText",
          id: "g9x3-definition-context",
          title: "先定角，再定对边和邻边",
          content: [
            "三角函数最容易错在“对边、邻边”是相对某个锐角而言的。",
            "角一换，对边和邻边也会跟着换。",
          ],
        },
      ],
      relatedExampleIds: ["example-g9x3-trig"],
      order: 1,
      videoPlaceholder: {
        title: "板书微课：三角函数里的边到底怎么认",
        durationLabel: "5 分钟",
        description: "围绕指定锐角确定三条边角色。",
      },
    },
    {
      id: "lesson-g9x3-application",
      chapterId: "g9-xia-unit-3",
      slug: "san-jiao-han-shu-shi-ji-ying-yong",
      title: "锐角三角函数的应用",
      summary: "会用仰角、俯角和坡度等情境建立直角三角形模型。",
      learningObjectives: [
        "会在测高题中用正切或正弦建立关系。",
        "会根据已知量选择合适函数。",
        "能解释角度与边长比在实际中的意义。",
      ],
      keyRules: [
        "仰角、俯角题通常先画出水平线和视线。",
        "已知邻边和对边，常用正切。",
        "已知斜边时，常考虑正弦或余弦。",
      ],
      bodyBlocks: [
        {
          type: "tip",
          id: "g9x3-app-tip",
          title: "易错提醒",
          content: "测高题中常把视线、地面和目标高度组成的直角三角形画错，先画图再列式更稳。",
        },
      ],
      relatedExampleIds: ["example-g9x3-height"],
      order: 2,
      videoPlaceholder: {
        title: "板书微课：测高题为什么常用正切",
        durationLabel: "6 分钟",
        description: "从“已知邻边和对边”出发选择函数。",
      },
    },
  ],
  workedExamples: [
    {
      id: "example-g9x3-trig",
      chapterId: "g9-xia-unit-3",
      slug: "yi-zhi-bian-chang-qiu-tan-zhi",
      title: "例题 1：求三角函数值",
      summary: "在直角三角形中根据边长求指定角的三角函数值。",
      problem: "在 Rt△ABC 中，∠C=90°，AC=3，BC=4。求 tanA。",
      steps: [
        { id: "step-1", title: "确定相对边", content: "相对 ∠A 而言，对边是 BC，邻边是 AC。" },
        { id: "step-2", title: "代入定义", content: "tanA=BC/AC=4/3。" },
      ],
      answer: "4/3",
      commonMistakes: ["把对边和邻边看反。"],
      relatedLessonIds: ["lesson-g9x3-definition"],
      order: 1,
    },
    {
      id: "example-g9x3-height",
      chapterId: "g9-xia-unit-3",
      slug: "yang-jiao-ce-gao",
      title: "例题 2：利用仰角测高",
      summary: "在实际测量中用正切建立高度关系。",
      problem: "人在离塔底 10 米处观测塔顶，仰角为 45°。求塔高。",
      steps: [
        { id: "step-1", title: "建立模型", content: "将塔高看作对边，人与塔底距离看作邻边。" },
        { id: "step-2", title: "列式", content: "tan45°=h/10。" },
        { id: "step-3", title: "求高", content: "因为 tan45°=1，所以 h=10。" },
      ],
      answer: "10 米",
      commonMistakes: ["没有把塔高和水平距离对应到正切定义。"],
      relatedLessonIds: ["lesson-g9x3-application"],
      order: 2,
    },
  ],
  quiz: {
    id: "quiz-g9-xia-unit-3",
    chapterId: "g9-xia-unit-3",
    title: "第三章单元小测",
    instructions:
      "共 10 题，基础 2 题、进阶 4 题、压轴 4 题，整体难度明显上调，更强调多步推理、信息提取与综合应用。",
    passingScore: 80,
    questions: [
      {
        id: "q1",
        quizId: "quiz-g9-xia-unit-3",
        type: "single-choice",
        difficulty: "basic",
        stem: "在直角三角形中，sinA 等于什么？",
        options: [
          { id: "a", label: "A", content: "对边/斜边" },
          { id: "b", label: "B", content: "邻边/斜边" },
          { id: "c", label: "C", content: "对边/邻边" },
          { id: "d", label: "D", content: "斜边/对边" },
        ],
        correctOptionId: "a",
        explanation: "正弦定义为对边比斜边。",
        relatedLessonIds: ["lesson-g9x3-definition"],
      },
      {
        id: "q2",
        quizId: "quiz-g9-xia-unit-3",
        type: "single-choice",
        difficulty: "basic",
        stem: "在 Rt△ABC 中，∠C=90°。相对 ∠A，BC 属于哪条边？",
        options: [
          { id: "a", label: "A", content: "斜边" },
          { id: "b", label: "B", content: "邻边" },
          { id: "c", label: "C", content: "对边" },
          { id: "d", label: "D", content: "中线" },
        ],
        correctOptionId: "c",
        explanation: "相对 ∠A，BC 是对边。",
        relatedLessonIds: ["lesson-g9x3-definition"],
      },
      {
        id: "q3",
        quizId: "quiz-g9-xia-unit-3",
        type: "fill-blank",
        difficulty: "advanced",
        stem: "在 Rt△ABC 中，∠C=90°，AC=3，BC=4。请填写 tanA 和 sinA 的值。",
        blanks: [
          {
            id: "tan",
            prompt: "tanA",
            hint: "对边/邻边。",
            acceptableAnswers: ["4/3"],
            placeholder: "请填写结果",
          },
          {
            id: "sin",
            prompt: "依据相关关系，sinA",
            hint: "先判断所用关系或方法，再先求斜边。",
            acceptableAnswers: ["4/5"],
            placeholder: "请填写结果",
          },
        ],
        explanation: "依据题目中的条件和相关性质，斜边 AB=5，所以 tanA=4/3，sinA=4/5。",
        relatedLessonIds: ["lesson-g9x3-definition"],
      },
      {
        id: "q4",
        quizId: "quiz-g9-xia-unit-3",
        type: "single-choice",
        difficulty: "advanced",
        stem: "若 tanA=1，则在锐角范围内 A 等于多少？",
        options: [
          { id: "a", label: "A", content: "30°" },
          { id: "b", label: "B", content: "45°" },
          { id: "c", label: "C", content: "60°" },
          { id: "d", label: "D", content: "75°" },
        ],
        correctOptionId: "b",
        explanation: "在常见特殊角中，tan45°=1。",
        relatedLessonIds: ["lesson-g9x3-definition"],
      },
      {
        id: "q5",
        quizId: "quiz-g9-xia-unit-3",
        type: "fill-blank",
        difficulty: "advanced",
        stem: "在 Rt△ABC 中，∠C=90°，AB=10，AC=6。请填写 cosA 的值，并求 BC 的长度。",
        blanks: [
          {
            id: "cos",
            prompt: "cosA",
            hint: "邻边/斜边。",
            acceptableAnswers: ["3/5", "6/10"],
            placeholder: "请填写结果",
          },
          {
            id: "bc",
            prompt: "BC 的长度",
            hint: "可用勾股定理。",
            acceptableAnswers: ["8"],
            placeholder: "请填写结果",
          },
        ],
        explanation: "cosA=6/10=3/5，BC=8。",
        relatedLessonIds: ["lesson-g9x3-definition"],
      },
      {
        id: "q6",
        quizId: "quiz-g9-xia-unit-3",
        type: "single-choice",
        difficulty: "advanced",
        stem: "人在离旗杆底部 12 米处看到旗杆顶，仰角 45°。旗杆高是多少？",
        options: [
          { id: "a", label: "A", content: "6 米" },
          { id: "b", label: "B", content: "10 米" },
          { id: "c", label: "C", content: "12 米" },
          { id: "d", label: "D", content: "24 米" },
        ],
        correctOptionId: "c",
        explanation: "tan45°=h/12=1，所以 h=12。",
        relatedLessonIds: ["lesson-g9x3-application"],
      },
      {
        id: "q7",
        quizId: "quiz-g9-xia-unit-3",
        type: "fill-blank",
        difficulty: "challenge",
        stem: "某斜坡坡角为 30°，斜坡长 20 米。请填写坡高，并说明这里更适合用 sin 还是 tan。",
        blanks: [
          {
            id: "height",
            prompt: "坡高",
            hint: "已知斜边和对边关系。",
            acceptableAnswers: ["10"],
            placeholder: "请填写结果",
          },
          {
            id: "func",
            prompt: "更适合的函数",
            hint: "对边/斜边。",
            acceptableAnswers: ["sin", "正弦"],
            placeholder: "请填写结果",
          },
        ],
        explanation: "sin30°=h/20=1/2，所以 h=10；已知斜边时更适合用正弦。",
        relatedLessonIds: ["lesson-g9x3-application"],
      },
      {
        id: "q8",
        quizId: "quiz-g9-xia-unit-3",
        type: "single-choice",
        difficulty: "challenge",
        stem: "在 Rt△ABC 中，∠C=90°，若 sinA=3/5，则 tanA 等于多少？",
        options: [
          { id: "a", label: "A", content: "3/4" },
          { id: "b", label: "B", content: "4/3" },
          { id: "c", label: "C", content: "3/5" },
          { id: "d", label: "D", content: "5/3" },
        ],
        correctOptionId: "a",
        explanation: "由 3-4-5 直角三角形关系可得 tanA=3/4。",
        relatedLessonIds: ["lesson-g9x3-definition"],
      },
      {
        id: "q9",
        quizId: "quiz-g9-xia-unit-3",
        type: "fill-blank",
        difficulty: "challenge",
        stem: "某楼高 h，从楼前 15 米处观测楼顶，仰角为 45°；若再后退 5 米，仰角变小。请填写 h 的值，并判断第二次仰角是变大还是变小。",
        blanks: [
          {
            id: "height",
            prompt: "楼高 h",
            hint: "第一次观测直接用 tan45°。",
            acceptableAnswers: ["15"],
            placeholder: "请填写结果",
          },
          {
            id: "angle",
            prompt: "第二次仰角变化",
            hint: "距离增大，同高情况下仰角会减小。",
            acceptableAnswers: ["变小"],
            placeholder: "请填写结果",
          },
        ],
        explanation: "第一次有 tan45°=h/15，所以 h=15；距离变大时仰角变小。",
        relatedLessonIds: ["lesson-g9x3-application"],
      },
      {
        id: "q10",
        quizId: "quiz-g9-xia-unit-3",
        type: "fill-blank",
        difficulty: "challenge",
        stem: "在 Rt△ABC 中，∠C=90°，若 tanA=2，且 AC=7。请填写 BC 的长度，并说明你为什么不需要先求斜边也能完成计算。",
        blanks: [
          {
            id: "bc",
            prompt: "BC 的长度",
            hint: "tanA=BC/AC。",
            acceptableAnswers: ["14"],
            placeholder: "请填写结果",
          },
          {
            id: "reason",
            prompt: "原因",
            hint: "正切直接联系对边和邻边。",
            acceptableAnswers: ["正切直接等于对边比邻边", "tan直接用对边和邻边"],
            placeholder: "请填写结果",
          },
        ],
        explanation: "tanA=BC/AC=2，所以 BC=14；正切定义不涉及斜边，因此可以直接求。",
        relatedLessonIds: ["lesson-g9x3-definition", "lesson-g9x3-application"],
      },
    ],
  },
};
