import type { CurriculumSlice } from "@/types/content";

export const g9XiaUnit4Slice: CurriculumSlice = {
  grade: {
    id: "g9",
    label: "九年级",
    shortLabel: "九下",
    description: "围绕方程、函数与几何综合应用，进入中考主干能力训练阶段。",
  },
  volume: {
    id: "xia",
    gradeId: "g9",
    label: "下册",
    description: "以反比例函数、相似、三角函数和空间视图为主要内容。",
  },
  chapter: {
    id: "g9-xia-unit-4",
    gradeId: "g9",
    volumeId: "xia",
    slug: "tou-ying-yu-shi-tu",
    title: "第四章 投影与视图",
    summary: "理解中心投影与平行投影，会识别三视图并在立体图形与平面图形之间转化。",
    order: 4,
    lessonIds: ["lesson-g9x4-projection", "lesson-g9x4-view"],
    workedExampleIds: ["example-g9x4-shadow", "example-g9x4-three-view"],
    quizId: "quiz-g9-xia-unit-4",
  },
  lessons: [
    {
      id: "lesson-g9x4-projection",
      chapterId: "g9-xia-unit-4",
      slug: "tou-ying-de-ji-ben-gai-nian",
      title: "投影的基本概念",
      summary: "理解中心投影与平行投影的区别，知道光线方向对影子的影响。",
      learningObjectives: [
        "会区分中心投影和平行投影。",
        "知道平行光线下同方向物体影子关系。",
        "会从影子变化反推投影方式。",
      ],
      keyRules: [
        "太阳光近似看作平行投影。",
        "点光源形成的投影更接近中心投影。",
        "投影方向不同，影子的形状和长度会变化。",
      ],
      bodyBlocks: [
        {
          type: "richText",
          id: "g9x4-projection-context",
          title: "先判断光线，再谈影子",
          content: [
            "投影题最核心的不是背定义，而是先判断光线是平行还是从一点发出。",
            "一旦投影方式确定，后面的图形变化就更容易解释。",
          ],
        },
      ],
      relatedExampleIds: ["example-g9x4-shadow"],
      order: 1,
      videoPlaceholder: {
        title: "板书微课：投影题先看什么",
        durationLabel: "5 分钟",
        description: "先判断光源，再分析影子。",
      },
    },
    {
      id: "lesson-g9x4-view",
      chapterId: "g9-xia-unit-4",
      slug: "san-shi-tu-yu-li-ti-tu-xing",
      title: "三视图与立体图形",
      summary: "会识别主视图、左视图、俯视图，并根据三视图想象立体图形。",
      learningObjectives: [
        "会区分主视图、左视图和俯视图。",
        "会由简单立体图形画出三视图。",
        "会根据三视图判断立体图形的基本结构。",
      ],
      keyRules: [
        "主视图看正面，左视图看左侧，俯视图从上往下看。",
        "三视图反映的是同一物体的不同方向形状。",
        "判断立体图形时要综合三视图信息，而不是只看一张。",
      ],
      bodyBlocks: [
        {
          type: "tip",
          id: "g9x4-view-tip",
          title: "易错提醒",
          content: "左视图不是“站在左边看左边那一面”，而是从左向右观察整个物体。",
        },
      ],
      relatedExampleIds: ["example-g9x4-three-view"],
      order: 2,
      videoPlaceholder: {
        title: "板书微课：三视图怎样和立体图对上",
        durationLabel: "6 分钟",
        description: "通过方向切换建立空间感。",
      },
    },
  ],
  workedExamples: [
    {
      id: "example-g9x4-shadow",
      chapterId: "g9-xia-unit-4",
      slug: "ping-xing-tou-ying-ying-zi",
      title: "例题 1：平行投影下的影子",
      summary: "在平行投影背景下理解影长变化与方向关系。",
      problem: "在同一时刻的太阳光下，两根竖直杆的影子方向是否相同？说明理由。",
      steps: [
        { id: "step-1", title: "判断投影方式", content: "太阳光近似看作平行投影。" },
        { id: "step-2", title: "分析方向", content: "平行光线方向相同，所以同一时刻竖直杆影子方向相同。" },
      ],
      answer: "相同，因为属于平行投影",
      commonMistakes: ["只说“太阳一样”，没有解释平行光线。"],
      relatedLessonIds: ["lesson-g9x4-projection"],
      order: 1,
    },
    {
      id: "example-g9x4-three-view",
      chapterId: "g9-xia-unit-4",
      slug: "chang-fang-ti-san-shi-tu",
      title: "例题 2：长方体的三视图",
      summary: "认识简单几何体三视图之间的对应关系。",
      problem: "一个长方体长 4、宽 3、高 2。写出它的主视图和俯视图分别是什么形状及边长。",
      steps: [
        { id: "step-1", title: "看主视图", content: "主视图反映长和高，所以是长 4、高 2 的长方形。" },
        { id: "step-2", title: "看俯视图", content: "俯视图反映长和宽，所以是长 4、宽 3 的长方形。" },
      ],
      answer: "主视图是 4×2 的长方形，俯视图是 4×3 的长方形",
      commonMistakes: ["把高和宽放错到同一视图里。"],
      relatedLessonIds: ["lesson-g9x4-view"],
      order: 2,
    },
  ],
  quiz: {
    id: "quiz-g9-xia-unit-4",
    chapterId: "g9-xia-unit-4",
    title: "第四章单元小测",
    instructions:
      "共 10 题，基础 2 题、进阶 4 题、压轴 4 题，整体难度明显上调，更强调多步推理、信息提取与综合应用。",
    passingScore: 80,
    questions: [
      {
        id: "q1",
        quizId: "quiz-g9-xia-unit-4",
        type: "single-choice",
        difficulty: "basic",
        stem: "太阳光下形成的投影更接近哪一种？",
        options: [
          { id: "a", label: "A", content: "中心投影" },
          { id: "b", label: "B", content: "平行投影" },
          { id: "c", label: "C", content: "旋转投影" },
          { id: "d", label: "D", content: "对称投影" },
        ],
        correctOptionId: "b",
        explanation: "太阳光可近似看作平行光，因此是平行投影。",
        relatedLessonIds: ["lesson-g9x4-projection"],
      },
      {
        id: "q2",
        quizId: "quiz-g9-xia-unit-4",
        type: "single-choice",
        difficulty: "basic",
        stem: "从上往下观察物体得到的视图叫做什么？",
        options: [
          { id: "a", label: "A", content: "主视图" },
          { id: "b", label: "B", content: "左视图" },
          { id: "c", label: "C", content: "俯视图" },
          { id: "d", label: "D", content: "后视图" },
        ],
        correctOptionId: "c",
        explanation: "从上往下观察得到的是俯视图。",
        relatedLessonIds: ["lesson-g9x4-view"],
      },
      {
        id: "q3",
        quizId: "quiz-g9-xia-unit-4",
        type: "fill-blank",
        difficulty: "advanced",
        stem: "在同一时刻的太阳光下，两根竖直杆的影子方向有什么关系？并说明原因。",
        blanks: [
          {
            id: "relation",
            prompt: "影子方向关系",
            hint: "同一时刻太阳光方向相同。",
            acceptableAnswers: ["相同"],
            placeholder: "请填写结果",
          },
          {
            id: "reason",
            prompt: "原因",
            hint: "先判断所用关系或方法，再属于平行投影。",
            acceptableAnswers: ["太阳光近似平行", "属于平行投影"],
            placeholder: "请填写结果",
          },
        ],
        explanation: "依据题目中的条件和相关性质，在同一时刻太阳光方向相同，因此竖直杆影子方向相同。",
        relatedLessonIds: ["lesson-g9x4-projection"],
      },
      {
        id: "q4",
        quizId: "quiz-g9-xia-unit-4",
        type: "single-choice",
        difficulty: "advanced",
        stem: "一个长方体的主视图一定是什么图形？",
        options: [
          { id: "a", label: "A", content: "圆" },
          { id: "b", label: "B", content: "三角形" },
          { id: "c", label: "C", content: "长方形" },
          { id: "d", label: "D", content: "梯形" },
        ],
        correctOptionId: "c",
        explanation: "长方体从正面看得到长方形。",
        relatedLessonIds: ["lesson-g9x4-view"],
      },
      {
        id: "q5",
        quizId: "quiz-g9-xia-unit-4",
        type: "fill-blank",
        difficulty: "advanced",
        stem: "一个长方体长 5、宽 4、高 3。请填写主视图对应的两个尺寸，以及俯视图对应的两个尺寸。",
        blanks: [
          {
            id: "front",
            prompt: "主视图尺寸",
            hint: "主视图看长和高。",
            acceptableAnswers: ["5和3", "5、3"],
            placeholder: "请填写结果",
          },
          {
            id: "top",
            prompt: "俯视图尺寸",
            hint: "俯视图看长和宽。",
            acceptableAnswers: ["5和4", "5、4"],
            placeholder: "请填写结果",
          },
        ],
        explanation: "主视图看长和高，俯视图看长和宽。",
        relatedLessonIds: ["lesson-g9x4-view"],
      },
      {
        id: "q6",
        quizId: "quiz-g9-xia-unit-4",
        type: "single-choice",
        difficulty: "advanced",
        stem: "下列关于中心投影的说法正确的是哪个？",
        options: [
          { id: "a", label: "A", content: "光线互相平行" },
          { id: "b", label: "B", content: "来自一个点光源" },
          { id: "c", label: "C", content: "一定没有近大远小现象" },
          { id: "d", label: "D", content: "与平行投影完全相同" },
        ],
        correctOptionId: "b",
        explanation: "中心投影常来自一点光源。",
        relatedLessonIds: ["lesson-g9x4-projection"],
      },
      {
        id: "q7",
        quizId: "quiz-g9-xia-unit-4",
        type: "fill-blank",
        difficulty: "challenge",
        stem: "一个圆柱从正面看和从左面看都是什么图形？从上面看又是什么图形？",
        blanks: [
          {
            id: "front-left",
            prompt: "正面和左面",
            hint: "侧面投影。",
            acceptableAnswers: ["长方形", "都是长方形"],
            placeholder: "请填写结果",
          },
          {
            id: "top",
            prompt: "上面",
            hint: "底面投影。",
            acceptableAnswers: ["圆"],
            placeholder: "请填写结果",
          },
        ],
        explanation: "圆柱正视图和左视图通常是长方形，俯视图是圆。",
        relatedLessonIds: ["lesson-g9x4-view"],
      },
      {
        id: "q8",
        quizId: "quiz-g9-xia-unit-4",
        type: "single-choice",
        difficulty: "challenge",
        stem: "同一物体的三视图中，如果主视图和左视图都是正方形，俯视图是长方形，则这个物体最可能是哪个？",
        options: [
          { id: "a", label: "A", content: "长方体" },
          { id: "b", label: "B", content: "圆柱" },
          { id: "c", label: "C", content: "球" },
          { id: "d", label: "D", content: "圆锥" },
        ],
        correctOptionId: "a",
        explanation: "这类三视图组合更符合某些长方体的投影特征。",
        relatedLessonIds: ["lesson-g9x4-view"],
      },
      {
        id: "q9",
        quizId: "quiz-g9-xia-unit-4",
        type: "fill-blank",
        difficulty: "challenge",
        stem: "如果点光源从物体左前方照射，一个竖直杆的影子长度会随着光源高度升高而怎样变化？并说明原因。",
        blanks: [
          {
            id: "change",
            prompt: "影长变化",
            hint: "光越高，影子越短。",
            acceptableAnswers: ["变短"],
            placeholder: "请填写结果",
          },
          {
            id: "reason",
            prompt: "原因",
            hint: "投影角度更接近竖直。",
            acceptableAnswers: ["光线更接近竖直，所以影子更短", "投影角度变化使影子缩短"],
            placeholder: "请填写结果",
          },
        ],
        explanation: "光源越高，光线越接近竖直方向，影子会变短。",
        relatedLessonIds: ["lesson-g9x4-projection"],
      },
      {
        id: "q10",
        quizId: "quiz-g9-xia-unit-4",
        type: "fill-blank",
        difficulty: "challenge",
        stem: "一个长方体的主视图是 6×4 的长方形，俯视图是 6×3 的长方形。请填写这个长方体的长、宽、高，并说明左视图尺寸。",
        blanks: [
          {
            id: "size",
            prompt: "长宽高",
            hint: "由主视图和俯视图综合判断。",
            acceptableAnswers: ["长6宽3高4", "6、3、4"],
            placeholder: "请填写结果",
          },
          {
            id: "left",
            prompt: "左视图尺寸",
            hint: "左视图看宽和高。",
            acceptableAnswers: ["3和4", "3、4"],
            placeholder: "请填写结果",
          },
        ],
        explanation: "主视图给出长和高，俯视图给出长和宽，所以长 6、宽 3、高 4；左视图尺寸为 3 和 4。",
        relatedLessonIds: ["lesson-g9x4-view", "lesson-g9x4-projection"],
      },
    ],
  },
};
